# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "pm2"
      - dependency-name: "forgescript"
      - dependency-name: "forgedb"
      - dependency-name: "discord.js"
      - dependency-name: "axios"
      - dependency-name: "typescript"
      - dependency-name: "node.js"
    commit-message:
      prefix: "npm"
      prefix-development: "npm dev"
    labels:
      - "npm"
      - "dependencies"
    pull-request-branch-name:
      separator: "-"
