import { InteractionCommand } from '@/types'

const commands: InteractionCommand[] = [
  {
    type: "interactionCreate",
    version: "V1.0.0",
    code: `
      $textSplit[$customID;~]

      $onlyIf[$splitText[0]==counter;]
      $onlyIf[$splitText[2]==$authorID;]

      $let[userID;$splitText[3]]
      $let[user;$getUserVar[uuid;$customEncrypt[encrypt;$get[userID]]]]

      $switch[$splitText[1];
        $case[positive;
          $interactionUpdate[
            $color[$getUserVar[color;$get[user]]]
            $author[$username[$get[userID]]'s roleplay counter;$userAvatar[$get[userID]]]

$let[blush-give;$if[$getVar[blush-give;$get[user]]!=;$if[$getVar[blush-give;$get[user]]<=9;   $getVar[blush-give;$get[user]]   ;$if[$getVar[blush-give;$get[user]]<=99;   $getVar[blush-give;$get[user]]  ;$if[$getVar[blush-give;$get[user]]<=999;  $getVar[blush-give;$get[user]]  ;$if[$getVar[blush-give;$get[user]]<=9999;  $getVar[blush-give;$get[user]] ;$if[$getVar[blush-give;$get[user]]<=99999; $getVar[blush-give;$get[user]] ;$if[$getVar[blush-give;$get[user]]<=999999; $getVar[blush-give;$get[user]];$if[$getVar[blush-give;$get[user]]<=9999999;$getVar[blush-give;$get[user]];9999999]]]]]]];   0   ]]
$let[blush-gotten;$if[$getVar[blush-gotten;$get[user]]!=;$if[$getVar[blush-gotten;$get[user]]<=9;   $getVar[blush-gotten;$get[user]]   ;$if[$getVar[blush-gotten;$get[user]]<=99;   $getVar[blush-gotten;$get[user]]  ;$if[$getVar[blush-gotten;$get[user]]<=999;  $getVar[blush-gotten;$get[user]]  ;$if[$getVar[blush-gotten;$get[user]]<=9999;  $getVar[blush-gotten;$get[user]] ;$if[$getVar[blush-gotten;$get[user]]<=99999; $getVar[blush-gotten;$get[user]] ;$if[$getVar[blush-gotten;$get[user]]<=999999; $getVar[blush-gotten;$get[user]];$if[$getVar[blush-gotten;$get[user]]<=9999999;$getVar[blush-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[blush-sum;$sum[$replace[$getVar[blush-gotten;$get[user]]; ;;-1];$replace[$getVar[blush-give;$get[user]]; ;;-1]]]
$let[blush;$if[$get[blush-sum]!=;$if[$get[blush-sum]<=9;   $get[blush-sum]   ;$if[$get[blush-sum]<=99;   $get[blush-sum]  ;$if[$get[blush-sum]<=999;  $get[blush-sum]  ;$if[$get[blush-sum]<=9999;  $get[blush-sum] ;$if[$get[blush-sum]<=99999; $get[blush-sum] ;$if[$get[blush-sum]<=999999; $get[blush-sum];$if[$get[blush-sum]<=9999999;$get[blush-sum];9999999]]]]]]];   0   ]]

$let[boop-give;$if[$getVar[boop-give;$get[user]]!=;$if[$getVar[boop-give;$get[user]]<=9;   $getVar[boop-give;$get[user]]   ;$if[$getVar[boop-give;$get[user]]<=99;   $getVar[boop-give;$get[user]]  ;$if[$getVar[boop-give;$get[user]]<=999;  $getVar[boop-give;$get[user]]  ;$if[$getVar[boop-give;$get[user]]<=9999;  $getVar[boop-give;$get[user]] ;$if[$getVar[boop-give;$get[user]]<=99999; $getVar[boop-give;$get[user]] ;$if[$getVar[boop-give;$get[user]]<=999999; $getVar[boop-give;$get[user]];$if[$getVar[boop-give;$get[user]]<=9999999;$getVar[boop-give;$get[user]];9999999]]]]]]];   0   ]]
$let[boop-gotten;$if[$getVar[boop-gotten;$get[user]]!=;$if[$getVar[boop-gotten;$get[user]]<=9;   $getVar[boop-gotten;$get[user]]   ;$if[$getVar[boop-gotten;$get[user]]<=99;   $getVar[boop-gotten;$get[user]]  ;$if[$getVar[boop-gotten;$get[user]]<=999;  $getVar[boop-gotten;$get[user]]  ;$if[$getVar[boop-gotten;$get[user]]<=9999;  $getVar[boop-gotten;$get[user]] ;$if[$getVar[boop-gotten;$get[user]]<=99999; $getVar[boop-gotten;$get[user]] ;$if[$getVar[boop-gotten;$get[user]]<=999999; $getVar[boop-gotten;$get[user]];$if[$getVar[boop-gotten;$get[user]]<=9999999;$getVar[boop-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[boop-sum;$sum[$replace[$getVar[boop-gotten;$get[user]]; ;;-1];$replace[$getVar[boop-give;$get[user]]; ;;-1]]]
$let[boop;$if[$get[boop-sum]!=;$if[$get[boop-sum]<=9;   $get[boop-sum]   ;$if[$get[boop-sum]<=99;   $get[boop-sum]  ;$if[$get[boop-sum]<=999;  $get[boop-sum]  ;$if[$get[boop-sum]<=9999;  $get[boop-sum] ;$if[$get[boop-sum]<=99999; $get[boop-sum] ;$if[$get[boop-sum]<=999999; $get[boop-sum];$if[$get[boop-sum]<=9999999;$get[boop-sum];9999999]]]]]]];   0   ]]

$let[cheer-give;$if[$getVar[cheer-give;$get[user]]!=;$if[$getVar[cheer-give;$get[user]]<=9;   $getVar[cheer-give;$get[user]]   ;$if[$getVar[cheer-give;$get[user]]<=99;   $getVar[cheer-give;$get[user]]  ;$if[$getVar[cheer-give;$get[user]]<=999;  $getVar[cheer-give;$get[user]]  ;$if[$getVar[cheer-give;$get[user]]<=9999;  $getVar[cheer-give;$get[user]] ;$if[$getVar[cheer-give;$get[user]]<=99999; $getVar[cheer-give;$get[user]] ;$if[$getVar[cheer-give;$get[user]]<=999999; $getVar[cheer-give;$get[user]];$if[$getVar[cheer-give;$get[user]]<=9999999;$getVar[cheer-give;$get[user]];9999999]]]]]]];   0   ]]
$let[cheer-gotten;$if[$getVar[cheer-gotten;$get[user]]!=;$if[$getVar[cheer-gotten;$get[user]]<=9;   $getVar[cheer-gotten;$get[user]]   ;$if[$getVar[cheer-gotten;$get[user]]<=99;   $getVar[cheer-gotten;$get[user]]  ;$if[$getVar[cheer-gotten;$get[user]]<=999;  $getVar[cheer-gotten;$get[user]]  ;$if[$getVar[cheer-gotten;$get[user]]<=9999;  $getVar[cheer-gotten;$get[user]] ;$if[$getVar[cheer-gotten;$get[user]]<=99999; $getVar[cheer-gotten;$get[user]] ;$if[$getVar[cheer-gotten;$get[user]]<=999999; $getVar[cheer-gotten;$get[user]];$if[$getVar[cheer-gotten;$get[user]]<=9999999;$getVar[cheer-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[cheer-sum;$sum[$replace[$getVar[cheer-gotten;$get[user]]; ;;-1];$replace[$getVar[cheer-give;$get[user]]; ;;-1]]]
$let[cheer;$if[$get[cheer-sum]!=;$if[$get[cheer-sum]<=9;   $get[cheer-sum]   ;$if[$get[cheer-sum]<=99;   $get[cheer-sum]  ;$if[$get[cheer-sum]<=999;  $get[cheer-sum]  ;$if[$get[cheer-sum]<=9999;  $get[cheer-sum] ;$if[$get[cheer-sum]<=99999; $get[cheer-sum] ;$if[$get[cheer-sum]<=999999; $get[cheer-sum];$if[$get[cheer-sum]<=9999999;$get[cheer-sum];9999999]]]]]]];   0   ]]

$let[cuddle-give;$if[$getVar[cuddle-give;$get[user]]!=;$if[$getVar[cuddle-give;$get[user]]<=9;   $getVar[cuddle-give;$get[user]]   ;$if[$getVar[cuddle-give;$get[user]]<=99;   $getVar[cuddle-give;$get[user]]  ;$if[$getVar[cuddle-give;$get[user]]<=999;  $getVar[cuddle-give;$get[user]]  ;$if[$getVar[cuddle-give;$get[user]]<=9999;  $getVar[cuddle-give;$get[user]] ;$if[$getVar[cuddle-give;$get[user]]<=99999; $getVar[cuddle-give;$get[user]] ;$if[$getVar[cuddle-give;$get[user]]<=999999; $getVar[cuddle-give;$get[user]];$if[$getVar[cuddle-give;$get[user]]<=9999999;$getVar[cuddle-give;$get[user]];9999999]]]]]]];   0   ]]
$let[cuddle-gotten;$if[$getVar[cuddle-gotten;$get[user]]!=;$if[$getVar[cuddle-gotten;$get[user]]<=9;   $getVar[cuddle-gotten;$get[user]]   ;$if[$getVar[cuddle-gotten;$get[user]]<=99;   $getVar[cuddle-gotten;$get[user]]  ;$if[$getVar[cuddle-gotten;$get[user]]<=999;  $getVar[cuddle-gotten;$get[user]]  ;$if[$getVar[cuddle-gotten;$get[user]]<=9999;  $getVar[cuddle-gotten;$get[user]] ;$if[$getVar[cuddle-gotten;$get[user]]<=99999; $getVar[cuddle-gotten;$get[user]] ;$if[$getVar[cuddle-gotten;$get[user]]<=999999; $getVar[cuddle-gotten;$get[user]];$if[$getVar[cuddle-gotten;$get[user]]<=9999999;$getVar[cuddle-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[cuddle-sum;$sum[$replace[$getVar[cuddle-gotten;$get[user]]; ;;-1];$replace[$getVar[cuddle-give;$get[user]]; ;;-1]]]
$let[cuddle;$if[$get[cuddle-sum]!=;$if[$get[cuddle-sum]<=9;   $get[cuddle-sum]   ;$if[$get[cuddle-sum]<=99;   $get[cuddle-sum]  ;$if[$get[cuddle-sum]<=999;  $get[cuddle-sum]  ;$if[$get[cuddle-sum]<=9999;  $get[cuddle-sum] ;$if[$get[cuddle-sum]<=99999; $get[cuddle-sum] ;$if[$get[cuddle-sum]<=999999; $get[cuddle-sum];$if[$get[cuddle-sum]<=9999999;$get[cuddle-sum];9999999]]]]]]];   0   ]]

$let[dance-give;$if[$getVar[dance-give;$get[user]]!=;$if[$getVar[dance-give;$get[user]]<=9;   $getVar[dance-give;$get[user]]   ;$if[$getVar[dance-give;$get[user]]<=99;   $getVar[dance-give;$get[user]]  ;$if[$getVar[dance-give;$get[user]]<=999;  $getVar[dance-give;$get[user]]  ;$if[$getVar[dance-give;$get[user]]<=9999;  $getVar[dance-give;$get[user]] ;$if[$getVar[dance-give;$get[user]]<=99999; $getVar[dance-give;$get[user]] ;$if[$getVar[dance-give;$get[user]]<=999999; $getVar[dance-give;$get[user]];$if[$getVar[dance-give;$get[user]]<=9999999;$getVar[dance-give;$get[user]];9999999]]]]]]];   0   ]]
$let[dance-gotten;$if[$getVar[dance-gotten;$get[user]]!=;$if[$getVar[dance-gotten;$get[user]]<=9;   $getVar[dance-gotten;$get[user]]   ;$if[$getVar[dance-gotten;$get[user]]<=99;   $getVar[dance-gotten;$get[user]]  ;$if[$getVar[dance-gotten;$get[user]]<=999;  $getVar[dance-gotten;$get[user]]  ;$if[$getVar[dance-gotten;$get[user]]<=9999;  $getVar[dance-gotten;$get[user]] ;$if[$getVar[dance-gotten;$get[user]]<=99999; $getVar[dance-gotten;$get[user]] ;$if[$getVar[dance-gotten;$get[user]]<=999999; $getVar[dance-gotten;$get[user]];$if[$getVar[dance-gotten;$get[user]]<=9999999;$getVar[dance-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[dance-sum;$sum[$replace[$getVar[dance-gotten;$get[user]]; ;;-1];$replace[$getVar[dance-give;$get[user]]; ;;-1]]]
$let[dance;$if[$get[dance-sum]!=;$if[$get[dance-sum]<=9;   $get[dance-sum]   ;$if[$get[dance-sum]<=99;   $get[dance-sum]  ;$if[$get[dance-sum]<=999;  $get[dance-sum]  ;$if[$get[dance-sum]<=9999;  $get[dance-sum] ;$if[$get[dance-sum]<=99999; $get[dance-sum] ;$if[$get[dance-sum]<=999999; $get[dance-sum];$if[$get[dance-sum]<=9999999;$get[dance-sum];9999999]]]]]]];   0   ]]

$let[feed-give;$if[$getVar[feed-give;$get[user]]!=;$if[$getVar[feed-give;$get[user]]<=9;   $getVar[feed-give;$get[user]]   ;$if[$getVar[feed-give;$get[user]]<=99;   $getVar[feed-give;$get[user]]  ;$if[$getVar[feed-give;$get[user]]<=999;  $getVar[feed-give;$get[user]]  ;$if[$getVar[feed-give;$get[user]]<=9999;  $getVar[feed-give;$get[user]] ;$if[$getVar[feed-give;$get[user]]<=99999; $getVar[feed-give;$get[user]] ;$if[$getVar[feed-give;$get[user]]<=999999; $getVar[feed-give;$get[user]];$if[$getVar[feed-give;$get[user]]<=9999999;$getVar[feed-give;$get[user]];9999999]]]]]]];   0   ]]
$let[feed-gotten;$if[$getVar[feed-gotten;$get[user]]!=;$if[$getVar[feed-gotten;$get[user]]<=9;   $getVar[feed-gotten;$get[user]]   ;$if[$getVar[feed-gotten;$get[user]]<=99;   $getVar[feed-gotten;$get[user]]  ;$if[$getVar[feed-gotten;$get[user]]<=999;  $getVar[feed-gotten;$get[user]]  ;$if[$getVar[feed-gotten;$get[user]]<=9999;  $getVar[feed-gotten;$get[user]] ;$if[$getVar[feed-gotten;$get[user]]<=99999; $getVar[feed-gotten;$get[user]] ;$if[$getVar[feed-gotten;$get[user]]<=999999; $getVar[feed-gotten;$get[user]];$if[$getVar[feed-gotten;$get[user]]<=9999999;$getVar[feed-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[feed-sum;$sum[$replace[$getVar[feed-gotten;$get[user]]; ;;-1];$replace[$getVar[feed-give;$get[user]]; ;;-1]]]
$let[feed;$if[$get[feed-sum]!=;$if[$get[feed-sum]<=9;   $get[feed-sum]   ;$if[$get[feed-sum]<=99;   $get[feed-sum]  ;$if[$get[feed-sum]<=999;  $get[feed-sum]  ;$if[$get[feed-sum]<=9999;  $get[feed-sum] ;$if[$get[feed-sum]<=99999; $get[feed-sum] ;$if[$get[feed-sum]<=999999; $get[feed-sum];$if[$get[feed-sum]<=9999999;$get[feed-sum];9999999]]]]]]];   0   ]]

$let[glomp-give;$if[$getVar[glomp-give;$get[user]]!=;$if[$getVar[glomp-give;$get[user]]<=9;   $getVar[glomp-give;$get[user]]   ;$if[$getVar[glomp-give;$get[user]]<=99;   $getVar[glomp-give;$get[user]]  ;$if[$getVar[glomp-give;$get[user]]<=999;  $getVar[glomp-give;$get[user]]  ;$if[$getVar[glomp-give;$get[user]]<=9999;  $getVar[glomp-give;$get[user]] ;$if[$getVar[glomp-give;$get[user]]<=99999; $getVar[glomp-give;$get[user]] ;$if[$getVar[glomp-give;$get[user]]<=999999; $getVar[glomp-give;$get[user]];$if[$getVar[glomp-give;$get[user]]<=9999999;$getVar[glomp-give;$get[user]];9999999]]]]]]];   0   ]]
$let[glomp-gotten;$if[$getVar[glomp-gotten;$get[user]]!=;$if[$getVar[glomp-gotten;$get[user]]<=9;   $getVar[glomp-gotten;$get[user]]   ;$if[$getVar[glomp-gotten;$get[user]]<=99;   $getVar[glomp-gotten;$get[user]]  ;$if[$getVar[glomp-gotten;$get[user]]<=999;  $getVar[glomp-gotten;$get[user]]  ;$if[$getVar[glomp-gotten;$get[user]]<=9999;  $getVar[glomp-gotten;$get[user]] ;$if[$getVar[glomp-gotten;$get[user]]<=99999; $getVar[glomp-gotten;$get[user]] ;$if[$getVar[glomp-gotten;$get[user]]<=999999; $getVar[glomp-gotten;$get[user]];$if[$getVar[glomp-gotten;$get[user]]<=9999999;$getVar[glomp-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[glomp-sum;$sum[$replace[$getVar[glomp-gotten;$get[user]]; ;;-1];$replace[$getVar[glomp-give;$get[user]]; ;;-1]]]
$let[glomp;$if[$get[glomp-sum]!=;$if[$get[glomp-sum]<=9;   $get[glomp-sum]   ;$if[$get[glomp-sum]<=99;   $get[glomp-sum]  ;$if[$get[glomp-sum]<=999;  $get[glomp-sum]  ;$if[$get[glomp-sum]<=9999;  $get[glomp-sum] ;$if[$get[glomp-sum]<=99999; $get[glomp-sum] ;$if[$get[glomp-sum]<=999999; $get[glomp-sum];$if[$get[glomp-sum]<=9999999;$get[glomp-sum];9999999]]]]]]];   0   ]]

$let[handhold-give;$if[$getVar[handhold-give;$get[user]]!=;$if[$getVar[handhold-give;$get[user]]<=9;   $getVar[handhold-give;$get[user]]   ;$if[$getVar[handhold-give;$get[user]]<=99;   $getVar[handhold-give;$get[user]]  ;$if[$getVar[handhold-give;$get[user]]<=999;  $getVar[handhold-give;$get[user]]  ;$if[$getVar[handhold-give;$get[user]]<=9999;  $getVar[handhold-give;$get[user]] ;$if[$getVar[handhold-give;$get[user]]<=99999; $getVar[handhold-give;$get[user]] ;$if[$getVar[handhold-give;$get[user]]<=999999; $getVar[handhold-give;$get[user]];$if[$getVar[handhold-give;$get[user]]<=9999999;$getVar[handhold-give;$get[user]];9999999]]]]]]];   0   ]]
$let[handhold-gotten;$if[$getVar[handhold-gotten;$get[user]]!=;$if[$getVar[handhold-gotten;$get[user]]<=9;   $getVar[handhold-gotten;$get[user]]   ;$if[$getVar[handhold-gotten;$get[user]]<=99;   $getVar[handhold-gotten;$get[user]]  ;$if[$getVar[handhold-gotten;$get[user]]<=999;  $getVar[handhold-gotten;$get[user]]  ;$if[$getVar[handhold-gotten;$get[user]]<=9999;  $getVar[handhold-gotten;$get[user]] ;$if[$getVar[handhold-gotten;$get[user]]<=99999; $getVar[handhold-gotten;$get[user]] ;$if[$getVar[handhold-gotten;$get[user]]<=999999; $getVar[handhold-gotten;$get[user]];$if[$getVar[handhold-gotten;$get[user]]<=9999999;$getVar[handhold-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[handhold-sum;$sum[$replace[$getVar[handhold-gotten;$get[user]]; ;;-1];$replace[$getVar[handhold-give;$get[user]]; ;;-1]]]
$let[handhold;$if[$get[handhold-sum]!=;$if[$get[handhold-sum]<=9;   $get[handhold-sum]   ;$if[$get[handhold-sum]<=99;   $get[handhold-sum]  ;$if[$get[handhold-sum]<=999;  $get[handhold-sum]  ;$if[$get[handhold-sum]<=9999;  $get[handhold-sum] ;$if[$get[handhold-sum]<=99999; $get[handhold-sum] ;$if[$get[handhold-sum]<=999999; $get[handhold-sum];$if[$get[handhold-sum]<=9999999;$get[handhold-sum];9999999]]]]]]];   0   ]]

$let[highfive-give;$if[$getVar[highfive-give;$get[user]]!=;$if[$getVar[highfive-give;$get[user]]<=9;   $getVar[highfive-give;$get[user]]   ;$if[$getVar[highfive-give;$get[user]]<=99;   $getVar[highfive-give;$get[user]]  ;$if[$getVar[highfive-give;$get[user]]<=999;  $getVar[highfive-give;$get[user]]  ;$if[$getVar[highfive-give;$get[user]]<=9999;  $getVar[highfive-give;$get[user]] ;$if[$getVar[highfive-give;$get[user]]<=99999; $getVar[highfive-give;$get[user]] ;$if[$getVar[highfive-give;$get[user]]<=999999; $getVar[highfive-give;$get[user]];$if[$getVar[highfive-give;$get[user]]<=9999999;$getVar[highfive-give;$get[user]];9999999]]]]]]];   0   ]]
$let[highfive-gotten;$if[$getVar[highfive-gotten;$get[user]]!=;$if[$getVar[highfive-gotten;$get[user]]<=9;   $getVar[highfive-gotten;$get[user]]   ;$if[$getVar[highfive-gotten;$get[user]]<=99;   $getVar[highfive-gotten;$get[user]]  ;$if[$getVar[highfive-gotten;$get[user]]<=999;  $getVar[highfive-gotten;$get[user]]  ;$if[$getVar[highfive-gotten;$get[user]]<=9999;  $getVar[highfive-gotten;$get[user]] ;$if[$getVar[highfive-gotten;$get[user]]<=99999; $getVar[highfive-gotten;$get[user]] ;$if[$getVar[highfive-gotten;$get[user]]<=999999; $getVar[highfive-gotten;$get[user]];$if[$getVar[highfive-gotten;$get[user]]<=9999999;$getVar[highfive-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[highfive-sum;$sum[$replace[$getVar[highfive-gotten;$get[user]]; ;;-1];$replace[$getVar[highfive-give;$get[user]]; ;;-1]]]
$let[highfive;$if[$get[highfive-sum]!=;$if[$get[highfive-sum]<=9;   $get[highfive-sum]   ;$if[$get[highfive-sum]<=99;   $get[highfive-sum]  ;$if[$get[highfive-sum]<=999;  $get[highfive-sum]  ;$if[$get[highfive-sum]<=9999;  $get[highfive-sum] ;$if[$get[highfive-sum]<=99999; $get[highfive-sum] ;$if[$get[highfive-sum]<=999999; $get[highfive-sum];$if[$get[highfive-sum]<=9999999;$get[highfive-sum];9999999]]]]]]];   0   ]]

$let[happy-give;$if[$getVar[happy-give;$get[user]]!=;$if[$getVar[happy-give;$get[user]]<=9;   $getVar[happy-give;$get[user]]   ;$if[$getVar[happy-give;$get[user]]<=99;   $getVar[happy-give;$get[user]]  ;$if[$getVar[happy-give;$get[user]]<=999;  $getVar[happy-give;$get[user]]  ;$if[$getVar[happy-give;$get[user]]<=9999;  $getVar[happy-give;$get[user]] ;$if[$getVar[happy-give;$get[user]]<=99999; $getVar[happy-give;$get[user]] ;$if[$getVar[happy-give;$get[user]]<=999999; $getVar[happy-give;$get[user]];$if[$getVar[happy-give;$get[user]]<=9999999;$getVar[happy-give;$get[user]];9999999]]]]]]];   0   ]]
$let[happy-gotten;$if[$getVar[happy-gotten;$get[user]]!=;$if[$getVar[happy-gotten;$get[user]]<=9;   $getVar[happy-gotten;$get[user]]   ;$if[$getVar[happy-gotten;$get[user]]<=99;   $getVar[happy-gotten;$get[user]]  ;$if[$getVar[happy-gotten;$get[user]]<=999;  $getVar[happy-gotten;$get[user]]  ;$if[$getVar[happy-gotten;$get[user]]<=9999;  $getVar[happy-gotten;$get[user]] ;$if[$getVar[happy-gotten;$get[user]]<=99999; $getVar[happy-gotten;$get[user]] ;$if[$getVar[happy-gotten;$get[user]]<=999999; $getVar[happy-gotten;$get[user]];$if[$getVar[happy-gotten;$get[user]]<=9999999;$getVar[happy-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[happy-sum;$sum[$replace[$getVar[happy-gotten;$get[user]]; ;;-1];$replace[$getVar[happy-give;$get[user]]; ;;-1]]]
$let[happy;$if[$get[happy-sum]!=;$if[$get[happy-sum]<=9;   $get[happy-sum]   ;$if[$get[happy-sum]<=99;   $get[happy-sum]  ;$if[$get[happy-sum]<=999;  $get[happy-sum]  ;$if[$get[happy-sum]<=9999;  $get[happy-sum] ;$if[$get[happy-sum]<=99999; $get[happy-sum] ;$if[$get[happy-sum]<=999999; $get[happy-sum];$if[$get[happy-sum]<=9999999;$get[happy-sum];9999999]]]]]]];   0   ]]

$let[hug-give;$if[$getVar[hug-give;$get[user]]!=;$if[$getVar[hug-give;$get[user]]<=9;   $getVar[hug-give;$get[user]]   ;$if[$getVar[hug-give;$get[user]]<=99;   $getVar[hug-give;$get[user]]  ;$if[$getVar[hug-give;$get[user]]<=999;  $getVar[hug-give;$get[user]]  ;$if[$getVar[hug-give;$get[user]]<=9999;  $getVar[hug-give;$get[user]] ;$if[$getVar[hug-give;$get[user]]<=99999; $getVar[hug-give;$get[user]] ;$if[$getVar[hug-give;$get[user]]<=999999; $getVar[hug-give;$get[user]];$if[$getVar[hug-give;$get[user]]<=9999999;$getVar[hug-give;$get[user]];9999999]]]]]]];   0   ]]
$let[hug-gotten;$if[$getVar[hug-gotten;$get[user]]!=;$if[$getVar[hug-gotten;$get[user]]<=9;   $getVar[hug-gotten;$get[user]]   ;$if[$getVar[hug-gotten;$get[user]]<=99;   $getVar[hug-gotten;$get[user]]  ;$if[$getVar[hug-gotten;$get[user]]<=999;  $getVar[hug-gotten;$get[user]]  ;$if[$getVar[hug-gotten;$get[user]]<=9999;  $getVar[hug-gotten;$get[user]] ;$if[$getVar[hug-gotten;$get[user]]<=99999; $getVar[hug-gotten;$get[user]] ;$if[$getVar[hug-gotten;$get[user]]<=999999; $getVar[hug-gotten;$get[user]];$if[$getVar[hug-gotten;$get[user]]<=9999999;$getVar[hug-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[hug-sum;$sum[$replace[$getVar[hug-gotten;$get[user]]; ;;-1];$replace[$getVar[hug-give;$get[user]]; ;;-1]]]
$let[hug;$if[$get[hug-sum]!=;$if[$get[hug-sum]<=9;   $get[hug-sum]   ;$if[$get[hug-sum]<=99;   $get[hug-sum]  ;$if[$get[hug-sum]<=999;  $get[hug-sum]  ;$if[$get[hug-sum]<=9999;  $get[hug-sum] ;$if[$get[hug-sum]<=99999; $get[hug-sum] ;$if[$get[hug-sum]<=999999; $get[hug-sum];$if[$get[hug-sum]<=9999999;$get[hug-sum];9999999]]]]]]];   0   ]]

$let[kiss-give;$if[$getVar[kiss-give;$get[user]]!=;$if[$getVar[kiss-give;$get[user]]<=9;   $getVar[kiss-give;$get[user]]   ;$if[$getVar[kiss-give;$get[user]]<=99;   $getVar[kiss-give;$get[user]]  ;$if[$getVar[kiss-give;$get[user]]<=999;  $getVar[kiss-give;$get[user]]  ;$if[$getVar[kiss-give;$get[user]]<=9999;  $getVar[kiss-give;$get[user]] ;$if[$getVar[kiss-give;$get[user]]<=99999; $getVar[kiss-give;$get[user]] ;$if[$getVar[kiss-give;$get[user]]<=999999; $getVar[kiss-give;$get[user]];$if[$getVar[kiss-give;$get[user]]<=9999999;$getVar[kiss-give;$get[user]];9999999]]]]]]];   0   ]]
$let[kiss-gotten;$if[$getVar[kiss-gotten;$get[user]]!=;$if[$getVar[kiss-gotten;$get[user]]<=9;   $getVar[kiss-gotten;$get[user]]   ;$if[$getVar[kiss-gotten;$get[user]]<=99;   $getVar[kiss-gotten;$get[user]]  ;$if[$getVar[kiss-gotten;$get[user]]<=999;  $getVar[kiss-gotten;$get[user]]  ;$if[$getVar[kiss-gotten;$get[user]]<=9999;  $getVar[kiss-gotten;$get[user]] ;$if[$getVar[kiss-gotten;$get[user]]<=99999; $getVar[kiss-gotten;$get[user]] ;$if[$getVar[kiss-gotten;$get[user]]<=999999; $getVar[kiss-gotten;$get[user]];$if[$getVar[kiss-gotten;$get[user]]<=9999999;$getVar[kiss-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[kiss-sum;$sum[$replace[$getVar[kiss-gotten;$get[user]]; ;;-1];$replace[$getVar[kiss-give;$get[user]]; ;;-1]]]
$let[kiss;$if[$get[kiss-sum]!=;$if[$get[kiss-sum]<=9;   $get[kiss-sum]   ;$if[$get[kiss-sum]<=99;   $get[kiss-sum]  ;$if[$get[kiss-sum]<=999;  $get[kiss-sum]  ;$if[$get[kiss-sum]<=9999;  $get[kiss-sum] ;$if[$get[kiss-sum]<=99999; $get[kiss-sum] ;$if[$get[kiss-sum]<=999999; $get[kiss-sum];$if[$get[kiss-sum]<=9999999;$get[kiss-sum];9999999]]]]]]];   0   ]]

$let[laugh-give;$if[$getVar[laugh-give;$get[user]]!=;$if[$getVar[laugh-give;$get[user]]<=9;   $getVar[laugh-give;$get[user]]   ;$if[$getVar[laugh-give;$get[user]]<=99;   $getVar[laugh-give;$get[user]]  ;$if[$getVar[laugh-give;$get[user]]<=999;  $getVar[laugh-give;$get[user]]  ;$if[$getVar[laugh-give;$get[user]]<=9999;  $getVar[laugh-give;$get[user]] ;$if[$getVar[laugh-give;$get[user]]<=99999; $getVar[laugh-give;$get[user]] ;$if[$getVar[laugh-give;$get[user]]<=999999; $getVar[laugh-give;$get[user]];$if[$getVar[laugh-give;$get[user]]<=9999999;$getVar[laugh-give;$get[user]];9999999]]]]]]];   0   ]]
$let[laugh-gotten;$if[$getVar[laugh-gotten;$get[user]]!=;$if[$getVar[laugh-gotten;$get[user]]<=9;   $getVar[laugh-gotten;$get[user]]   ;$if[$getVar[laugh-gotten;$get[user]]<=99;   $getVar[laugh-gotten;$get[user]]  ;$if[$getVar[laugh-gotten;$get[user]]<=999;  $getVar[laugh-gotten;$get[user]]  ;$if[$getVar[laugh-gotten;$get[user]]<=9999;  $getVar[laugh-gotten;$get[user]] ;$if[$getVar[laugh-gotten;$get[user]]<=99999; $getVar[laugh-gotten;$get[user]] ;$if[$getVar[laugh-gotten;$get[user]]<=999999; $getVar[laugh-gotten;$get[user]];$if[$getVar[laugh-gotten;$get[user]]<=9999999;$getVar[laugh-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[laugh-sum;$sum[$replace[$getVar[laugh-gotten;$get[user]]; ;;-1];$replace[$getVar[laugh-give;$get[user]]; ;;-1]]]
$let[laugh;$if[$get[laugh-sum]!=;$if[$get[laugh-sum]<=9;   $get[laugh-sum]   ;$if[$get[laugh-sum]<=99;   $get[laugh-sum]  ;$if[$get[laugh-sum]<=999;  $get[laugh-sum]  ;$if[$get[laugh-sum]<=9999;  $get[laugh-sum] ;$if[$get[laugh-sum]<=99999; $get[laugh-sum] ;$if[$get[laugh-sum]<=999999; $get[laugh-sum];$if[$get[laugh-sum]<=9999999;$get[laugh-sum];9999999]]]]]]];   0   ]]

$let[lick-give;$if[$getVar[lick-give;$get[user]]!=;$if[$getVar[lick-give;$get[user]]<=9;   $getVar[lick-give;$get[user]]   ;$if[$getVar[lick-give;$get[user]]<=99;   $getVar[lick-give;$get[user]]  ;$if[$getVar[lick-give;$get[user]]<=999;  $getVar[lick-give;$get[user]]  ;$if[$getVar[lick-give;$get[user]]<=9999;  $getVar[lick-give;$get[user]] ;$if[$getVar[lick-give;$get[user]]<=99999; $getVar[lick-give;$get[user]] ;$if[$getVar[lick-give;$get[user]]<=999999; $getVar[lick-give;$get[user]];$if[$getVar[lick-give;$get[user]]<=9999999;$getVar[lick-give;$get[user]];9999999]]]]]]];   0   ]]
$let[lick-gotten;$if[$getVar[lick-gotten;$get[user]]!=;$if[$getVar[lick-gotten;$get[user]]<=9;   $getVar[lick-gotten;$get[user]]   ;$if[$getVar[lick-gotten;$get[user]]<=99;   $getVar[lick-gotten;$get[user]]  ;$if[$getVar[lick-gotten;$get[user]]<=999;  $getVar[lick-gotten;$get[user]]  ;$if[$getVar[lick-gotten;$get[user]]<=9999;  $getVar[lick-gotten;$get[user]] ;$if[$getVar[lick-gotten;$get[user]]<=99999; $getVar[lick-gotten;$get[user]] ;$if[$getVar[lick-gotten;$get[user]]<=999999; $getVar[lick-gotten;$get[user]];$if[$getVar[lick-gotten;$get[user]]<=9999999;$getVar[lick-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[lick-sum;$sum[$replace[$getVar[lick-gotten;$get[user]]; ;;-1];$replace[$getVar[lick-give;$get[user]]; ;;-1]]]
$let[lick;$if[$get[lick-sum]!=;$if[$get[lick-sum]<=9;   $get[lick-sum]   ;$if[$get[lick-sum]<=99;   $get[lick-sum]  ;$if[$get[lick-sum]<=999;  $get[lick-sum]  ;$if[$get[lick-sum]<=9999;  $get[lick-sum] ;$if[$get[lick-sum]<=99999; $get[lick-sum] ;$if[$get[lick-sum]<=999999; $get[lick-sum];$if[$get[lick-sum]<=9999999;$get[lick-sum];9999999]]]]]]];   0   ]]

$let[love-give;$if[$getVar[love-give;$get[user]]!=;$if[$getVar[love-give;$get[user]]<=9;   $getVar[love-give;$get[user]]   ;$if[$getVar[love-give;$get[user]]<=99;   $getVar[love-give;$get[user]]  ;$if[$getVar[love-give;$get[user]]<=999;  $getVar[love-give;$get[user]]  ;$if[$getVar[love-give;$get[user]]<=9999;  $getVar[love-give;$get[user]] ;$if[$getVar[love-give;$get[user]]<=99999; $getVar[love-give;$get[user]] ;$if[$getVar[love-give;$get[user]]<=999999; $getVar[love-give;$get[user]];$if[$getVar[love-give;$get[user]]<=9999999;$getVar[love-give;$get[user]];9999999]]]]]]];   0   ]]
$let[love-gotten;$if[$getVar[love-gotten;$get[user]]!=;$if[$getVar[love-gotten;$get[user]]<=9;   $getVar[love-gotten;$get[user]]   ;$if[$getVar[love-gotten;$get[user]]<=99;   $getVar[love-gotten;$get[user]]  ;$if[$getVar[love-gotten;$get[user]]<=999;  $getVar[love-gotten;$get[user]]  ;$if[$getVar[love-gotten;$get[user]]<=9999;  $getVar[love-gotten;$get[user]] ;$if[$getVar[love-gotten;$get[user]]<=99999; $getVar[love-gotten;$get[user]] ;$if[$getVar[love-gotten;$get[user]]<=999999; $getVar[love-gotten;$get[user]];$if[$getVar[love-gotten;$get[user]]<=9999999;$getVar[love-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[love-sum;$sum[$replace[$getVar[love-gotten;$get[user]]; ;;-1];$replace[$getVar[love-give;$get[user]]; ;;-1]]]
$let[love;$if[$get[love-sum]!=;$if[$get[love-sum]<=9;   $get[love-sum]   ;$if[$get[love-sum]<=99;   $get[love-sum]  ;$if[$get[love-sum]<=999;  $get[love-sum]  ;$if[$get[love-sum]<=9999;  $get[love-sum] ;$if[$get[love-sum]<=99999; $get[love-sum] ;$if[$get[love-sum]<=999999; $get[love-sum];$if[$get[love-sum]<=9999999;$get[love-sum];9999999]]]]]]];   0   ]]

$let[lurk-give;$if[$getVar[lurk-give;$get[user]]!=;$if[$getVar[lurk-give;$get[user]]<=9;   $getVar[lurk-give;$get[user]]   ;$if[$getVar[lurk-give;$get[user]]<=99;   $getVar[lurk-give;$get[user]]  ;$if[$getVar[lurk-give;$get[user]]<=999;  $getVar[lurk-give;$get[user]]  ;$if[$getVar[lurk-give;$get[user]]<=9999;  $getVar[lurk-give;$get[user]] ;$if[$getVar[lurk-give;$get[user]]<=99999; $getVar[lurk-give;$get[user]] ;$if[$getVar[lurk-give;$get[user]]<=999999; $getVar[lurk-give;$get[user]];$if[$getVar[lurk-give;$get[user]]<=9999999;$getVar[lurk-give;$get[user]];9999999]]]]]]];   0   ]]
$let[lurk-gotten;$if[$getVar[lurk-gotten;$get[user]]!=;$if[$getVar[lurk-gotten;$get[user]]<=9;   $getVar[lurk-gotten;$get[user]]   ;$if[$getVar[lurk-gotten;$get[user]]<=99;   $getVar[lurk-gotten;$get[user]]  ;$if[$getVar[lurk-gotten;$get[user]]<=999;  $getVar[lurk-gotten;$get[user]]  ;$if[$getVar[lurk-gotten;$get[user]]<=9999;  $getVar[lurk-gotten;$get[user]] ;$if[$getVar[lurk-gotten;$get[user]]<=99999; $getVar[lurk-gotten;$get[user]] ;$if[$getVar[lurk-gotten;$get[user]]<=999999; $getVar[lurk-gotten;$get[user]];$if[$getVar[lurk-gotten;$get[user]]<=9999999;$getVar[lurk-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[lurk-sum;$sum[$replace[$getVar[lurk-gotten;$get[user]]; ;;-1];$replace[$getVar[lurk-give;$get[user]]; ;;-1]]]
$let[lurk;$if[$get[lurk-sum]!=;$if[$get[lurk-sum]<=9;   $get[lurk-sum]   ;$if[$get[lurk-sum]<=99;   $get[lurk-sum]  ;$if[$get[lurk-sum]<=999;  $get[lurk-sum]  ;$if[$get[lurk-sum]<=9999;  $get[lurk-sum] ;$if[$get[lurk-sum]<=99999; $get[lurk-sum] ;$if[$get[lurk-sum]<=999999; $get[lurk-sum];$if[$get[lurk-sum]<=9999999;$get[lurk-sum];9999999]]]]]]];   0   ]]

$let[nom-give;$if[$getVar[nom-give;$get[user]]!=;$if[$getVar[nom-give;$get[user]]<=9;   $getVar[nom-give;$get[user]]   ;$if[$getVar[nom-give;$get[user]]<=99;   $getVar[nom-give;$get[user]]  ;$if[$getVar[nom-give;$get[user]]<=999;  $getVar[nom-give;$get[user]]  ;$if[$getVar[nom-give;$get[user]]<=9999;  $getVar[nom-give;$get[user]] ;$if[$getVar[nom-give;$get[user]]<=99999; $getVar[nom-give;$get[user]] ;$if[$getVar[nom-give;$get[user]]<=999999; $getVar[nom-give;$get[user]];$if[$getVar[nom-give;$get[user]]<=9999999;$getVar[nom-give;$get[user]];9999999]]]]]]];   0   ]]
$let[nom-gotten;$if[$getVar[nom-gotten;$get[user]]!=;$if[$getVar[nom-gotten;$get[user]]<=9;   $getVar[nom-gotten;$get[user]]   ;$if[$getVar[nom-gotten;$get[user]]<=99;   $getVar[nom-gotten;$get[user]]  ;$if[$getVar[nom-gotten;$get[user]]<=999;  $getVar[nom-gotten;$get[user]]  ;$if[$getVar[nom-gotten;$get[user]]<=9999;  $getVar[nom-gotten;$get[user]] ;$if[$getVar[nom-gotten;$get[user]]<=99999; $getVar[nom-gotten;$get[user]] ;$if[$getVar[nom-gotten;$get[user]]<=999999; $getVar[nom-gotten;$get[user]];$if[$getVar[nom-gotten;$get[user]]<=9999999;$getVar[nom-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[nom-sum;$sum[$replace[$getVar[nom-gotten;$get[user]]; ;;-1];$replace[$getVar[nom-give;$get[user]]; ;;-1]]]
$let[nom;$if[$get[nom-sum]!=;$if[$get[nom-sum]<=9;   $get[nom-sum]   ;$if[$get[nom-sum]<=99;   $get[nom-sum]  ;$if[$get[nom-sum]<=999;  $get[nom-sum]  ;$if[$get[nom-sum]<=9999;  $get[nom-sum] ;$if[$get[nom-sum]<=99999; $get[nom-sum] ;$if[$get[nom-sum]<=999999; $get[nom-sum];$if[$get[nom-sum]<=9999999;$get[nom-sum];9999999]]]]]]];   0   ]]

$let[nuzzle-give;$if[$getVar[nuzzle-give;$get[user]]!=;$if[$getVar[nuzzle-give;$get[user]]<=9;   $getVar[nuzzle-give;$get[user]]   ;$if[$getVar[nuzzle-give;$get[user]]<=99;   $getVar[nuzzle-give;$get[user]]  ;$if[$getVar[nuzzle-give;$get[user]]<=999;  $getVar[nuzzle-give;$get[user]]  ;$if[$getVar[nuzzle-give;$get[user]]<=9999;  $getVar[nuzzle-give;$get[user]] ;$if[$getVar[nuzzle-give;$get[user]]<=99999; $getVar[nuzzle-give;$get[user]] ;$if[$getVar[nuzzle-give;$get[user]]<=999999; $getVar[nuzzle-give;$get[user]];$if[$getVar[nuzzle-give;$get[user]]<=9999999;$getVar[nuzzle-give;$get[user]];9999999]]]]]]];   0   ]]
$let[nuzzle-gotten;$if[$getVar[nuzzle-gotten;$get[user]]!=;$if[$getVar[nuzzle-gotten;$get[user]]<=9;   $getVar[nuzzle-gotten;$get[user]]   ;$if[$getVar[nuzzle-gotten;$get[user]]<=99;   $getVar[nuzzle-gotten;$get[user]]  ;$if[$getVar[nuzzle-gotten;$get[user]]<=999;  $getVar[nuzzle-gotten;$get[user]]  ;$if[$getVar[nuzzle-gotten;$get[user]]<=9999;  $getVar[nuzzle-gotten;$get[user]] ;$if[$getVar[nuzzle-gotten;$get[user]]<=99999; $getVar[nuzzle-gotten;$get[user]] ;$if[$getVar[nuzzle-gotten;$get[user]]<=999999; $getVar[nuzzle-gotten;$get[user]];$if[$getVar[nuzzle-gotten;$get[user]]<=9999999;$getVar[nuzzle-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[nuzzle-sum;$sum[$replace[$getVar[nuzzle-gotten;$get[user]]; ;;-1];$replace[$getVar[nuzzle-give;$get[user]]; ;;-1]]]
$let[nuzzle;$if[$get[nuzzle-sum]!=;$if[$get[nuzzle-sum]<=9;   $get[nuzzle-sum]   ;$if[$get[nuzzle-sum]<=99;   $get[nuzzle-sum]  ;$if[$get[nuzzle-sum]<=999;  $get[nuzzle-sum]  ;$if[$get[nuzzle-sum]<=9999;  $get[nuzzle-sum] ;$if[$get[nuzzle-sum]<=99999; $get[nuzzle-sum] ;$if[$get[nuzzle-sum]<=999999; $get[nuzzle-sum];$if[$get[nuzzle-sum]<=9999999;$get[nuzzle-sum];9999999]]]]]]];   0   ]]

$let[pat-give;$if[$getVar[pat-give;$get[user]]!=;$if[$getVar[pat-give;$get[user]]<=9;   $getVar[pat-give;$get[user]]   ;$if[$getVar[pat-give;$get[user]]<=99;   $getVar[pat-give;$get[user]]  ;$if[$getVar[pat-give;$get[user]]<=999;  $getVar[pat-give;$get[user]]  ;$if[$getVar[pat-give;$get[user]]<=9999;  $getVar[pat-give;$get[user]] ;$if[$getVar[pat-give;$get[user]]<=99999; $getVar[pat-give;$get[user]] ;$if[$getVar[pat-give;$get[user]]<=999999; $getVar[pat-give;$get[user]];$if[$getVar[pat-give;$get[user]]<=9999999;$getVar[pat-give;$get[user]];9999999]]]]]]];   0   ]]
$let[pat-gotten;$if[$getVar[pat-gotten;$get[user]]!=;$if[$getVar[pat-gotten;$get[user]]<=9;   $getVar[pat-gotten;$get[user]]   ;$if[$getVar[pat-gotten;$get[user]]<=99;   $getVar[pat-gotten;$get[user]]  ;$if[$getVar[pat-gotten;$get[user]]<=999;  $getVar[pat-gotten;$get[user]]  ;$if[$getVar[pat-gotten;$get[user]]<=9999;  $getVar[pat-gotten;$get[user]] ;$if[$getVar[pat-gotten;$get[user]]<=99999; $getVar[pat-gotten;$get[user]] ;$if[$getVar[pat-gotten;$get[user]]<=999999; $getVar[pat-gotten;$get[user]];$if[$getVar[pat-gotten;$get[user]]<=9999999;$getVar[pat-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[pat-sum;$sum[$replace[$getVar[pat-gotten;$get[user]]; ;;-1];$replace[$getVar[pat-give;$get[user]]; ;;-1]]]
$let[pat;$if[$get[pat-sum]!=;$if[$get[pat-sum]<=9;   $get[pat-sum]   ;$if[$get[pat-sum]<=99;   $get[pat-sum]  ;$if[$get[pat-sum]<=999;  $get[pat-sum]  ;$if[$get[pat-sum]<=9999;  $get[pat-sum] ;$if[$get[pat-sum]<=99999; $get[pat-sum] ;$if[$get[pat-sum]<=999999; $get[pat-sum];$if[$get[pat-sum]<=9999999;$get[pat-sum];9999999]]]]]]];   0   ]]

$let[peck-give;$if[$getVar[peck-give;$get[user]]!=;$if[$getVar[peck-give;$get[user]]<=9;   $getVar[peck-give;$get[user]]   ;$if[$getVar[peck-give;$get[user]]<=99;   $getVar[peck-give;$get[user]]  ;$if[$getVar[peck-give;$get[user]]<=999;  $getVar[peck-give;$get[user]]  ;$if[$getVar[peck-give;$get[user]]<=9999;  $getVar[peck-give;$get[user]] ;$if[$getVar[peck-give;$get[user]]<=99999; $getVar[peck-give;$get[user]] ;$if[$getVar[peck-give;$get[user]]<=999999; $getVar[peck-give;$get[user]];$if[$getVar[peck-give;$get[user]]<=9999999;$getVar[peck-give;$get[user]];9999999]]]]]]];   0   ]]
$let[peck-gotten;$if[$getVar[peck-gotten;$get[user]]!=;$if[$getVar[peck-gotten;$get[user]]<=9;   $getVar[peck-gotten;$get[user]]   ;$if[$getVar[peck-gotten;$get[user]]<=99;   $getVar[peck-gotten;$get[user]]  ;$if[$getVar[peck-gotten;$get[user]]<=999;  $getVar[peck-gotten;$get[user]]  ;$if[$getVar[peck-gotten;$get[user]]<=9999;  $getVar[peck-gotten;$get[user]] ;$if[$getVar[peck-gotten;$get[user]]<=99999; $getVar[peck-gotten;$get[user]] ;$if[$getVar[peck-gotten;$get[user]]<=999999; $getVar[peck-gotten;$get[user]];$if[$getVar[peck-gotten;$get[user]]<=9999999;$getVar[peck-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[peck-sum;$sum[$replace[$getVar[peck-gotten;$get[user]]; ;;-1];$replace[$getVar[peck-give;$get[user]]; ;;-1]]]
$let[peck;$if[$get[peck-sum]!=;$if[$get[peck-sum]<=9;   $get[peck-sum]   ;$if[$get[peck-sum]<=99;   $get[peck-sum]  ;$if[$get[peck-sum]<=999;  $get[peck-sum]  ;$if[$get[peck-sum]<=9999;  $get[peck-sum] ;$if[$get[peck-sum]<=99999; $get[peck-sum] ;$if[$get[peck-sum]<=999999; $get[peck-sum];$if[$get[peck-sum]<=9999999;$get[peck-sum];9999999]]]]]]];   0   ]]

$let[poke-give;$if[$getVar[poke-give;$get[user]]!=;$if[$getVar[poke-give;$get[user]]<=9;   $getVar[poke-give;$get[user]]   ;$if[$getVar[poke-give;$get[user]]<=99;   $getVar[poke-give;$get[user]]  ;$if[$getVar[poke-give;$get[user]]<=999;  $getVar[poke-give;$get[user]]  ;$if[$getVar[poke-give;$get[user]]<=9999;  $getVar[poke-give;$get[user]] ;$if[$getVar[poke-give;$get[user]]<=99999; $getVar[poke-give;$get[user]] ;$if[$getVar[poke-give;$get[user]]<=999999; $getVar[poke-give;$get[user]];$if[$getVar[poke-give;$get[user]]<=9999999;$getVar[poke-give;$get[user]];9999999]]]]]]];   0   ]]
$let[poke-gotten;$if[$getVar[poke-gotten;$get[user]]!=;$if[$getVar[poke-gotten;$get[user]]<=9;   $getVar[poke-gotten;$get[user]]   ;$if[$getVar[poke-gotten;$get[user]]<=99;   $getVar[poke-gotten;$get[user]]  ;$if[$getVar[poke-gotten;$get[user]]<=999;  $getVar[poke-gotten;$get[user]]  ;$if[$getVar[poke-gotten;$get[user]]<=9999;  $getVar[poke-gotten;$get[user]] ;$if[$getVar[poke-gotten;$get[user]]<=99999; $getVar[poke-gotten;$get[user]] ;$if[$getVar[poke-gotten;$get[user]]<=999999; $getVar[poke-gotten;$get[user]];$if[$getVar[poke-gotten;$get[user]]<=9999999;$getVar[poke-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[poke-sum;$sum[$replace[$getVar[poke-gotten;$get[user]]; ;;-1];$replace[$getVar[poke-give;$get[user]]; ;;-1]]]
$let[poke;$if[$get[poke-sum]!=;$if[$get[poke-sum]<=9;   $get[poke-sum]   ;$if[$get[poke-sum]<=99;   $get[poke-sum]  ;$if[$get[poke-sum]<=999;  $get[poke-sum]  ;$if[$get[poke-sum]<=9999;  $get[poke-sum] ;$if[$get[poke-sum]<=99999; $get[poke-sum] ;$if[$get[poke-sum]<=999999; $get[poke-sum];$if[$get[poke-sum]<=9999999;$get[poke-sum];9999999]]]]]]];   0   ]]

$let[pout-give;$if[$getVar[pout-give;$get[user]]!=;$if[$getVar[pout-give;$get[user]]<=9;   $getVar[pout-give;$get[user]]   ;$if[$getVar[pout-give;$get[user]]<=99;   $getVar[pout-give;$get[user]]  ;$if[$getVar[pout-give;$get[user]]<=999;  $getVar[pout-give;$get[user]]  ;$if[$getVar[pout-give;$get[user]]<=9999;  $getVar[pout-give;$get[user]] ;$if[$getVar[pout-give;$get[user]]<=99999; $getVar[pout-give;$get[user]] ;$if[$getVar[pout-give;$get[user]]<=999999; $getVar[pout-give;$get[user]];$if[$getVar[pout-give;$get[user]]<=9999999;$getVar[pout-give;$get[user]];9999999]]]]]]];   0   ]]
$let[pout-gotten;$if[$getVar[pout-gotten;$get[user]]!=;$if[$getVar[pout-gotten;$get[user]]<=9;   $getVar[pout-gotten;$get[user]]   ;$if[$getVar[pout-gotten;$get[user]]<=99;   $getVar[pout-gotten;$get[user]]  ;$if[$getVar[pout-gotten;$get[user]]<=999;  $getVar[pout-gotten;$get[user]]  ;$if[$getVar[pout-gotten;$get[user]]<=9999;  $getVar[pout-gotten;$get[user]] ;$if[$getVar[pout-gotten;$get[user]]<=99999; $getVar[pout-gotten;$get[user]] ;$if[$getVar[pout-gotten;$get[user]]<=999999; $getVar[pout-gotten;$get[user]];$if[$getVar[pout-gotten;$get[user]]<=9999999;$getVar[pout-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[pout-sum;$sum[$replace[$getVar[pout-gotten;$get[user]]; ;;-1];$replace[$getVar[pout-give;$get[user]]; ;;-1]]]
$let[pout;$if[$get[pout-sum]!=;$if[$get[pout-sum]<=9;   $get[pout-sum]   ;$if[$get[pout-sum]<=99;   $get[pout-sum]  ;$if[$get[pout-sum]<=999;  $get[pout-sum]  ;$if[$get[pout-sum]<=9999;  $get[pout-sum] ;$if[$get[pout-sum]<=99999; $get[pout-sum] ;$if[$get[pout-sum]<=999999; $get[pout-sum];$if[$get[pout-sum]<=9999999;$get[pout-sum];9999999]]]]]]];   0   ]]

$let[sleep-give;$if[$getVar[sleep-give;$get[user]]!=;$if[$getVar[sleep-give;$get[user]]<=9;   $getVar[sleep-give;$get[user]]   ;$if[$getVar[sleep-give;$get[user]]<=99;   $getVar[sleep-give;$get[user]]  ;$if[$getVar[sleep-give;$get[user]]<=999;  $getVar[sleep-give;$get[user]]  ;$if[$getVar[sleep-give;$get[user]]<=9999;  $getVar[sleep-give;$get[user]] ;$if[$getVar[sleep-give;$get[user]]<=99999; $getVar[sleep-give;$get[user]] ;$if[$getVar[sleep-give;$get[user]]<=999999; $getVar[sleep-give;$get[user]];$if[$getVar[sleep-give;$get[user]]<=9999999;$getVar[sleep-give;$get[user]];9999999]]]]]]];   0   ]]
$let[sleep-gotten;$if[$getVar[sleep-gotten;$get[user]]!=;$if[$getVar[sleep-gotten;$get[user]]<=9;   $getVar[sleep-gotten;$get[user]]   ;$if[$getVar[sleep-gotten;$get[user]]<=99;   $getVar[sleep-gotten;$get[user]]  ;$if[$getVar[sleep-gotten;$get[user]]<=999;  $getVar[sleep-gotten;$get[user]]  ;$if[$getVar[sleep-gotten;$get[user]]<=9999;  $getVar[sleep-gotten;$get[user]] ;$if[$getVar[sleep-gotten;$get[user]]<=99999; $getVar[sleep-gotten;$get[user]] ;$if[$getVar[sleep-gotten;$get[user]]<=999999; $getVar[sleep-gotten;$get[user]];$if[$getVar[sleep-gotten;$get[user]]<=9999999;$getVar[sleep-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[sleep-sum;$sum[$replace[$getVar[sleep-gotten;$get[user]]; ;;-1];$replace[$getVar[sleep-give;$get[user]]; ;;-1]]]
$let[sleep;$if[$get[sleep-sum]!=;$if[$get[sleep-sum]<=9;   $get[sleep-sum]   ;$if[$get[sleep-sum]<=99;   $get[sleep-sum]  ;$if[$get[sleep-sum]<=999;  $get[sleep-sum]  ;$if[$get[sleep-sum]<=9999;  $get[sleep-sum] ;$if[$get[sleep-sum]<=99999; $get[sleep-sum] ;$if[$get[sleep-sum]<=999999; $get[sleep-sum];$if[$get[sleep-sum]<=9999999;$get[sleep-sum];9999999]]]]]]];   0   ]]

$let[thumbsup-give;$if[$getVar[thumbsup-give;$get[user]]!=;$if[$getVar[thumbsup-give;$get[user]]<=9;   $getVar[thumbsup-give;$get[user]]   ;$if[$getVar[thumbsup-give;$get[user]]<=99;   $getVar[thumbsup-give;$get[user]]  ;$if[$getVar[thumbsup-give;$get[user]]<=999;  $getVar[thumbsup-give;$get[user]]  ;$if[$getVar[thumbsup-give;$get[user]]<=9999;  $getVar[thumbsup-give;$get[user]] ;$if[$getVar[thumbsup-give;$get[user]]<=99999; $getVar[thumbsup-give;$get[user]] ;$if[$getVar[thumbsup-give;$get[user]]<=999999; $getVar[thumbsup-give;$get[user]];$if[$getVar[thumbsup-give;$get[user]]<=9999999;$getVar[thumbsup-give;$get[user]];9999999]]]]]]];   0   ]]
$let[thumbsup-gotten;$if[$getVar[thumbsup-gotten;$get[user]]!=;$if[$getVar[thumbsup-gotten;$get[user]]<=9;   $getVar[thumbsup-gotten;$get[user]]   ;$if[$getVar[thumbsup-gotten;$get[user]]<=99;   $getVar[thumbsup-gotten;$get[user]]  ;$if[$getVar[thumbsup-gotten;$get[user]]<=999;  $getVar[thumbsup-gotten;$get[user]]  ;$if[$getVar[thumbsup-gotten;$get[user]]<=9999;  $getVar[thumbsup-gotten;$get[user]] ;$if[$getVar[thumbsup-gotten;$get[user]]<=99999; $getVar[thumbsup-gotten;$get[user]] ;$if[$getVar[thumbsup-gotten;$get[user]]<=999999; $getVar[thumbsup-gotten;$get[user]];$if[$getVar[thumbsup-gotten;$get[user]]<=9999999;$getVar[thumbsup-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[thumbsup-sum;$sum[$replace[$getVar[thumbsup-gotten;$get[user]]; ;;-1];$replace[$getVar[thumbsup-give;$get[user]]; ;;-1]]]
$let[thumbsup;$if[$get[thumbsup-sum]!=;$if[$get[thumbsup-sum]<=9;   $get[thumbsup-sum]   ;$if[$get[thumbsup-sum]<=99;   $get[thumbsup-sum]  ;$if[$get[thumbsup-sum]<=999;  $get[thumbsup-sum]  ;$if[$get[thumbsup-sum]<=9999;  $get[thumbsup-sum] ;$if[$get[thumbsup-sum]<=99999; $get[thumbsup-sum] ;$if[$get[thumbsup-sum]<=999999; $get[thumbsup-sum];$if[$get[thumbsup-sum]<=9999999;$get[thumbsup-sum];9999999]]]]]]];   0   ]]

$let[tickle-give;$if[$getVar[tickle-give;$get[user]]!=;$if[$getVar[tickle-give;$get[user]]<=9;   $getVar[tickle-give;$get[user]]   ;$if[$getVar[tickle-give;$get[user]]<=99;   $getVar[tickle-give;$get[user]]  ;$if[$getVar[tickle-give;$get[user]]<=999;  $getVar[tickle-give;$get[user]]  ;$if[$getVar[tickle-give;$get[user]]<=9999;  $getVar[tickle-give;$get[user]] ;$if[$getVar[tickle-give;$get[user]]<=99999; $getVar[tickle-give;$get[user]] ;$if[$getVar[tickle-give;$get[user]]<=999999; $getVar[tickle-give;$get[user]];$if[$getVar[tickle-give;$get[user]]<=9999999;$getVar[tickle-give;$get[user]];9999999]]]]]]];   0   ]]
$let[tickle-gotten;$if[$getVar[tickle-gotten;$get[user]]!=;$if[$getVar[tickle-gotten;$get[user]]<=9;   $getVar[tickle-gotten;$get[user]]   ;$if[$getVar[tickle-gotten;$get[user]]<=99;   $getVar[tickle-gotten;$get[user]]  ;$if[$getVar[tickle-gotten;$get[user]]<=999;  $getVar[tickle-gotten;$get[user]]  ;$if[$getVar[tickle-gotten;$get[user]]<=9999;  $getVar[tickle-gotten;$get[user]] ;$if[$getVar[tickle-gotten;$get[user]]<=99999; $getVar[tickle-gotten;$get[user]] ;$if[$getVar[tickle-gotten;$get[user]]<=999999; $getVar[tickle-gotten;$get[user]];$if[$getVar[tickle-gotten;$get[user]]<=9999999;$getVar[tickle-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[tickle-sum;$sum[$replace[$getVar[tickle-gotten;$get[user]]; ;;-1];$replace[$getVar[tickle-give;$get[user]]; ;;-1]]]
$let[tickle;$if[$get[tickle-sum]!=;$if[$get[tickle-sum]<=9;   $get[tickle-sum]   ;$if[$get[tickle-sum]<=99;   $get[tickle-sum]  ;$if[$get[tickle-sum]<=999;  $get[tickle-sum]  ;$if[$get[tickle-sum]<=9999;  $get[tickle-sum] ;$if[$get[tickle-sum]<=99999; $get[tickle-sum] ;$if[$get[tickle-sum]<=999999; $get[tickle-sum];$if[$get[tickle-sum]<=9999999;$get[tickle-sum];9999999]]]]]]];   0   ]]

$let[wag-give;$if[$getVar[wag-give;$get[user]]!=;$if[$getVar[wag-give;$get[user]]<=9;   $getVar[wag-give;$get[user]]   ;$if[$getVar[wag-give;$get[user]]<=99;   $getVar[wag-give;$get[user]]  ;$if[$getVar[wag-give;$get[user]]<=999;  $getVar[wag-give;$get[user]]  ;$if[$getVar[wag-give;$get[user]]<=9999;  $getVar[wag-give;$get[user]] ;$if[$getVar[wag-give;$get[user]]<=99999; $getVar[wag-give;$get[user]] ;$if[$getVar[wag-give;$get[user]]<=999999; $getVar[wag-give;$get[user]];$if[$getVar[wag-give;$get[user]]<=9999999;$getVar[wag-give;$get[user]];9999999]]]]]]];   0   ]]
$let[wag-gotten;$if[$getVar[wag-gotten;$get[user]]!=;$if[$getVar[wag-gotten;$get[user]]<=9;   $getVar[wag-gotten;$get[user]]   ;$if[$getVar[wag-gotten;$get[user]]<=99;   $getVar[wag-gotten;$get[user]]  ;$if[$getVar[wag-gotten;$get[user]]<=999;  $getVar[wag-gotten;$get[user]]  ;$if[$getVar[wag-gotten;$get[user]]<=9999;  $getVar[wag-gotten;$get[user]] ;$if[$getVar[wag-gotten;$get[user]]<=99999; $getVar[wag-gotten;$get[user]] ;$if[$getVar[wag-gotten;$get[user]]<=999999; $getVar[wag-gotten;$get[user]];$if[$getVar[wag-gotten;$get[user]]<=9999999;$getVar[wag-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[wag-sum;$sum[$replace[$getVar[wag-gotten;$get[user]]; ;;-1];$replace[$getVar[wag-give;$get[user]]; ;;-1]]]
$let[wag;$if[$get[wag-sum]!=;$if[$get[wag-sum]<=9;   $get[wag-sum]   ;$if[$get[wag-sum]<=99;   $get[wag-sum]  ;$if[$get[wag-sum]<=999;  $get[wag-sum]  ;$if[$get[wag-sum]<=9999;  $get[wag-sum] ;$if[$get[wag-sum]<=99999; $get[wag-sum] ;$if[$get[wag-sum]<=999999; $get[wag-sum];$if[$get[wag-sum]<=9999999;$get[wag-sum];9999999]]]]]]];   0   ]]

$let[wave-give;$if[$getVar[wave-give;$get[user]]!=;$if[$getVar[wave-give;$get[user]]<=9;   $getVar[wave-give;$get[user]]   ;$if[$getVar[wave-give;$get[user]]<=99;   $getVar[wave-give;$get[user]]  ;$if[$getVar[wave-give;$get[user]]<=999;  $getVar[wave-give;$get[user]]  ;$if[$getVar[wave-give;$get[user]]<=9999;  $getVar[wave-give;$get[user]] ;$if[$getVar[wave-give;$get[user]]<=99999; $getVar[wave-give;$get[user]] ;$if[$getVar[wave-give;$get[user]]<=999999; $getVar[wave-give;$get[user]];$if[$getVar[wave-give;$get[user]]<=9999999;$getVar[wave-give;$get[user]];9999999]]]]]]];   0   ]]
$let[wave-gotten;$if[$getVar[wave-gotten;$get[user]]!=;$if[$getVar[wave-gotten;$get[user]]<=9;   $getVar[wave-gotten;$get[user]]   ;$if[$getVar[wave-gotten;$get[user]]<=99;   $getVar[wave-gotten;$get[user]]  ;$if[$getVar[wave-gotten;$get[user]]<=999;  $getVar[wave-gotten;$get[user]]  ;$if[$getVar[wave-gotten;$get[user]]<=9999;  $getVar[wave-gotten;$get[user]] ;$if[$getVar[wave-gotten;$get[user]]<=99999; $getVar[wave-gotten;$get[user]] ;$if[$getVar[wave-gotten;$get[user]]<=999999; $getVar[wave-gotten;$get[user]];$if[$getVar[wave-gotten;$get[user]]<=9999999;$getVar[wave-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[wave-sum;$sum[$replace[$getVar[wave-gotten;$get[user]]; ;;-1];$replace[$getVar[wave-give;$get[user]]; ;;-1]]]
$let[wave;$if[$get[wave-sum]!=;$if[$get[wave-sum]<=9;   $get[wave-sum]   ;$if[$get[wave-sum]<=99;   $get[wave-sum]  ;$if[$get[wave-sum]<=999;  $get[wave-sum]  ;$if[$get[wave-sum]<=9999;  $get[wave-sum] ;$if[$get[wave-sum]<=99999; $get[wave-sum] ;$if[$get[wave-sum]<=999999; $get[wave-sum];$if[$get[wave-sum]<=9999999;$get[wave-sum];9999999]]]]]]];   0   ]]

            $addField[**Wholesome:**;\`\`\`swift
Type     | Gotten  | Given   | Total   
---------+---------+---------+---------
Blush    | $get[blush-gotten] | $get[blush-give] | $get[blush]
Boop     | $get[boop-gotten] | $get[boop-give] | $get[boop]
Cheer    | $get[cheer-gotten] | $get[cheer-give] | $get[cheer]
Cuddle   | $get[cuddle-gotten] | $get[cuddle-give] | $get[cuddle]
Dance    | $get[dance-gotten] | $get[dance-give] | $get[dance]
Feed     | $get[feed-gotten] | $get[feed-give] | $get[feed]
Glomp    | $get[glomp-gotten] | $get[glomp-give] | $get[glomp]
Handhold | $get[handhold-gotten] | $get[handhold-give] | $get[handhold]
Happy    | $get[happy-gotten] | $get[happy-give] | $get[happy]
Highfive | $get[highfive-gotten] | $get[highfive-give] | $get[highfive]
Hug      | $get[hug-gotten] | $get[hug-give] | $get[hug]
Kiss     | $get[kiss-gotten] | $get[kiss-give] | $get[kiss]
Laugh    | $get[laugh-gotten] | $get[laugh-give] | $get[laugh]
Lick     | $get[lick-gotten] | $get[lick-give] | $get[lick]
\`\`\`]
            $addField[;\`\`\`swift
Love     | $get[love-gotten] | $get[love-give] | $get[love]
Lurk     | $get[lurk-gotten] | $get[lurk-give] | $get[lurk]
Nom      | $get[nom-gotten] | $get[nom-give] | $get[nom]
Nuzzle   | $get[nuzzle-gotten] | $get[nuzzle-give] | $get[nuzzle]
Pat      | $get[pat-gotten] | $get[pat-give] | $get[pat]
Peck     | $get[peck-gotten] | $get[peck-give] | $get[peck]
Poke     | $get[poke-gotten] | $get[poke-give] | $get[poke]
Pout     | $get[pout-gotten] | $get[pout-give] | $get[pout]
Sleep    | $get[sleep-gotten] | $get[sleep-give] | $get[sleep]
Thumbsup | $get[thumbsup-gotten] | $get[thumbsup-give] | $get[thumbsup]
Tickle   | $get[tickle-gotten] | $get[tickle-give] | $get[tickle]
Wag      | $get[wag-gotten] | $get[wag-give] | $get[wag]
Wave     | $get[wave-gotten] | $get[wave-give] | $get[wave]
\`\`\`]
            $addActionRow
            $addButton[counter~positive~$authorID~$get[userID];Positive;Primary;;true]
            $addButton[counter~neutral~$authorID~$get[userID];Neutral;Secondary;;false]
            $addButton[counter~negative~$authorID~$get[userID];Negative;Secondary;;false]
          ]
        ]
        $case[neutral;
          $interactionUpdate[
$let[bonk-give;$if[$getVar[bonk-give;$get[user]]!=;$if[$getVar[bonk-give;$get[user]]<=9;   $getVar[bonk-give;$get[user]]   ;$if[$getVar[bonk-give;$get[user]]<=99;   $getVar[bonk-give;$get[user]]  ;$if[$getVar[bonk-give;$get[user]]<=999;  $getVar[bonk-give;$get[user]]  ;$if[$getVar[bonk-give;$get[user]]<=9999;  $getVar[bonk-give;$get[user]] ;$if[$getVar[bonk-give;$get[user]]<=99999; $getVar[bonk-give;$get[user]] ;$if[$getVar[bonk-give;$get[user]]<=999999; $getVar[bonk-give;$get[user]];$if[$getVar[bonk-give;$get[user]]<=9999999;$getVar[bonk-give;$get[user]];9999999]]]]]]];   0   ]]
$let[bonk-gotten;$if[$getVar[bonk-gotten;$get[user]]!=;$if[$getVar[bonk-gotten;$get[user]]<=9;   $getVar[bonk-gotten;$get[user]]   ;$if[$getVar[bonk-gotten;$get[user]]<=99;   $getVar[bonk-gotten;$get[user]]  ;$if[$getVar[bonk-gotten;$get[user]]<=999;  $getVar[bonk-gotten;$get[user]]  ;$if[$getVar[bonk-gotten;$get[user]]<=9999;  $getVar[bonk-gotten;$get[user]] ;$if[$getVar[bonk-gotten;$get[user]]<=99999; $getVar[bonk-gotten;$get[user]] ;$if[$getVar[bonk-gotten;$get[user]]<=999999; $getVar[bonk-gotten;$get[user]];$if[$getVar[bonk-gotten;$get[user]]<=9999999;$getVar[bonk-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[bonk-sum;$sum[$replace[$getVar[bonk-gotten;$get[user]]; ;;-1];$replace[$getVar[bonk-give;$get[user]]; ;;-1]]]
$let[bonk;$if[$get[bonk-sum]!=;$if[$get[bonk-sum]<=9;   $get[bonk-sum]   ;$if[$get[bonk-sum]<=99;   $get[bonk-sum]  ;$if[$get[bonk-sum]<=999;  $get[bonk-sum]  ;$if[$get[bonk-sum]<=9999;  $get[bonk-sum] ;$if[$get[bonk-sum]<=99999; $get[bonk-sum] ;$if[$get[bonk-sum]<=999999; $get[bonk-sum];$if[$get[bonk-sum]<=9999999;$get[bonk-sum];9999999]]]]]]];   0   ]]

$let[bored-give;$if[$getVar[bored-give;$get[user]]!=;$if[$getVar[bored-give;$get[user]]<=9;   $getVar[bored-give;$get[user]]   ;$if[$getVar[bored-give;$get[user]]<=99;   $getVar[bored-give;$get[user]]  ;$if[$getVar[bored-give;$get[user]]<=999;  $getVar[bored-give;$get[user]]  ;$if[$getVar[bored-give;$get[user]]<=9999;  $getVar[bored-give;$get[user]] ;$if[$getVar[bored-give;$get[user]]<=99999; $getVar[bored-give;$get[user]] ;$if[$getVar[bored-give;$get[user]]<=999999; $getVar[bored-give;$get[user]];$if[$getVar[bored-give;$get[user]]<=9999999;$getVar[bored-give;$get[user]];9999999]]]]]]];   0   ]]
$let[bored-gotten;$if[$getVar[bored-gotten;$get[user]]!=;$if[$getVar[bored-gotten;$get[user]]<=9;   $getVar[bored-gotten;$get[user]]   ;$if[$getVar[bored-gotten;$get[user]]<=99;   $getVar[bored-gotten;$get[user]]  ;$if[$getVar[bored-gotten;$get[user]]<=999;  $getVar[bored-gotten;$get[user]]  ;$if[$getVar[bored-gotten;$get[user]]<=9999;  $getVar[bored-gotten;$get[user]] ;$if[$getVar[bored-gotten;$get[user]]<=99999; $getVar[bored-gotten;$get[user]] ;$if[$getVar[bored-gotten;$get[user]]<=999999; $getVar[bored-gotten;$get[user]];$if[$getVar[bored-gotten;$get[user]]<=9999999;$getVar[bored-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[bored-sum;$sum[$replace[$getVar[bored-gotten;$get[user]]; ;;-1];$replace[$getVar[bored-give;$get[user]]; ;;-1]]]
$let[bored;$if[$get[bored-sum]!=;$if[$get[bored-sum]<=9;   $get[bored-sum]   ;$if[$get[bored-sum]<=99;   $get[bored-sum]  ;$if[$get[bored-sum]<=999;  $get[bored-sum]  ;$if[$get[bored-sum]<=9999;  $get[bored-sum] ;$if[$get[bored-sum]<=99999; $get[bored-sum] ;$if[$get[bored-sum]<=999999; $get[bored-sum];$if[$get[bored-sum]<=9999999;$get[bored-sum];9999999]]]]]]];   0   ]]

$let[chase-give;$if[$getVar[chase-give;$get[user]]!=;$if[$getVar[chase-give;$get[user]]<=9;   $getVar[chase-give;$get[user]]   ;$if[$getVar[chase-give;$get[user]]<=99;   $getVar[chase-give;$get[user]]  ;$if[$getVar[chase-give;$get[user]]<=999;  $getVar[chase-give;$get[user]]  ;$if[$getVar[chase-give;$get[user]]<=9999;  $getVar[chase-give;$get[user]] ;$if[$getVar[chase-give;$get[user]]<=99999; $getVar[chase-give;$get[user]] ;$if[$getVar[chase-give;$get[user]]<=999999; $getVar[chase-give;$get[user]];$if[$getVar[chase-give;$get[user]]<=9999999;$getVar[chase-give;$get[user]];9999999]]]]]]];   0   ]]
$let[chase-gotten;$if[$getVar[chase-gotten;$get[user]]!=;$if[$getVar[chase-gotten;$get[user]]<=9;   $getVar[chase-gotten;$get[user]]   ;$if[$getVar[chase-gotten;$get[user]]<=99;   $getVar[chase-gotten;$get[user]]  ;$if[$getVar[chase-gotten;$get[user]]<=999;  $getVar[chase-gotten;$get[user]]  ;$if[$getVar[chase-gotten;$get[user]]<=9999;  $getVar[chase-gotten;$get[user]] ;$if[$getVar[chase-gotten;$get[user]]<=99999; $getVar[chase-gotten;$get[user]] ;$if[$getVar[chase-gotten;$get[user]]<=999999; $getVar[chase-gotten;$get[user]];$if[$getVar[chase-gotten;$get[user]]<=9999999;$getVar[chase-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[chase-sum;$sum[$replace[$getVar[chase-gotten;$get[user]]; ;;-1];$replace[$getVar[chase-give;$get[user]]; ;;-1]]]
$let[chase;$if[$get[chase-sum]!=;$if[$get[chase-sum]<=9;   $get[chase-sum]   ;$if[$get[chase-sum]<=99;   $get[chase-sum]  ;$if[$get[chase-sum]<=999;  $get[chase-sum]  ;$if[$get[chase-sum]<=9999;  $get[chase-sum] ;$if[$get[chase-sum]<=99999; $get[chase-sum] ;$if[$get[chase-sum]<=999999; $get[chase-sum];$if[$get[chase-sum]<=9999999;$get[chase-sum];9999999]]]]]]];   0   ]]

$let[cringe-give;$if[$getVar[cringe-give;$get[user]]!=;$if[$getVar[cringe-give;$get[user]]<=9;   $getVar[cringe-give;$get[user]]   ;$if[$getVar[cringe-give;$get[user]]<=99;   $getVar[cringe-give;$get[user]]  ;$if[$getVar[cringe-give;$get[user]]<=999;  $getVar[cringe-give;$get[user]]  ;$if[$getVar[cringe-give;$get[user]]<=9999;  $getVar[cringe-give;$get[user]] ;$if[$getVar[cringe-give;$get[user]]<=99999; $getVar[cringe-give;$get[user]] ;$if[$getVar[cringe-give;$get[user]]<=999999; $getVar[cringe-give;$get[user]];$if[$getVar[cringe-give;$get[user]]<=9999999;$getVar[cringe-give;$get[user]];9999999]]]]]]];   0   ]]
$let[cringe-gotten;$if[$getVar[cringe-gotten;$get[user]]!=;$if[$getVar[cringe-gotten;$get[user]]<=9;   $getVar[cringe-gotten;$get[user]]   ;$if[$getVar[cringe-gotten;$get[user]]<=99;   $getVar[cringe-gotten;$get[user]]  ;$if[$getVar[cringe-gotten;$get[user]]<=999;  $getVar[cringe-gotten;$get[user]]  ;$if[$getVar[cringe-gotten;$get[user]]<=9999;  $getVar[cringe-gotten;$get[user]] ;$if[$getVar[cringe-gotten;$get[user]]<=99999; $getVar[cringe-gotten;$get[user]] ;$if[$getVar[cringe-gotten;$get[user]]<=999999; $getVar[cringe-gotten;$get[user]];$if[$getVar[cringe-gotten;$get[user]]<=9999999;$getVar[cringe-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[cringe-sum;$sum[$replace[$getVar[cringe-gotten;$get[user]]; ;;-1];$replace[$getVar[cringe-give;$get[user]]; ;;-1]]]
$let[cringe;$if[$get[cringe-sum]!=;$if[$get[cringe-sum]<=9;   $get[cringe-sum]   ;$if[$get[cringe-sum]<=99;   $get[cringe-sum]  ;$if[$get[cringe-sum]<=999;  $get[cringe-sum]  ;$if[$get[cringe-sum]<=9999;  $get[cringe-sum] ;$if[$get[cringe-sum]<=99999; $get[cringe-sum] ;$if[$get[cringe-sum]<=999999; $get[cringe-sum];$if[$get[cringe-sum]<=9999999;$get[cringe-sum];9999999]]]]]]];   0   ]]

$let[facepalm-give;$if[$getVar[facepalm-give;$get[user]]!=;$if[$getVar[facepalm-give;$get[user]]<=9;   $getVar[facepalm-give;$get[user]]   ;$if[$getVar[facepalm-give;$get[user]]<=99;   $getVar[facepalm-give;$get[user]]  ;$if[$getVar[facepalm-give;$get[user]]<=999;  $getVar[facepalm-give;$get[user]]  ;$if[$getVar[facepalm-give;$get[user]]<=9999;  $getVar[facepalm-give;$get[user]] ;$if[$getVar[facepalm-give;$get[user]]<=99999; $getVar[facepalm-give;$get[user]] ;$if[$getVar[facepalm-give;$get[user]]<=999999; $getVar[facepalm-give;$get[user]];$if[$getVar[facepalm-give;$get[user]]<=9999999;$getVar[facepalm-give;$get[user]];9999999]]]]]]];   0   ]]
$let[facepalm-gotten;$if[$getVar[facepalm-gotten;$get[user]]!=;$if[$getVar[facepalm-gotten;$get[user]]<=9;   $getVar[facepalm-gotten;$get[user]]   ;$if[$getVar[facepalm-gotten;$get[user]]<=99;   $getVar[facepalm-gotten;$get[user]]  ;$if[$getVar[facepalm-gotten;$get[user]]<=999;  $getVar[facepalm-gotten;$get[user]]  ;$if[$getVar[facepalm-gotten;$get[user]]<=9999;  $getVar[facepalm-gotten;$get[user]] ;$if[$getVar[facepalm-gotten;$get[user]]<=99999; $getVar[facepalm-gotten;$get[user]] ;$if[$getVar[facepalm-gotten;$get[user]]<=999999; $getVar[facepalm-gotten;$get[user]];$if[$getVar[facepalm-gotten;$get[user]]<=9999999;$getVar[facepalm-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[facepalm-sum;$sum[$replace[$getVar[facepalm-gotten;$get[user]]; ;;-1];$replace[$getVar[facepalm-give;$get[user]]; ;;-1]]]
$let[facepalm;$if[$get[facepalm-sum]!=;$if[$get[facepalm-sum]<=9;   $get[facepalm-sum]   ;$if[$get[facepalm-sum]<=99;   $get[facepalm-sum]  ;$if[$get[facepalm-sum]<=999;  $get[facepalm-sum]  ;$if[$get[facepalm-sum]<=9999;  $get[facepalm-sum] ;$if[$get[facepalm-sum]<=99999; $get[facepalm-sum] ;$if[$get[facepalm-sum]<=999999; $get[facepalm-sum];$if[$get[facepalm-sum]<=9999999;$get[facepalm-sum];9999999]]]]]]];   0   ]]

$let[nervous-give;$if[$getVar[nervous-give;$get[user]]!=;$if[$getVar[nervous-give;$get[user]]<=9;   $getVar[nervous-give;$get[user]]   ;$if[$getVar[nervous-give;$get[user]]<=99;   $getVar[nervous-give;$get[user]]  ;$if[$getVar[nervous-give;$get[user]]<=999;  $getVar[nervous-give;$get[user]]  ;$if[$getVar[nervous-give;$get[user]]<=9999;  $getVar[nervous-give;$get[user]] ;$if[$getVar[nervous-give;$get[user]]<=99999; $getVar[nervous-give;$get[user]] ;$if[$getVar[nervous-give;$get[user]]<=999999; $getVar[nervous-give;$get[user]];$if[$getVar[nervous-give;$get[user]]<=9999999;$getVar[nervous-give;$get[user]];9999999]]]]]]];   0   ]]
$let[nervous-gotten;$if[$getVar[nervous-gotten;$get[user]]!=;$if[$getVar[nervous-gotten;$get[user]]<=9;   $getVar[nervous-gotten;$get[user]]   ;$if[$getVar[nervous-gotten;$get[user]]<=99;   $getVar[nervous-gotten;$get[user]]  ;$if[$getVar[nervous-gotten;$get[user]]<=999;  $getVar[nervous-gotten;$get[user]]  ;$if[$getVar[nervous-gotten;$get[user]]<=9999;  $getVar[nervous-gotten;$get[user]] ;$if[$getVar[nervous-gotten;$get[user]]<=99999; $getVar[nervous-gotten;$get[user]] ;$if[$getVar[nervous-gotten;$get[user]]<=999999; $getVar[nervous-gotten;$get[user]];$if[$getVar[nervous-gotten;$get[user]]<=9999999;$getVar[nervous-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[nervous-sum;$sum[$replace[$getVar[nervous-gotten;$get[user]]; ;;-1];$replace[$getVar[nervous-give;$get[user]]; ;;-1]]]
$let[nervous;$if[$get[nervous-sum]!=;$if[$get[nervous-sum]<=9;   $get[nervous-sum]   ;$if[$get[nervous-sum]<=99;   $get[nervous-sum]  ;$if[$get[nervous-sum]<=999;  $get[nervous-sum]  ;$if[$get[nervous-sum]<=9999;  $get[nervous-sum] ;$if[$get[nervous-sum]<=99999; $get[nervous-sum] ;$if[$get[nervous-sum]<=999999; $get[nervous-sum];$if[$get[nervous-sum]<=9999999;$get[nervous-sum];9999999]]]]]]];   0   ]]

$let[no-give;$if[$getVar[no-give;$get[user]]!=;$if[$getVar[no-give;$get[user]]<=9;   $getVar[no-give;$get[user]]   ;$if[$getVar[no-give;$get[user]]<=99;   $getVar[no-give;$get[user]]  ;$if[$getVar[no-give;$get[user]]<=999;  $getVar[no-give;$get[user]]  ;$if[$getVar[no-give;$get[user]]<=9999;  $getVar[no-give;$get[user]] ;$if[$getVar[no-give;$get[user]]<=99999; $getVar[no-give;$get[user]] ;$if[$getVar[no-give;$get[user]]<=999999; $getVar[no-give;$get[user]];$if[$getVar[no-give;$get[user]]<=9999999;$getVar[no-give;$get[user]];9999999]]]]]]];   0   ]]
$let[no-gotten;$if[$getVar[no-gotten;$get[user]]!=;$if[$getVar[no-gotten;$get[user]]<=9;   $getVar[no-gotten;$get[user]]   ;$if[$getVar[no-gotten;$get[user]]<=99;   $getVar[no-gotten;$get[user]]  ;$if[$getVar[no-gotten;$get[user]]<=999;  $getVar[no-gotten;$get[user]]  ;$if[$getVar[no-gotten;$get[user]]<=9999;  $getVar[no-gotten;$get[user]] ;$if[$getVar[no-gotten;$get[user]]<=99999; $getVar[no-gotten;$get[user]] ;$if[$getVar[no-gotten;$get[user]]<=999999; $getVar[no-gotten;$get[user]];$if[$getVar[no-gotten;$get[user]]<=9999999;$getVar[no-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[no-sum;$sum[$replace[$getVar[no-gotten;$get[user]]; ;;-1];$replace[$getVar[no-give;$get[user]]; ;;-1]]]
$let[no;$if[$get[no-sum]!=;$if[$get[no-sum]<=9;   $get[no-sum]   ;$if[$get[no-sum]<=99;   $get[no-sum]  ;$if[$get[no-sum]<=999;  $get[no-sum]  ;$if[$get[no-sum]<=9999;  $get[no-sum] ;$if[$get[no-sum]<=99999; $get[no-sum] ;$if[$get[no-sum]<=999999; $get[no-sum];$if[$get[no-sum]<=9999999;$get[no-sum];9999999]]]]]]];   0   ]]

$let[panic-give;$if[$getVar[panic-give;$get[user]]!=;$if[$getVar[panic-give;$get[user]]<=9;   $getVar[panic-give;$get[user]]   ;$if[$getVar[panic-give;$get[user]]<=99;   $getVar[panic-give;$get[user]]  ;$if[$getVar[panic-give;$get[user]]<=999;  $getVar[panic-give;$get[user]]  ;$if[$getVar[panic-give;$get[user]]<=9999;  $getVar[panic-give;$get[user]] ;$if[$getVar[panic-give;$get[user]]<=99999; $getVar[panic-give;$get[user]] ;$if[$getVar[panic-give;$get[user]]<=999999; $getVar[panic-give;$get[user]];$if[$getVar[panic-give;$get[user]]<=9999999;$getVar[panic-give;$get[user]];9999999]]]]]]];   0   ]]
$let[panic-gotten;$if[$getVar[panic-gotten;$get[user]]!=;$if[$getVar[panic-gotten;$get[user]]<=9;   $getVar[panic-gotten;$get[user]]   ;$if[$getVar[panic-gotten;$get[user]]<=99;   $getVar[panic-gotten;$get[user]]  ;$if[$getVar[panic-gotten;$get[user]]<=999;  $getVar[panic-gotten;$get[user]]  ;$if[$getVar[panic-gotten;$get[user]]<=9999;  $getVar[panic-gotten;$get[user]] ;$if[$getVar[panic-gotten;$get[user]]<=99999; $getVar[panic-gotten;$get[user]] ;$if[$getVar[panic-gotten;$get[user]]<=999999; $getVar[panic-gotten;$get[user]];$if[$getVar[panic-gotten;$get[user]]<=9999999;$getVar[panic-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[panic-sum;$sum[$replace[$getVar[panic-gotten;$get[user]]; ;;-1];$replace[$getVar[panic-give;$get[user]]; ;;-1]]]
$let[panic;$if[$get[panic-sum]!=;$if[$get[panic-sum]<=9;   $get[panic-sum]   ;$if[$get[panic-sum]<=99;   $get[panic-sum]  ;$if[$get[panic-sum]<=999;  $get[panic-sum]  ;$if[$get[panic-sum]<=9999;  $get[panic-sum] ;$if[$get[panic-sum]<=99999; $get[panic-sum] ;$if[$get[panic-sum]<=999999; $get[panic-sum];$if[$get[panic-sum]<=9999999;$get[panic-sum];9999999]]]]]]];   0   ]]

$let[run-give;$if[$getVar[run-give;$get[user]]!=;$if[$getVar[run-give;$get[user]]<=9;   $getVar[run-give;$get[user]]   ;$if[$getVar[run-give;$get[user]]<=99;   $getVar[run-give;$get[user]]  ;$if[$getVar[run-give;$get[user]]<=999;  $getVar[run-give;$get[user]]  ;$if[$getVar[run-give;$get[user]]<=9999;  $getVar[run-give;$get[user]] ;$if[$getVar[run-give;$get[user]]<=99999; $getVar[run-give;$get[user]] ;$if[$getVar[run-give;$get[user]]<=999999; $getVar[run-give;$get[user]];$if[$getVar[run-give;$get[user]]<=9999999;$getVar[run-give;$get[user]];9999999]]]]]]];   0   ]]
$let[run-gotten;$if[$getVar[run-gotten;$get[user]]!=;$if[$getVar[run-gotten;$get[user]]<=9;   $getVar[run-gotten;$get[user]]   ;$if[$getVar[run-gotten;$get[user]]<=99;   $getVar[run-gotten;$get[user]]  ;$if[$getVar[run-gotten;$get[user]]<=999;  $getVar[run-gotten;$get[user]]  ;$if[$getVar[run-gotten;$get[user]]<=9999;  $getVar[run-gotten;$get[user]] ;$if[$getVar[run-gotten;$get[user]]<=99999; $getVar[run-gotten;$get[user]] ;$if[$getVar[run-gotten;$get[user]]<=999999; $getVar[run-gotten;$get[user]];$if[$getVar[run-gotten;$get[user]]<=9999999;$getVar[run-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[run-sum;$sum[$replace[$getVar[run-gotten;$get[user]]; ;;-1];$replace[$getVar[run-give;$get[user]]; ;;-1]]]
$let[run;$if[$get[run-sum]!=;$if[$get[run-sum]<=9;   $get[run-sum]   ;$if[$get[run-sum]<=99;   $get[run-sum]  ;$if[$get[run-sum]<=999;  $get[run-sum]  ;$if[$get[run-sum]<=9999;  $get[run-sum] ;$if[$get[run-sum]<=99999; $get[run-sum] ;$if[$get[run-sum]<=999999; $get[run-sum];$if[$get[run-sum]<=9999999;$get[run-sum];9999999]]]]]]];   0   ]]

$let[sip-give;$if[$getVar[sip-give;$get[user]]!=;$if[$getVar[sip-give;$get[user]]<=9;   $getVar[sip-give;$get[user]]   ;$if[$getVar[sip-give;$get[user]]<=99;   $getVar[sip-give;$get[user]]  ;$if[$getVar[sip-give;$get[user]]<=999;  $getVar[sip-give;$get[user]]  ;$if[$getVar[sip-give;$get[user]]<=9999;  $getVar[sip-give;$get[user]] ;$if[$getVar[sip-give;$get[user]]<=99999; $getVar[sip-give;$get[user]] ;$if[$getVar[sip-give;$get[user]]<=999999; $getVar[sip-give;$get[user]];$if[$getVar[sip-give;$get[user]]<=9999999;$getVar[sip-give;$get[user]];9999999]]]]]]];   0   ]]
$let[sip-gotten;$if[$getVar[sip-gotten;$get[user]]!=;$if[$getVar[sip-gotten;$get[user]]<=9;   $getVar[sip-gotten;$get[user]]   ;$if[$getVar[sip-gotten;$get[user]]<=99;   $getVar[sip-gotten;$get[user]]  ;$if[$getVar[sip-gotten;$get[user]]<=999;  $getVar[sip-gotten;$get[user]]  ;$if[$getVar[sip-gotten;$get[user]]<=9999;  $getVar[sip-gotten;$get[user]] ;$if[$getVar[sip-gotten;$get[user]]<=99999; $getVar[sip-gotten;$get[user]] ;$if[$getVar[sip-gotten;$get[user]]<=999999; $getVar[sip-gotten;$get[user]];$if[$getVar[sip-gotten;$get[user]]<=9999999;$getVar[sip-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[sip-sum;$sum[$replace[$getVar[sip-gotten;$get[user]]; ;;-1];$replace[$getVar[sip-give;$get[user]]; ;;-1]]]
$let[sip;$if[$get[sip-sum]!=;$if[$get[sip-sum]<=9;   $get[sip-sum]   ;$if[$get[sip-sum]<=99;   $get[sip-sum]  ;$if[$get[sip-sum]<=999;  $get[sip-sum]  ;$if[$get[sip-sum]<=9999;  $get[sip-sum] ;$if[$get[sip-sum]<=99999; $get[sip-sum] ;$if[$get[sip-sum]<=999999; $get[sip-sum];$if[$get[sip-sum]<=9999999;$get[sip-sum];9999999]]]]]]];   0   ]]

$let[smug-give;$if[$getVar[smug-give;$get[user]]!=;$if[$getVar[smug-give;$get[user]]<=9;   $getVar[smug-give;$get[user]]   ;$if[$getVar[smug-give;$get[user]]<=99;   $getVar[smug-give;$get[user]]  ;$if[$getVar[smug-give;$get[user]]<=999;  $getVar[smug-give;$get[user]]  ;$if[$getVar[smug-give;$get[user]]<=9999;  $getVar[smug-give;$get[user]] ;$if[$getVar[smug-give;$get[user]]<=99999; $getVar[smug-give;$get[user]] ;$if[$getVar[smug-give;$get[user]]<=999999; $getVar[smug-give;$get[user]];$if[$getVar[smug-give;$get[user]]<=9999999;$getVar[smug-give;$get[user]];9999999]]]]]]];   0   ]]
$let[smug-gotten;$if[$getVar[smug-gotten;$get[user]]!=;$if[$getVar[smug-gotten;$get[user]]<=9;   $getVar[smug-gotten;$get[user]]   ;$if[$getVar[smug-gotten;$get[user]]<=99;   $getVar[smug-gotten;$get[user]]  ;$if[$getVar[smug-gotten;$get[user]]<=999;  $getVar[smug-gotten;$get[user]]  ;$if[$getVar[smug-gotten;$get[user]]<=9999;  $getVar[smug-gotten;$get[user]] ;$if[$getVar[smug-gotten;$get[user]]<=99999; $getVar[smug-gotten;$get[user]] ;$if[$getVar[smug-gotten;$get[user]]<=999999; $getVar[smug-gotten;$get[user]];$if[$getVar[smug-gotten;$get[user]]<=9999999;$getVar[smug-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[smug-sum;$sum[$replace[$getVar[smug-gotten;$get[user]]; ;;-1];$replace[$getVar[smug-give;$get[user]]; ;;-1]]]
$let[smug;$if[$get[smug-sum]!=;$if[$get[smug-sum]<=9;   $get[smug-sum]   ;$if[$get[smug-sum]<=99;   $get[smug-sum]  ;$if[$get[smug-sum]<=999;  $get[smug-sum]  ;$if[$get[smug-sum]<=9999;  $get[smug-sum] ;$if[$get[smug-sum]<=99999; $get[smug-sum] ;$if[$get[smug-sum]<=999999; $get[smug-sum];$if[$get[smug-sum]<=9999999;$get[smug-sum];9999999]]]]]]];   0   ]]

$let[stare-give;$if[$getVar[stare-give;$get[user]]!=;$if[$getVar[stare-give;$get[user]]<=9;   $getVar[stare-give;$get[user]]   ;$if[$getVar[stare-give;$get[user]]<=99;   $getVar[stare-give;$get[user]]  ;$if[$getVar[stare-give;$get[user]]<=999;  $getVar[stare-give;$get[user]]  ;$if[$getVar[stare-give;$get[user]]<=9999;  $getVar[stare-give;$get[user]] ;$if[$getVar[stare-give;$get[user]]<=99999; $getVar[stare-give;$get[user]] ;$if[$getVar[stare-give;$get[user]]<=999999; $getVar[stare-give;$get[user]];$if[$getVar[stare-give;$get[user]]<=9999999;$getVar[stare-give;$get[user]];9999999]]]]]]];   0   ]]
$let[stare-gotten;$if[$getVar[stare-gotten;$get[user]]!=;$if[$getVar[stare-gotten;$get[user]]<=9;   $getVar[stare-gotten;$get[user]]   ;$if[$getVar[stare-gotten;$get[user]]<=99;   $getVar[stare-gotten;$get[user]]  ;$if[$getVar[stare-gotten;$get[user]]<=999;  $getVar[stare-gotten;$get[user]]  ;$if[$getVar[stare-gotten;$get[user]]<=9999;  $getVar[stare-gotten;$get[user]] ;$if[$getVar[stare-gotten;$get[user]]<=99999; $getVar[stare-gotten;$get[user]] ;$if[$getVar[stare-gotten;$get[user]]<=999999; $getVar[stare-gotten;$get[user]];$if[$getVar[stare-gotten;$get[user]]<=9999999;$getVar[stare-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[stare-sum;$sum[$replace[$getVar[stare-gotten;$get[user]]; ;;-1];$replace[$getVar[stare-give;$get[user]]; ;;-1]]]
$let[stare;$if[$get[stare-sum]!=;$if[$get[stare-sum]<=9;   $get[stare-sum]   ;$if[$get[stare-sum]<=99;   $get[stare-sum]  ;$if[$get[stare-sum]<=999;  $get[stare-sum]  ;$if[$get[stare-sum]<=9999;  $get[stare-sum] ;$if[$get[stare-sum]<=99999; $get[stare-sum] ;$if[$get[stare-sum]<=999999; $get[stare-sum];$if[$get[stare-sum]<=9999999;$get[stare-sum];9999999]]]]]]];   0   ]]

$let[tease-give;$if[$getVar[tease-give;$get[user]]!=;$if[$getVar[tease-give;$get[user]]<=9;   $getVar[tease-give;$get[user]]   ;$if[$getVar[tease-give;$get[user]]<=99;   $getVar[tease-give;$get[user]]  ;$if[$getVar[tease-give;$get[user]]<=999;  $getVar[tease-give;$get[user]]  ;$if[$getVar[tease-give;$get[user]]<=9999;  $getVar[tease-give;$get[user]] ;$if[$getVar[tease-give;$get[user]]<=99999; $getVar[tease-give;$get[user]] ;$if[$getVar[tease-give;$get[user]]<=999999; $getVar[tease-give;$get[user]];$if[$getVar[tease-give;$get[user]]<=9999999;$getVar[tease-give;$get[user]];9999999]]]]]]];   0   ]]
$let[tease-gotten;$if[$getVar[tease-gotten;$get[user]]!=;$if[$getVar[tease-gotten;$get[user]]<=9;   $getVar[tease-gotten;$get[user]]   ;$if[$getVar[tease-gotten;$get[user]]<=99;   $getVar[tease-gotten;$get[user]]  ;$if[$getVar[tease-gotten;$get[user]]<=999;  $getVar[tease-gotten;$get[user]]  ;$if[$getVar[tease-gotten;$get[user]]<=9999;  $getVar[tease-gotten;$get[user]] ;$if[$getVar[tease-gotten;$get[user]]<=99999; $getVar[tease-gotten;$get[user]] ;$if[$getVar[tease-gotten;$get[user]]<=999999; $getVar[tease-gotten;$get[user]];$if[$getVar[tease-gotten;$get[user]]<=9999999;$getVar[tease-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[tease-sum;$sum[$replace[$getVar[tease-gotten;$get[user]]; ;;-1];$replace[$getVar[tease-give;$get[user]]; ;;-1]]]
$let[tease;$if[$get[tease-sum]!=;$if[$get[tease-sum]<=9;   $get[tease-sum]   ;$if[$get[tease-sum]<=99;   $get[tease-sum]  ;$if[$get[tease-sum]<=999;  $get[tease-sum]  ;$if[$get[tease-sum]<=9999;  $get[tease-sum] ;$if[$get[tease-sum]<=99999; $get[tease-sum] ;$if[$get[tease-sum]<=999999; $get[tease-sum];$if[$get[tease-sum]<=9999999;$get[tease-sum];9999999]]]]]]];   0   ]]

$let[think-give;$if[$getVar[think-give;$get[user]]!=;$if[$getVar[think-give;$get[user]]<=9;   $getVar[think-give;$get[user]]   ;$if[$getVar[think-give;$get[user]]<=99;   $getVar[think-give;$get[user]]  ;$if[$getVar[think-give;$get[user]]<=999;  $getVar[think-give;$get[user]]  ;$if[$getVar[think-give;$get[user]]<=9999;  $getVar[think-give;$get[user]] ;$if[$getVar[think-give;$get[user]]<=99999; $getVar[think-give;$get[user]] ;$if[$getVar[think-give;$get[user]]<=999999; $getVar[think-give;$get[user]];$if[$getVar[think-give;$get[user]]<=9999999;$getVar[think-give;$get[user]];9999999]]]]]]];   0   ]]
$let[think-gotten;$if[$getVar[think-gotten;$get[user]]!=;$if[$getVar[think-gotten;$get[user]]<=9;   $getVar[think-gotten;$get[user]]   ;$if[$getVar[think-gotten;$get[user]]<=99;   $getVar[think-gotten;$get[user]]  ;$if[$getVar[think-gotten;$get[user]]<=999;  $getVar[think-gotten;$get[user]]  ;$if[$getVar[think-gotten;$get[user]]<=9999;  $getVar[think-gotten;$get[user]] ;$if[$getVar[think-gotten;$get[user]]<=99999; $getVar[think-gotten;$get[user]] ;$if[$getVar[think-gotten;$get[user]]<=999999; $getVar[think-gotten;$get[user]];$if[$getVar[think-gotten;$get[user]]<=9999999;$getVar[think-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[think-sum;$sum[$replace[$getVar[think-gotten;$get[user]]; ;;-1];$replace[$getVar[think-give;$get[user]]; ;;-1]]]
$let[think;$if[$get[think-sum]!=;$if[$get[think-sum]<=9;   $get[think-sum]   ;$if[$get[think-sum]<=99;   $get[think-sum]  ;$if[$get[think-sum]<=999;  $get[think-sum]  ;$if[$get[think-sum]<=9999;  $get[think-sum] ;$if[$get[think-sum]<=99999; $get[think-sum] ;$if[$get[think-sum]<=999999; $get[think-sum];$if[$get[think-sum]<=9999999;$get[think-sum];9999999]]]]]]];   0   ]]

$let[rage-give;$if[$getVar[rage-give;$get[user]]!=;$if[$getVar[rage-give;$get[user]]<=9;   $getVar[rage-give;$get[user]]   ;$if[$getVar[rage-give;$get[user]]<=99;   $getVar[rage-give;$get[user]]  ;$if[$getVar[rage-give;$get[user]]<=999;  $getVar[rage-give;$get[user]]  ;$if[$getVar[rage-give;$get[user]]<=9999;  $getVar[rage-give;$get[user]] ;$if[$getVar[rage-give;$get[user]]<=99999; $getVar[rage-give;$get[user]] ;$if[$getVar[rage-give;$get[user]]<=999999; $getVar[rage-give;$get[user]];$if[$getVar[rage-give;$get[user]]<=9999999;$getVar[rage-give;$get[user]];9999999]]]]]]];   0   ]]
$let[rage-gotten;$if[$getVar[rage-gotten;$get[user]]!=;$if[$getVar[rage-gotten;$get[user]]<=9;   $getVar[rage-gotten;$get[user]]   ;$if[$getVar[rage-gotten;$get[user]]<=99;   $getVar[rage-gotten;$get[user]]  ;$if[$getVar[rage-gotten;$get[user]]<=999;  $getVar[rage-gotten;$get[user]]  ;$if[$getVar[rage-gotten;$get[user]]<=9999;  $getVar[rage-gotten;$get[user]] ;$if[$getVar[rage-gotten;$get[user]]<=99999; $getVar[rage-gotten;$get[user]] ;$if[$getVar[rage-gotten;$get[user]]<=999999; $getVar[rage-gotten;$get[user]];$if[$getVar[rage-gotten;$get[user]]<=9999999;$getVar[rage-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[rage-sum;$sum[$replace[$getVar[rage-gotten;$get[user]]; ;;-1];$replace[$getVar[rage-give;$get[user]]; ;;-1]]]
$let[rage;$if[$get[rage-sum]!=;$if[$get[rage-sum]<=9;   $get[rage-sum]   ;$if[$get[rage-sum]<=99;   $get[rage-sum]  ;$if[$get[rage-sum]<=999;  $get[rage-sum]  ;$if[$get[rage-sum]<=9999;  $get[rage-sum] ;$if[$get[rage-sum]<=99999; $get[rage-sum] ;$if[$get[rage-sum]<=999999; $get[rage-sum];$if[$get[rage-sum]<=9999999;$get[rage-sum];9999999]]]]]]];   0   ]]

$let[wink-give;$if[$getVar[wink-give;$get[user]]!=;$if[$getVar[wink-give;$get[user]]<=9;   $getVar[wink-give;$get[user]]   ;$if[$getVar[wink-give;$get[user]]<=99;   $getVar[wink-give;$get[user]]  ;$if[$getVar[wink-give;$get[user]]<=999;  $getVar[wink-give;$get[user]]  ;$if[$getVar[wink-give;$get[user]]<=9999;  $getVar[wink-give;$get[user]] ;$if[$getVar[wink-give;$get[user]]<=99999; $getVar[wink-give;$get[user]] ;$if[$getVar[wink-give;$get[user]]<=999999; $getVar[wink-give;$get[user]];$if[$getVar[wink-give;$get[user]]<=9999999;$getVar[wink-give;$get[user]];9999999]]]]]]];   0   ]]
$let[wink-gotten;$if[$getVar[wink-gotten;$get[user]]!=;$if[$getVar[wink-gotten;$get[user]]<=9;   $getVar[wink-gotten;$get[user]]   ;$if[$getVar[wink-gotten;$get[user]]<=99;   $getVar[wink-gotten;$get[user]]  ;$if[$getVar[wink-gotten;$get[user]]<=999;  $getVar[wink-gotten;$get[user]]  ;$if[$getVar[wink-gotten;$get[user]]<=9999;  $getVar[wink-gotten;$get[user]] ;$if[$getVar[wink-gotten;$get[user]]<=99999; $getVar[wink-gotten;$get[user]] ;$if[$getVar[wink-gotten;$get[user]]<=999999; $getVar[wink-gotten;$get[user]];$if[$getVar[wink-gotten;$get[user]]<=9999999;$getVar[wink-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[wink-sum;$sum[$replace[$getVar[wink-gotten;$get[user]]; ;;-1];$replace[$getVar[wink-give;$get[user]]; ;;-1]]]
$let[wink;$if[$get[wink-sum]!=;$if[$get[wink-sum]<=9;   $get[wink-sum]   ;$if[$get[wink-sum]<=99;   $get[wink-sum]  ;$if[$get[wink-sum]<=999;  $get[wink-sum]  ;$if[$get[wink-sum]<=9999;  $get[wink-sum] ;$if[$get[wink-sum]<=99999; $get[wink-sum] ;$if[$get[wink-sum]<=999999; $get[wink-sum];$if[$get[wink-sum]<=9999999;$get[wink-sum];9999999]]]]]]];   0   ]]

$let[yes-give;$if[$getVar[yes-give;$get[user]]!=;$if[$getVar[yes-give;$get[user]]<=9;   $getVar[yes-give;$get[user]]   ;$if[$getVar[yes-give;$get[user]]<=99;   $getVar[yes-give;$get[user]]  ;$if[$getVar[yes-give;$get[user]]<=999;  $getVar[yes-give;$get[user]]  ;$if[$getVar[yes-give;$get[user]]<=9999;  $getVar[yes-give;$get[user]] ;$if[$getVar[yes-give;$get[user]]<=99999; $getVar[yes-give;$get[user]] ;$if[$getVar[yes-give;$get[user]]<=999999; $getVar[yes-give;$get[user]];$if[$getVar[yes-give;$get[user]]<=9999999;$getVar[yes-give;$get[user]];9999999]]]]]]];   0   ]]
$let[yes-gotten;$if[$getVar[yes-gotten;$get[user]]!=;$if[$getVar[yes-gotten;$get[user]]<=9;   $getVar[yes-gotten;$get[user]]   ;$if[$getVar[yes-gotten;$get[user]]<=99;   $getVar[yes-gotten;$get[user]]  ;$if[$getVar[yes-gotten;$get[user]]<=999;  $getVar[yes-gotten;$get[user]]  ;$if[$getVar[yes-gotten;$get[user]]<=9999;  $getVar[yes-gotten;$get[user]] ;$if[$getVar[yes-gotten;$get[user]]<=99999; $getVar[yes-gotten;$get[user]] ;$if[$getVar[yes-gotten;$get[user]]<=999999; $getVar[yes-gotten;$get[user]];$if[$getVar[yes-gotten;$get[user]]<=9999999;$getVar[yes-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[yes-sum;$sum[$replace[$getVar[yes-gotten;$get[user]]; ;;-1];$replace[$getVar[yes-give;$get[user]]; ;;-1]]]
$let[yes;$if[$get[yes-sum]!=;$if[$get[yes-sum]<=9;   $get[yes-sum]   ;$if[$get[yes-sum]<=99;   $get[yes-sum]  ;$if[$get[yes-sum]<=999;  $get[yes-sum]  ;$if[$get[yes-sum]<=9999;  $get[yes-sum] ;$if[$get[yes-sum]<=99999; $get[yes-sum] ;$if[$get[yes-sum]<=999999; $get[yes-sum];$if[$get[yes-sum]<=9999999;$get[yes-sum];9999999]]]]]]];   0   ]]

            $color[$getUserVar[color;$get[user]]]
            $author[$username[$get[userID]]'s roleplay counter;$userAvatar[$get[userID]]]
            $addField[**Neutral:**;\`\`\`swift
Type     | Gotten  | Given   | Total   
---------+---------+---------+---------
Bonk     | $get[bonk-gotten] | $get[bonk-give] | $get[bonk]
Bored    | $get[bored-gotten] | $get[bored-give] | $get[bored]
Chase    | $get[chase-gotten] | $get[chase-give] | $get[chase]
Cringe   | $get[cringe-gotten] | $get[cringe-give] | $get[cringe]
Facepalm | $get[facepalm-gotten] | $get[facepalm-give] | $get[facepalm]
Nervous  | $get[nervous-gotten] | $get[nervous-give] | $get[nervous]
No       | $get[no-gotten] | $get[no-give] | $get[no]
Panic    | $get[panic-gotten] | $get[panic-give] | $get[panic]
Run      | $get[run-gotten] | $get[run-give] | $get[run]
Sip      | $get[sip-gotten] | $get[sip-give] | $get[sip]
Smug     | $get[smug-gotten] | $get[smug-give] | $get[smug]
Stare    | $get[stare-gotten] | $get[stare-give] | $get[stare]
Tease    | $get[tease-gotten] | $get[tease-give] | $get[tease]
Think    | $get[think-gotten] | $get[think-give] | $get[think]
Rage     | $get[rage-gotten] | $get[rage-give] | $get[rage]
Wink     | $get[wink-gotten] | $get[wink-give] | $get[wink]
Yes      | $get[yes-gotten] | $get[yes-give] | $get[yes]
\`\`\`]
            $addActionRow
            $addButton[counter~positive~$authorID~$get[userID];Positive;Secondary;;false]
            $addButton[counter~neutral~$authorID~$get[userID];Neutral;Primary;;true]
            $addButton[counter~negative~$authorID~$get[userID];Negative;Secondary;;false]
          ]
        ]
        $case[negative;
          $interactionUpdate[
$let[bite-give;$if[$getVar[bite-give;$get[user]]!=;$if[$getVar[bite-give;$get[user]]<=9;   $getVar[bite-give;$get[user]]   ;$if[$getVar[bite-give;$get[user]]<=99;   $getVar[bite-give;$get[user]]  ;$if[$getVar[bite-give;$get[user]]<=999;  $getVar[bite-give;$get[user]]  ;$if[$getVar[bite-give;$get[user]]<=9999;  $getVar[bite-give;$get[user]] ;$if[$getVar[bite-give;$get[user]]<=99999; $getVar[bite-give;$get[user]] ;$if[$getVar[bite-give;$get[user]]<=999999; $getVar[bite-give;$get[user]];$if[$getVar[bite-give;$get[user]]<=9999999;$getVar[bite-give;$get[user]];9999999]]]]]]];   0   ]]
$let[bite-gotten;$if[$getVar[bite-gotten;$get[user]]!=;$if[$getVar[bite-gotten;$get[user]]<=9;   $getVar[bite-gotten;$get[user]]   ;$if[$getVar[bite-gotten;$get[user]]<=99;   $getVar[bite-gotten;$get[user]]  ;$if[$getVar[bite-gotten;$get[user]]<=999;  $getVar[bite-gotten;$get[user]]  ;$if[$getVar[bite-gotten;$get[user]]<=9999;  $getVar[bite-gotten;$get[user]] ;$if[$getVar[bite-gotten;$get[user]]<=99999; $getVar[bite-gotten;$get[user]] ;$if[$getVar[bite-gotten;$get[user]]<=999999; $getVar[bite-gotten;$get[user]];$if[$getVar[bite-gotten;$get[user]]<=9999999;$getVar[bite-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[bite-sum;$sum[$replace[$getVar[bite-gotten;$get[user]]; ;;-1];$replace[$getVar[bite-give;$get[user]]; ;;-1]]]
$let[bite;$if[$get[bite-sum]!=;$if[$get[bite-sum]<=9;   $get[bite-sum]   ;$if[$get[bite-sum]<=99;   $get[bite-sum]  ;$if[$get[bite-sum]<=999;  $get[bite-sum]  ;$if[$get[bite-sum]<=9999;  $get[bite-sum] ;$if[$get[bite-sum]<=99999; $get[bite-sum] ;$if[$get[bite-sum]<=999999; $get[bite-sum];$if[$get[bite-sum]<=9999999;$get[bite-sum];9999999]]]]]]];   0   ]]

$let[cry-give;$if[$getVar[cry-give;$get[user]]!=;$if[$getVar[cry-give;$get[user]]<=9;   $getVar[cry-give;$get[user]]   ;$if[$getVar[cry-give;$get[user]]<=99;   $getVar[cry-give;$get[user]]  ;$if[$getVar[cry-give;$get[user]]<=999;  $getVar[cry-give;$get[user]]  ;$if[$getVar[cry-give;$get[user]]<=9999;  $getVar[cry-give;$get[user]] ;$if[$getVar[cry-give;$get[user]]<=99999; $getVar[cry-give;$get[user]] ;$if[$getVar[cry-give;$get[user]]<=999999; $getVar[cry-give;$get[user]];$if[$getVar[cry-give;$get[user]]<=9999999;$getVar[cry-give;$get[user]];9999999]]]]]]];   0   ]]
$let[cry-gotten;$if[$getVar[cry-gotten;$get[user]]!=;$if[$getVar[cry-gotten;$get[user]]<=9;   $getVar[cry-gotten;$get[user]]   ;$if[$getVar[cry-gotten;$get[user]]<=99;   $getVar[cry-gotten;$get[user]]  ;$if[$getVar[cry-gotten;$get[user]]<=999;  $getVar[cry-gotten;$get[user]]  ;$if[$getVar[cry-gotten;$get[user]]<=9999;  $getVar[cry-gotten;$get[user]] ;$if[$getVar[cry-gotten;$get[user]]<=99999; $getVar[cry-gotten;$get[user]] ;$if[$getVar[cry-gotten;$get[user]]<=999999; $getVar[cry-gotten;$get[user]];$if[$getVar[cry-gotten;$get[user]]<=9999999;$getVar[cry-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[cry-sum;$sum[$replace[$getVar[cry-gotten;$get[user]]; ;;-1];$replace[$getVar[cry-give;$get[user]]; ;;-1]]]
$let[cry;$if[$get[cry-sum]!=;$if[$get[cry-sum]<=9;   $get[cry-sum]   ;$if[$get[cry-sum]<=99;   $get[cry-sum]  ;$if[$get[cry-sum]<=999;  $get[cry-sum]  ;$if[$get[cry-sum]<=9999;  $get[cry-sum] ;$if[$get[cry-sum]<=99999; $get[cry-sum] ;$if[$get[cry-sum]<=999999; $get[cry-sum];$if[$get[cry-sum]<=9999999;$get[cry-sum];9999999]]]]]]];   0   ]]

$let[die-give;$if[$getVar[die-give;$get[user]]!=;$if[$getVar[die-give;$get[user]]<=9;   $getVar[die-give;$get[user]]   ;$if[$getVar[die-give;$get[user]]<=99;   $getVar[die-give;$get[user]]  ;$if[$getVar[die-give;$get[user]]<=999;  $getVar[die-give;$get[user]]  ;$if[$getVar[die-give;$get[user]]<=9999;  $getVar[die-give;$get[user]] ;$if[$getVar[die-give;$get[user]]<=99999; $getVar[die-give;$get[user]] ;$if[$getVar[die-give;$get[user]]<=999999; $getVar[die-give;$get[user]];$if[$getVar[die-give;$get[user]]<=9999999;$getVar[die-give;$get[user]];9999999]]]]]]];   0   ]]
$let[die-gotten;$if[$getVar[die-gotten;$get[user]]!=;$if[$getVar[die-gotten;$get[user]]<=9;   $getVar[die-gotten;$get[user]]   ;$if[$getVar[die-gotten;$get[user]]<=99;   $getVar[die-gotten;$get[user]]  ;$if[$getVar[die-gotten;$get[user]]<=999;  $getVar[die-gotten;$get[user]]  ;$if[$getVar[die-gotten;$get[user]]<=9999;  $getVar[die-gotten;$get[user]] ;$if[$getVar[die-gotten;$get[user]]<=99999; $getVar[die-gotten;$get[user]] ;$if[$getVar[die-gotten;$get[user]]<=999999; $getVar[die-gotten;$get[user]];$if[$getVar[die-gotten;$get[user]]<=9999999;$getVar[die-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[die-sum;$sum[$replace[$getVar[die-gotten;$get[user]]; ;;-1];$replace[$getVar[die-give;$get[user]]; ;;-1]]]
$let[die;$if[$get[die-sum]!=;$if[$get[die-sum]<=9;   $get[die-sum]   ;$if[$get[die-sum]<=99;   $get[die-sum]  ;$if[$get[die-sum]<=999;  $get[die-sum]  ;$if[$get[die-sum]<=9999;  $get[die-sum] ;$if[$get[die-sum]<=99999; $get[die-sum] ;$if[$get[die-sum]<=999999; $get[die-sum];$if[$get[die-sum]<=9999999;$get[die-sum];9999999]]]]]]];   0   ]]

$let[hate-give;$if[$getVar[hate-give;$get[user]]!=;$if[$getVar[hate-give;$get[user]]<=9;   $getVar[hate-give;$get[user]]   ;$if[$getVar[hate-give;$get[user]]<=99;   $getVar[hate-give;$get[user]]  ;$if[$getVar[hate-give;$get[user]]<=999;  $getVar[hate-give;$get[user]]  ;$if[$getVar[hate-give;$get[user]]<=9999;  $getVar[hate-give;$get[user]] ;$if[$getVar[hate-give;$get[user]]<=99999; $getVar[hate-give;$get[user]] ;$if[$getVar[hate-give;$get[user]]<=999999; $getVar[hate-give;$get[user]];$if[$getVar[hate-give;$get[user]]<=9999999;$getVar[hate-give;$get[user]];9999999]]]]]]];   0   ]]
$let[hate-gotten;$if[$getVar[hate-gotten;$get[user]]!=;$if[$getVar[hate-gotten;$get[user]]<=9;   $getVar[hate-gotten;$get[user]]   ;$if[$getVar[hate-gotten;$get[user]]<=99;   $getVar[hate-gotten;$get[user]]  ;$if[$getVar[hate-gotten;$get[user]]<=999;  $getVar[hate-gotten;$get[user]]  ;$if[$getVar[hate-gotten;$get[user]]<=9999;  $getVar[hate-gotten;$get[user]] ;$if[$getVar[hate-gotten;$get[user]]<=99999; $getVar[hate-gotten;$get[user]] ;$if[$getVar[hate-gotten;$get[user]]<=999999; $getVar[hate-gotten;$get[user]];$if[$getVar[hate-gotten;$get[user]]<=9999999;$getVar[hate-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[hate-sum;$sum[$replace[$getVar[hate-gotten;$get[user]]; ;;-1];$replace[$getVar[hate-give;$get[user]]; ;;-1]]]
$let[hate;$if[$get[hate-sum]!=;$if[$get[hate-sum]<=9;   $get[hate-sum]   ;$if[$get[hate-sum]<=99;   $get[hate-sum]  ;$if[$get[hate-sum]<=999;  $get[hate-sum]  ;$if[$get[hate-sum]<=9999;  $get[hate-sum] ;$if[$get[hate-sum]<=99999; $get[hate-sum] ;$if[$get[hate-sum]<=999999; $get[hate-sum];$if[$get[hate-sum]<=9999999;$get[hate-sum];9999999]]]]]]];   0   ]]

$let[sad-give;$if[$getVar[sad-give;$get[user]]!=;$if[$getVar[sad-give;$get[user]]<=9;   $getVar[sad-give;$get[user]]   ;$if[$getVar[sad-give;$get[user]]<=99;   $getVar[sad-give;$get[user]]  ;$if[$getVar[sad-give;$get[user]]<=999;  $getVar[sad-give;$get[user]]  ;$if[$getVar[sad-give;$get[user]]<=9999;  $getVar[sad-give;$get[user]] ;$if[$getVar[sad-give;$get[user]]<=99999; $getVar[sad-give;$get[user]] ;$if[$getVar[sad-give;$get[user]]<=999999; $getVar[sad-give;$get[user]];$if[$getVar[sad-give;$get[user]]<=9999999;$getVar[sad-give;$get[user]];9999999]]]]]]];   0   ]]
$let[sad-gotten;$if[$getVar[sad-gotten;$get[user]]!=;$if[$getVar[sad-gotten;$get[user]]<=9;   $getVar[sad-gotten;$get[user]]   ;$if[$getVar[sad-gotten;$get[user]]<=99;   $getVar[sad-gotten;$get[user]]  ;$if[$getVar[sad-gotten;$get[user]]<=999;  $getVar[sad-gotten;$get[user]]  ;$if[$getVar[sad-gotten;$get[user]]<=9999;  $getVar[sad-gotten;$get[user]] ;$if[$getVar[sad-gotten;$get[user]]<=99999; $getVar[sad-gotten;$get[user]] ;$if[$getVar[sad-gotten;$get[user]]<=999999; $getVar[sad-gotten;$get[user]];$if[$getVar[sad-gotten;$get[user]]<=9999999;$getVar[sad-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[sad-sum;$sum[$replace[$getVar[sad-gotten;$get[user]]; ;;-1];$replace[$getVar[sad-give;$get[user]]; ;;-1]]]
$let[sad;$if[$get[sad-sum]!=;$if[$get[sad-sum]<=9;   $get[sad-sum]   ;$if[$get[sad-sum]<=99;   $get[sad-sum]  ;$if[$get[sad-sum]<=999;  $get[sad-sum]  ;$if[$get[sad-sum]<=9999;  $get[sad-sum] ;$if[$get[sad-sum]<=99999; $get[sad-sum] ;$if[$get[sad-sum]<=999999; $get[sad-sum];$if[$get[sad-sum]<=9999999;$get[sad-sum];9999999]]]]]]];   0   ]]

$let[kill-give;$if[$getVar[kill-give;$get[user]]!=;$if[$getVar[kill-give;$get[user]]<=9;   $getVar[kill-give;$get[user]]   ;$if[$getVar[kill-give;$get[user]]<=99;   $getVar[kill-give;$get[user]]  ;$if[$getVar[kill-give;$get[user]]<=999;  $getVar[kill-give;$get[user]]  ;$if[$getVar[kill-give;$get[user]]<=9999;  $getVar[kill-give;$get[user]] ;$if[$getVar[kill-give;$get[user]]<=99999; $getVar[kill-give;$get[user]] ;$if[$getVar[kill-give;$get[user]]<=999999; $getVar[kill-give;$get[user]];$if[$getVar[kill-give;$get[user]]<=9999999;$getVar[kill-give;$get[user]];9999999]]]]]]];   0   ]]
$let[kill-gotten;$if[$getVar[kill-gotten;$get[user]]!=;$if[$getVar[kill-gotten;$get[user]]<=9;   $getVar[kill-gotten;$get[user]]   ;$if[$getVar[kill-gotten;$get[user]]<=99;   $getVar[kill-gotten;$get[user]]  ;$if[$getVar[kill-gotten;$get[user]]<=999;  $getVar[kill-gotten;$get[user]]  ;$if[$getVar[kill-gotten;$get[user]]<=9999;  $getVar[kill-gotten;$get[user]] ;$if[$getVar[kill-gotten;$get[user]]<=99999; $getVar[kill-gotten;$get[user]] ;$if[$getVar[kill-gotten;$get[user]]<=999999; $getVar[kill-gotten;$get[user]];$if[$getVar[kill-gotten;$get[user]]<=9999999;$getVar[kill-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[kill-sum;$sum[$replace[$getVar[kill-gotten;$get[user]]; ;;-1];$replace[$getVar[kill-give;$get[user]]; ;;-1]]]
$let[kill;$if[$get[kill-sum]!=;$if[$get[kill-sum]<=9;   $get[kill-sum]   ;$if[$get[kill-sum]<=99;   $get[kill-sum]  ;$if[$get[kill-sum]<=999;  $get[kill-sum]  ;$if[$get[kill-sum]<=9999;  $get[kill-sum] ;$if[$get[kill-sum]<=99999; $get[kill-sum] ;$if[$get[kill-sum]<=999999; $get[kill-sum];$if[$get[kill-sum]<=9999999;$get[kill-sum];9999999]]]]]]];   0   ]]

$let[shoot-give;$if[$getVar[shoot-give;$get[user]]!=;$if[$getVar[shoot-give;$get[user]]<=9;   $getVar[shoot-give;$get[user]]   ;$if[$getVar[shoot-give;$get[user]]<=99;   $getVar[shoot-give;$get[user]]  ;$if[$getVar[shoot-give;$get[user]]<=999;  $getVar[shoot-give;$get[user]]  ;$if[$getVar[shoot-give;$get[user]]<=9999;  $getVar[shoot-give;$get[user]] ;$if[$getVar[shoot-give;$get[user]]<=99999; $getVar[shoot-give;$get[user]] ;$if[$getVar[shoot-give;$get[user]]<=999999; $getVar[shoot-give;$get[user]];$if[$getVar[shoot-give;$get[user]]<=9999999;$getVar[shoot-give;$get[user]];9999999]]]]]]];   0   ]]
$let[shoot-gotten;$if[$getVar[shoot-gotten;$get[user]]!=;$if[$getVar[shoot-gotten;$get[user]]<=9;   $getVar[shoot-gotten;$get[user]]   ;$if[$getVar[shoot-gotten;$get[user]]<=99;   $getVar[shoot-gotten;$get[user]]  ;$if[$getVar[shoot-gotten;$get[user]]<=999;  $getVar[shoot-gotten;$get[user]]  ;$if[$getVar[shoot-gotten;$get[user]]<=9999;  $getVar[shoot-gotten;$get[user]] ;$if[$getVar[shoot-gotten;$get[user]]<=99999; $getVar[shoot-gotten;$get[user]] ;$if[$getVar[shoot-gotten;$get[user]]<=999999; $getVar[shoot-gotten;$get[user]];$if[$getVar[shoot-gotten;$get[user]]<=9999999;$getVar[shoot-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[shoot-sum;$sum[$replace[$getVar[shoot-gotten;$get[user]]; ;;-1];$replace[$getVar[shoot-give;$get[user]]; ;;-1]]]
$let[shoot;$if[$get[shoot-sum]!=;$if[$get[shoot-sum]<=9;   $get[shoot-sum]   ;$if[$get[shoot-sum]<=99;   $get[shoot-sum]  ;$if[$get[shoot-sum]<=999;  $get[shoot-sum]  ;$if[$get[shoot-sum]<=9999;  $get[shoot-sum] ;$if[$get[shoot-sum]<=99999; $get[shoot-sum] ;$if[$get[shoot-sum]<=999999; $get[shoot-sum];$if[$get[shoot-sum]<=9999999;$get[shoot-sum];9999999]]]]]]];   0   ]]

$let[slap-give;$if[$getVar[slap-give;$get[user]]!=;$if[$getVar[slap-give;$get[user]]<=9;   $getVar[slap-give;$get[user]]   ;$if[$getVar[slap-give;$get[user]]<=99;   $getVar[slap-give;$get[user]]  ;$if[$getVar[slap-give;$get[user]]<=999;  $getVar[slap-give;$get[user]]  ;$if[$getVar[slap-give;$get[user]]<=9999;  $getVar[slap-give;$get[user]] ;$if[$getVar[slap-give;$get[user]]<=99999; $getVar[slap-give;$get[user]] ;$if[$getVar[slap-give;$get[user]]<=999999; $getVar[slap-give;$get[user]];$if[$getVar[slap-give;$get[user]]<=9999999;$getVar[slap-give;$get[user]];9999999]]]]]]];   0   ]]
$let[slap-gotten;$if[$getVar[slap-gotten;$get[user]]!=;$if[$getVar[slap-gotten;$get[user]]<=9;   $getVar[slap-gotten;$get[user]]   ;$if[$getVar[slap-gotten;$get[user]]<=99;   $getVar[slap-gotten;$get[user]]  ;$if[$getVar[slap-gotten;$get[user]]<=999;  $getVar[slap-gotten;$get[user]]  ;$if[$getVar[slap-gotten;$get[user]]<=9999;  $getVar[slap-gotten;$get[user]] ;$if[$getVar[slap-gotten;$get[user]]<=99999; $getVar[slap-gotten;$get[user]] ;$if[$getVar[slap-gotten;$get[user]]<=999999; $getVar[slap-gotten;$get[user]];$if[$getVar[slap-gotten;$get[user]]<=9999999;$getVar[slap-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[slap-sum;$sum[$replace[$getVar[slap-gotten;$get[user]]; ;;-1];$replace[$getVar[slap-give;$get[user]]; ;;-1]]]
$let[slap;$if[$get[slap-sum]!=;$if[$get[slap-sum]<=9;   $get[slap-sum]   ;$if[$get[slap-sum]<=99;   $get[slap-sum]  ;$if[$get[slap-sum]<=999;  $get[slap-sum]  ;$if[$get[slap-sum]<=9999;  $get[slap-sum] ;$if[$get[slap-sum]<=99999; $get[slap-sum] ;$if[$get[slap-sum]<=999999; $get[slap-sum];$if[$get[slap-sum]<=9999999;$get[slap-sum];9999999]]]]]]];   0   ]]

$let[stab-give;$if[$getVar[stab-give;$get[user]]!=;$if[$getVar[stab-give;$get[user]]<=9;   $getVar[stab-give;$get[user]]   ;$if[$getVar[stab-give;$get[user]]<=99;   $getVar[stab-give;$get[user]]  ;$if[$getVar[stab-give;$get[user]]<=999;  $getVar[stab-give;$get[user]]  ;$if[$getVar[stab-give;$get[user]]<=9999;  $getVar[stab-give;$get[user]] ;$if[$getVar[stab-give;$get[user]]<=99999; $getVar[stab-give;$get[user]] ;$if[$getVar[stab-give;$get[user]]<=999999; $getVar[stab-give;$get[user]];$if[$getVar[stab-give;$get[user]]<=9999999;$getVar[stab-give;$get[user]];9999999]]]]]]];   0   ]]
$let[stab-gotten;$if[$getVar[stab-gotten;$get[user]]!=;$if[$getVar[stab-gotten;$get[user]]<=9;   $getVar[stab-gotten;$get[user]]   ;$if[$getVar[stab-gotten;$get[user]]<=99;   $getVar[stab-gotten;$get[user]]  ;$if[$getVar[stab-gotten;$get[user]]<=999;  $getVar[stab-gotten;$get[user]]  ;$if[$getVar[stab-gotten;$get[user]]<=9999;  $getVar[stab-gotten;$get[user]] ;$if[$getVar[stab-gotten;$get[user]]<=99999; $getVar[stab-gotten;$get[user]] ;$if[$getVar[stab-gotten;$get[user]]<=999999; $getVar[stab-gotten;$get[user]];$if[$getVar[stab-gotten;$get[user]]<=9999999;$getVar[stab-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[stab-sum;$sum[$replace[$getVar[stab-gotten;$get[user]]; ;;-1];$replace[$getVar[stab-give;$get[user]]; ;;-1]]]
$let[stab;$if[$get[stab-sum]!=;$if[$get[stab-sum]<=9;   $get[stab-sum]   ;$if[$get[stab-sum]<=99;   $get[stab-sum]  ;$if[$get[stab-sum]<=999;  $get[stab-sum]  ;$if[$get[stab-sum]<=9999;  $get[stab-sum] ;$if[$get[stab-sum]<=99999; $get[stab-sum] ;$if[$get[stab-sum]<=999999; $get[stab-sum];$if[$get[stab-sum]<=9999999;$get[stab-sum];9999999]]]]]]];   0   ]]

$let[triggered-give;$if[$getVar[triggered-give;$get[user]]!=;$if[$getVar[triggered-give;$get[user]]<=9;   $getVar[triggered-give;$get[user]]   ;$if[$getVar[triggered-give;$get[user]]<=99;   $getVar[triggered-give;$get[user]]  ;$if[$getVar[triggered-give;$get[user]]<=999;  $getVar[triggered-give;$get[user]]  ;$if[$getVar[triggered-give;$get[user]]<=9999;  $getVar[triggered-give;$get[user]] ;$if[$getVar[triggered-give;$get[user]]<=99999; $getVar[triggered-give;$get[user]] ;$if[$getVar[triggered-give;$get[user]]<=999999; $getVar[triggered-give;$get[user]];$if[$getVar[triggered-give;$get[user]]<=9999999;$getVar[triggered-give;$get[user]];9999999]]]]]]];   0   ]]
$let[triggered-gotten;$if[$getVar[triggered-gotten;$get[user]]!=;$if[$getVar[triggered-gotten;$get[user]]<=9;   $getVar[triggered-gotten;$get[user]]   ;$if[$getVar[triggered-gotten;$get[user]]<=99;   $getVar[triggered-gotten;$get[user]]  ;$if[$getVar[triggered-gotten;$get[user]]<=999;  $getVar[triggered-gotten;$get[user]]  ;$if[$getVar[triggered-gotten;$get[user]]<=9999;  $getVar[triggered-gotten;$get[user]] ;$if[$getVar[triggered-gotten;$get[user]]<=99999; $getVar[triggered-gotten;$get[user]] ;$if[$getVar[triggered-gotten;$get[user]]<=999999; $getVar[triggered-gotten;$get[user]];$if[$getVar[triggered-gotten;$get[user]]<=9999999;$getVar[triggered-gotten;$get[user]];9999999]]]]]]];   0   ]]
$let[triggered-sum;$sum[$replace[$getVar[triggered-gotten;$get[user]]; ;;-1];$replace[$getVar[triggered-give;$get[user]]; ;;-1]]]
$let[triggered;$if[$get[triggered-sum]!=;$if[$get[triggered-sum]<=9;   $get[triggered-sum]   ;$if[$get[triggered-sum]<=99;   $get[triggered-sum]  ;$if[$get[triggered-sum]<=999;  $get[triggered-sum]  ;$if[$get[triggered-sum]<=9999;  $get[triggered-sum] ;$if[$get[triggered-sum]<=99999; $get[triggered-sum] ;$if[$get[triggered-sum]<=999999; $get[triggered-sum];$if[$get[triggered-sum]<=9999999;$get[triggered-sum];9999999]]]]]]];   0   ]]

            $color[$getUserVar[color;$get[user]]]
            $author[$username[$get[userID]]'s roleplay counter;$userAvatar[$get[userID]]]
            $addField[**Negative:**;\`\`\`swift
Type     | Gotten  | Given   | Total   
---------+---------+---------+---------
Bite     | $get[bite-gotten] | $get[bite-give] | $get[bite]
Cry      | $get[cry-gotten] | $get[cry-give] | $get[cry]
Die      | $get[die-gotten] | $get[die-give] | $get[die]
Hate     | $get[hate-gotten] | $get[hate-give] | $get[hate]
Sad      | $get[sad-gotten] | $get[sad-give] | $get[sad]
Kill     | $get[kill-gotten] | $get[kill-give] | $get[kill]
Shoot    | $get[shoot-gotten] | $get[shoot-give] | $get[shoot]
Slap     | $get[slap-gotten] | $get[slap-give] | $get[slap]
Stab     | $get[stab-gotten] | $get[stab-give] | $get[stab]
Triggered| $get[triggered-gotten] | $get[triggered-give] | $get[triggered]
\`\`\`]
            $addActionRow
            $addButton[counter~positive~$authorID~$get[userID];Positive;Secondary;;false]
            $addButton[counter~neutral~$authorID~$get[userID];Neutral;Secondary;;false]
            $addButton[counter~negative~$authorID~$get[userID];Negative;Primary;;true]
          ]
        ]
        $case[default;
          $interactionUpdate[
            $customError[405;counter]
          ]
        ]
      ]
    `
  }
]

export default commands;