import { Command } from '@/types';

const commands: Command[] = [
  {
    name: 'counter',
    aliases: ['rp-counter'],
    description: 'Get the roleplay counter of a user.',
    type: 'messageCreate',
    module: 'roleplay',
    version: '1.0.0',
    sourcecode: 'src/commands/roleplay/counter.ts',
    documentation: 'counter',
    usage: 'counter {user}',
    example: 'counter',
    code: `
      $let[author;$getUserVar[uuid;$customEncrypt[encrypt;$authorID]]]
      $let[lang;$if[$getUserVar[language;$get[author]]!=;$getUserVar[language;$get[author]];$if[$guildID!=;$guildPreferredLocale;en-us]]]
      $let[userID;$findUser[$message[0];true]]
      $let[user;$getUserVar[uuid;$customEncrypt[encrypt;$get[userID]]]]

      $checkAgreedToTos
      $checkBotChannel

      $let[blush-give;$if[$getVar[blush-give;$get[user]]!=;$if[$getVar[blush-give;$get[user]]<=9;   $getVar[blush-give;$get[user]]   ;$if[$getVar[blush-give;$get[user]]<=99;   $getVar[blush-give;$get[user]]  ;$if[$getVar[blush-give;$get[user]]<=999;  $getVar[blush-give;$get[user]]  ;$if[$getVar[blush-give;$get[user]]<=9999;  $getVar[blush-give;$get[user]] ;$if[$getVar[blush-give;$get[user]]<=99999; $getVar[blush-give;$get[user]] ;$if[$getVar[blush-give;$get[user]]<=999999; $getVar[blush-give;$get[user]];$if[$getVar[blush-give;$get[user]]<=9999999;$getVar[blush-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[blush-gotten;$if[$getVar[blush-gotten;$get[user]]!=;$if[$getVar[blush-gotten;$get[user]]<=9;   $getVar[blush-gotten;$get[user]]   ;$if[$getVar[blush-gotten;$get[user]]<=99;   $getVar[blush-gotten;$get[user]]  ;$if[$getVar[blush-gotten;$get[user]]<=999;  $getVar[blush-gotten;$get[user]]  ;$if[$getVar[blush-gotten;$get[user]]<=9999;  $getVar[blush-gotten;$get[user]] ;$if[$getVar[blush-gotten;$get[user]]<=99999; $getVar[blush-gotten;$get[user]] ;$if[$getVar[blush-gotten;$get[user]]<=999999; $getVar[blush-gotten;$get[user]];$if[$getVar[blush-gotten;$get[user]]<=9999999;$getVar[blush-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[blush-sum;$sum[$replace[$getVar[blush-gotten;$get[user]]; ;;-1];$replace[$getVar[blush-give;$get[user]]; ;;-1]]]
      $let[blush;$if[$get[blush-sum]!=;$if[$get[blush-sum]<=9;   $get[blush-sum]   ;$if[$get[blush-sum]<=99;   $get[blush-sum]  ;$if[$get[blush-sum]<=999;  $get[blush-sum]  ;$if[$get[blush-sum]<=9999;  $get[blush-sum] ;$if[$get[blush-sum]<=99999; $get[blush-sum] ;$if[$get[blush-sum]<=999999; $get[blush-sum];$if[$get[blush-sum]<=9999999;$get[blush-sum];9999999]]]]]]];   0   ]]

      $let[boop-give;$if[$getVar[boop-give;$get[user]]!=;$if[$getVar[boop-give;$get[user]]<=9;   $getVar[boop-give;$get[user]]   ;$if[$getVar[boop-give;$get[user]]<=99;   $getVar[boop-give;$get[user]]  ;$if[$getVar[boop-give;$get[user]]<=999;  $getVar[boop-give;$get[user]]  ;$if[$getVar[boop-give;$get[user]]<=9999;  $getVar[boop-give;$get[user]] ;$if[$getVar[boop-give;$get[user]]<=99999; $getVar[boop-give;$get[user]] ;$if[$getVar[boop-give;$get[user]]<=999999; $getVar[boop-give;$get[user]];$if[$getVar[boop-give;$get[user]]<=9999999;$getVar[boop-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[boop-gotten;$if[$getVar[boop-gotten;$get[user]]!=;$if[$getVar[boop-gotten;$get[user]]<=9;   $getVar[boop-gotten;$get[user]]   ;$if[$getVar[boop-gotten;$get[user]]<=99;   $getVar[boop-gotten;$get[user]]  ;$if[$getVar[boop-gotten;$get[user]]<=999;  $getVar[boop-gotten;$get[user]]  ;$if[$getVar[boop-gotten;$get[user]]<=9999;  $getVar[boop-gotten;$get[user]] ;$if[$getVar[boop-gotten;$get[user]]<=99999; $getVar[boop-gotten;$get[user]] ;$if[$getVar[boop-gotten;$get[user]]<=999999; $getVar[boop-gotten;$get[user]];$if[$getVar[boop-gotten;$get[user]]<=9999999;$getVar[boop-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[boop-sum;$sum[$replace[$getVar[boop-gotten;$get[user]]; ;;-1];$replace[$getVar[boop-give;$get[user]]; ;;-1]]]
      $let[boop;$if[$get[boop-sum]!=;$if[$get[boop-sum]<=9;   $get[boop-sum]   ;$if[$get[boop-sum]<=99;   $get[boop-sum]  ;$if[$get[boop-sum]<=999;  $get[boop-sum]  ;$if[$get[boop-sum]<=9999;  $get[boop-sum] ;$if[$get[boop-sum]<=99999; $get[boop-sum] ;$if[$get[boop-sum]<=999999; $get[boop-sum];$if[$get[boop-sum]<=9999999;$get[boop-sum];9999999]]]]]]];   0   ]]

      $let[cheer-give;$if[$getVar[cheer-give;$get[user]]!=;$if[$getVar[cheer-give;$get[user]]<=9;   $getVar[cheer-give;$get[user]]   ;$if[$getVar[cheer-give;$get[user]]<=99;   $getVar[cheer-give;$get[user]]  ;$if[$getVar[cheer-give;$get[user]]<=999;  $getVar[cheer-give;$get[user]]  ;$if[$getVar[cheer-give;$get[user]]<=9999;  $getVar[cheer-give;$get[user]] ;$if[$getVar[cheer-give;$get[user]]<=99999; $getVar[cheer-give;$get[user]] ;$if[$getVar[cheer-give;$get[user]]<=999999; $getVar[cheer-give;$get[user]];$if[$getVar[cheer-give;$get[user]]<=9999999;$getVar[cheer-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[cheer-gotten;$if[$getVar[cheer-gotten;$get[user]]!=;$if[$getVar[cheer-gotten;$get[user]]<=9;   $getVar[cheer-gotten;$get[user]]   ;$if[$getVar[cheer-gotten;$get[user]]<=99;   $getVar[cheer-gotten;$get[user]]  ;$if[$getVar[cheer-gotten;$get[user]]<=999;  $getVar[cheer-gotten;$get[user]]  ;$if[$getVar[cheer-gotten;$get[user]]<=9999;  $getVar[cheer-gotten;$get[user]] ;$if[$getVar[cheer-gotten;$get[user]]<=99999; $getVar[cheer-gotten;$get[user]] ;$if[$getVar[cheer-gotten;$get[user]]<=999999; $getVar[cheer-gotten;$get[user]];$if[$getVar[cheer-gotten;$get[user]]<=9999999;$getVar[cheer-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[cheer-sum;$sum[$replace[$getVar[cheer-gotten;$get[user]]; ;;-1];$replace[$getVar[cheer-give;$get[user]]; ;;-1]]]
      $let[cheer;$if[$get[cheer-sum]!=;$if[$get[cheer-sum]<=9;   $get[cheer-sum]   ;$if[$get[cheer-sum]<=99;   $get[cheer-sum]  ;$if[$get[cheer-sum]<=999;  $get[cheer-sum]  ;$if[$get[cheer-sum]<=9999;  $get[cheer-sum] ;$if[$get[cheer-sum]<=99999; $get[cheer-sum] ;$if[$get[cheer-sum]<=999999; $get[cheer-sum];$if[$get[cheer-sum]<=9999999;$get[cheer-sum];9999999]]]]]]];   0   ]]

      $let[cuddle-give;$if[$getVar[cuddle-give;$get[user]]!=;$if[$getVar[cuddle-give;$get[user]]<=9;   $getVar[cuddle-give;$get[user]]   ;$if[$getVar[cuddle-give;$get[user]]<=99;   $getVar[cuddle-give;$get[user]]  ;$if[$getVar[cuddle-give;$get[user]]<=999;  $getVar[cuddle-give;$get[user]]  ;$if[$getVar[cuddle-give;$get[user]]<=9999;  $getVar[cuddle-give;$get[user]] ;$if[$getVar[cuddle-give;$get[user]]<=99999; $getVar[cuddle-give;$get[user]] ;$if[$getVar[cuddle-give;$get[user]]<=999999; $getVar[cuddle-give;$get[user]];$if[$getVar[cuddle-give;$get[user]]<=9999999;$getVar[cuddle-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[cuddle-gotten;$if[$getVar[cuddle-gotten;$get[user]]!=;$if[$getVar[cuddle-gotten;$get[user]]<=9;   $getVar[cuddle-gotten;$get[user]]   ;$if[$getVar[cuddle-gotten;$get[user]]<=99;   $getVar[cuddle-gotten;$get[user]]  ;$if[$getVar[cuddle-gotten;$get[user]]<=999;  $getVar[cuddle-gotten;$get[user]]  ;$if[$getVar[cuddle-gotten;$get[user]]<=9999;  $getVar[cuddle-gotten;$get[user]] ;$if[$getVar[cuddle-gotten;$get[user]]<=99999; $getVar[cuddle-gotten;$get[user]] ;$if[$getVar[cuddle-gotten;$get[user]]<=999999; $getVar[cuddle-gotten;$get[user]];$if[$getVar[cuddle-gotten;$get[user]]<=9999999;$getVar[cuddle-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[cuddle-sum;$sum[$replace[$getVar[cuddle-gotten;$get[user]]; ;;-1];$replace[$getVar[cuddle-give;$get[user]]; ;;-1]]]
      $let[cuddle;$if[$get[cuddle-sum]!=;$if[$get[cuddle-sum]<=9;   $get[cuddle-sum]   ;$if[$get[cuddle-sum]<=99;   $get[cuddle-sum]  ;$if[$get[cuddle-sum]<=999;  $get[cuddle-sum]  ;$if[$get[cuddle-sum]<=9999;  $get[cuddle-sum] ;$if[$get[cuddle-sum]<=99999; $get[cuddle-sum] ;$if[$get[cuddle-sum]<=999999; $get[cuddle-sum];$if[$get[cuddle-sum]<=9999999;$get[cuddle-sum];9999999]]]]]]];   0   ]]

      $let[dance-give;$if[$getVar[dance-give;$get[user]]!=;$if[$getVar[dance-give;$get[user]]<=9;   $getVar[dance-give;$get[user]]   ;$if[$getVar[dance-give;$get[user]]<=99;   $getVar[dance-give;$get[user]]  ;$if[$getVar[dance-give;$get[user]]<=999;  $getVar[dance-give;$get[user]]  ;$if[$getVar[dance-give;$get[user]]<=9999;  $getVar[dance-give;$get[user]] ;$if[$getVar[dance-give;$get[user]]<=99999; $getVar[dance-give;$get[user]] ;$if[$getVar[dance-give;$get[user]]<=999999; $getVar[dance-give;$get[user]];$if[$getVar[dance-give;$get[user]]<=9999999;$getVar[dance-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[dance-gotten;$if[$getVar[dance-gotten;$get[user]]!=;$if[$getVar[dance-gotten;$get[user]]<=9;   $getVar[dance-gotten;$get[user]]   ;$if[$getVar[dance-gotten;$get[user]]<=99;   $getVar[dance-gotten;$get[user]]  ;$if[$getVar[dance-gotten;$get[user]]<=999;  $getVar[dance-gotten;$get[user]]  ;$if[$getVar[dance-gotten;$get[user]]<=9999;  $getVar[dance-gotten;$get[user]] ;$if[$getVar[dance-gotten;$get[user]]<=99999; $getVar[dance-gotten;$get[user]] ;$if[$getVar[dance-gotten;$get[user]]<=999999; $getVar[dance-gotten;$get[user]];$if[$getVar[dance-gotten;$get[user]]<=9999999;$getVar[dance-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[dance-sum;$sum[$replace[$getVar[dance-gotten;$get[user]]; ;;-1];$replace[$getVar[dance-give;$get[user]]; ;;-1]]]
      $let[dance;$if[$get[dance-sum]!=;$if[$get[dance-sum]<=9;   $get[dance-sum]   ;$if[$get[dance-sum]<=99;   $get[dance-sum]  ;$if[$get[dance-sum]<=999;  $get[dance-sum]  ;$if[$get[dance-sum]<=9999;  $get[dance-sum] ;$if[$get[dance-sum]<=99999; $get[dance-sum] ;$if[$get[dance-sum]<=999999; $get[dance-sum];$if[$get[dance-sum]<=9999999;$get[dance-sum];9999999]]]]]]];   0   ]]

      $let[feed-give;$if[$getVar[feed-give;$get[user]]!=;$if[$getVar[feed-give;$get[user]]<=9;   $getVar[feed-give;$get[user]]   ;$if[$getVar[feed-give;$get[user]]<=99;   $getVar[feed-give;$get[user]]  ;$if[$getVar[feed-give;$get[user]]<=999;  $getVar[feed-give;$get[user]]  ;$if[$getVar[feed-give;$get[user]]<=9999;  $getVar[feed-give;$get[user]] ;$if[$getVar[feed-give;$get[user]]<=99999; $getVar[feed-give;$get[user]] ;$if[$getVar[feed-give;$get[user]]<=999999; $getVar[feed-give;$get[user]];$if[$getVar[feed-give;$get[user]]<=9999999;$getVar[feed-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[feed-gotten;$if[$getVar[feed-gotten;$get[user]]!=;$if[$getVar[feed-gotten;$get[user]]<=9;   $getVar[feed-gotten;$get[user]]   ;$if[$getVar[feed-gotten;$get[user]]<=99;   $getVar[feed-gotten;$get[user]]  ;$if[$getVar[feed-gotten;$get[user]]<=999;  $getVar[feed-gotten;$get[user]]  ;$if[$getVar[feed-gotten;$get[user]]<=9999;  $getVar[feed-gotten;$get[user]] ;$if[$getVar[feed-gotten;$get[user]]<=99999; $getVar[feed-gotten;$get[user]] ;$if[$getVar[feed-gotten;$get[user]]<=999999; $getVar[feed-gotten;$get[user]];$if[$getVar[feed-gotten;$get[user]]<=9999999;$getVar[feed-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[feed-sum;$sum[$replace[$getVar[feed-gotten;$get[user]]; ;;-1];$replace[$getVar[feed-give;$get[user]]; ;;-1]]]
      $let[feed;$if[$get[feed-sum]!=;$if[$get[feed-sum]<=9;   $get[feed-sum]   ;$if[$get[feed-sum]<=99;   $get[feed-sum]  ;$if[$get[feed-sum]<=999;  $get[feed-sum]  ;$if[$get[feed-sum]<=9999;  $get[feed-sum] ;$if[$get[feed-sum]<=99999; $get[feed-sum] ;$if[$get[feed-sum]<=999999; $get[feed-sum];$if[$get[feed-sum]<=9999999;$get[feed-sum];9999999]]]]]]];   0   ]]

      $let[glomp-give;$if[$getVar[glomp-give;$get[user]]!=;$if[$getVar[glomp-give;$get[user]]<=9;   $getVar[glomp-give;$get[user]]   ;$if[$getVar[glomp-give;$get[user]]<=99;   $getVar[glomp-give;$get[user]]  ;$if[$getVar[glomp-give;$get[user]]<=999;  $getVar[glomp-give;$get[user]]  ;$if[$getVar[glomp-give;$get[user]]<=9999;  $getVar[glomp-give;$get[user]] ;$if[$getVar[glomp-give;$get[user]]<=99999; $getVar[glomp-give;$get[user]] ;$if[$getVar[glomp-give;$get[user]]<=999999; $getVar[glomp-give;$get[user]];$if[$getVar[glomp-give;$get[user]]<=9999999;$getVar[glomp-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[glomp-gotten;$if[$getVar[glomp-gotten;$get[user]]!=;$if[$getVar[glomp-gotten;$get[user]]<=9;   $getVar[glomp-gotten;$get[user]]   ;$if[$getVar[glomp-gotten;$get[user]]<=99;   $getVar[glomp-gotten;$get[user]]  ;$if[$getVar[glomp-gotten;$get[user]]<=999;  $getVar[glomp-gotten;$get[user]]  ;$if[$getVar[glomp-gotten;$get[user]]<=9999;  $getVar[glomp-gotten;$get[user]] ;$if[$getVar[glomp-gotten;$get[user]]<=99999; $getVar[glomp-gotten;$get[user]] ;$if[$getVar[glomp-gotten;$get[user]]<=999999; $getVar[glomp-gotten;$get[user]];$if[$getVar[glomp-gotten;$get[user]]<=9999999;$getVar[glomp-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[glomp-sum;$sum[$replace[$getVar[glomp-gotten;$get[user]]; ;;-1];$replace[$getVar[glomp-give;$get[user]]; ;;-1]]]
      $let[glomp;$if[$get[glomp-sum]!=;$if[$get[glomp-sum]<=9;   $get[glomp-sum]   ;$if[$get[glomp-sum]<=99;   $get[glomp-sum]  ;$if[$get[glomp-sum]<=999;  $get[glomp-sum]  ;$if[$get[glomp-sum]<=9999;  $get[glomp-sum] ;$if[$get[glomp-sum]<=99999; $get[glomp-sum] ;$if[$get[glomp-sum]<=999999; $get[glomp-sum];$if[$get[glomp-sum]<=9999999;$get[glomp-sum];9999999]]]]]]];   0   ]]

      $let[handhold-give;$if[$getVar[handhold-give;$get[user]]!=;$if[$getVar[handhold-give;$get[user]]<=9;   $getVar[handhold-give;$get[user]]   ;$if[$getVar[handhold-give;$get[user]]<=99;   $getVar[handhold-give;$get[user]]  ;$if[$getVar[handhold-give;$get[user]]<=999;  $getVar[handhold-give;$get[user]]  ;$if[$getVar[handhold-give;$get[user]]<=9999;  $getVar[handhold-give;$get[user]] ;$if[$getVar[handhold-give;$get[user]]<=99999; $getVar[handhold-give;$get[user]] ;$if[$getVar[handhold-give;$get[user]]<=999999; $getVar[handhold-give;$get[user]];$if[$getVar[handhold-give;$get[user]]<=9999999;$getVar[handhold-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[handhold-gotten;$if[$getVar[handhold-gotten;$get[user]]!=;$if[$getVar[handhold-gotten;$get[user]]<=9;   $getVar[handhold-gotten;$get[user]]   ;$if[$getVar[handhold-gotten;$get[user]]<=99;   $getVar[handhold-gotten;$get[user]]  ;$if[$getVar[handhold-gotten;$get[user]]<=999;  $getVar[handhold-gotten;$get[user]]  ;$if[$getVar[handhold-gotten;$get[user]]<=9999;  $getVar[handhold-gotten;$get[user]] ;$if[$getVar[handhold-gotten;$get[user]]<=99999; $getVar[handhold-gotten;$get[user]] ;$if[$getVar[handhold-gotten;$get[user]]<=999999; $getVar[handhold-gotten;$get[user]];$if[$getVar[handhold-gotten;$get[user]]<=9999999;$getVar[handhold-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[handhold-sum;$sum[$replace[$getVar[handhold-gotten;$get[user]]; ;;-1];$replace[$getVar[handhold-give;$get[user]]; ;;-1]]]
      $let[handhold;$if[$get[handhold-sum]!=;$if[$get[handhold-sum]<=9;   $get[handhold-sum]   ;$if[$get[handhold-sum]<=99;   $get[handhold-sum]  ;$if[$get[handhold-sum]<=999;  $get[handhold-sum]  ;$if[$get[handhold-sum]<=9999;  $get[handhold-sum] ;$if[$get[handhold-sum]<=99999; $get[handhold-sum] ;$if[$get[handhold-sum]<=999999; $get[handhold-sum];$if[$get[handhold-sum]<=9999999;$get[handhold-sum];9999999]]]]]]];   0   ]]

      $let[happy-give;$if[$getVar[happy-give;$get[user]]!=;$if[$getVar[happy-give;$get[user]]<=9;   $getVar[happy-give;$get[user]]   ;$if[$getVar[happy-give;$get[user]]<=99;   $getVar[happy-give;$get[user]]  ;$if[$getVar[happy-give;$get[user]]<=999;  $getVar[happy-give;$get[user]]  ;$if[$getVar[happy-give;$get[user]]<=9999;  $getVar[happy-give;$get[user]] ;$if[$getVar[happy-give;$get[user]]<=99999; $getVar[happy-give;$get[user]] ;$if[$getVar[happy-give;$get[user]]<=999999; $getVar[happy-give;$get[user]];$if[$getVar[happy-give;$get[user]]<=9999999;$getVar[happy-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[happy-gotten;$if[$getVar[happy-gotten;$get[user]]!=;$if[$getVar[happy-gotten;$get[user]]<=9;   $getVar[happy-gotten;$get[user]]   ;$if[$getVar[happy-gotten;$get[user]]<=99;   $getVar[happy-gotten;$get[user]]  ;$if[$getVar[happy-gotten;$get[user]]<=999;  $getVar[happy-gotten;$get[user]]  ;$if[$getVar[happy-gotten;$get[user]]<=9999;  $getVar[happy-gotten;$get[user]] ;$if[$getVar[happy-gotten;$get[user]]<=99999; $getVar[happy-gotten;$get[user]] ;$if[$getVar[happy-gotten;$get[user]]<=999999; $getVar[happy-gotten;$get[user]];$if[$getVar[happy-gotten;$get[user]]<=9999999;$getVar[happy-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[happy-sum;$sum[$replace[$getVar[happy-gotten;$get[user]]; ;;-1];$replace[$getVar[happy-give;$get[user]]; ;;-1]]]
      $let[happy;$if[$get[happy-sum]!=;$if[$get[happy-sum]<=9;   $get[happy-sum]   ;$if[$get[happy-sum]<=99;   $get[happy-sum]  ;$if[$get[happy-sum]<=999;  $get[happy-sum]  ;$if[$get[happy-sum]<=9999;  $get[happy-sum] ;$if[$get[happy-sum]<=99999; $get[happy-sum] ;$if[$get[happy-sum]<=999999; $get[happy-sum];$if[$get[happy-sum]<=9999999;$get[happy-sum];9999999]]]]]]];   0   ]]

      $let[highfive-give;$if[$getVar[highfive-give;$get[user]]!=;$if[$getVar[highfive-give;$get[user]]<=9;   $getVar[highfive-give;$get[user]]   ;$if[$getVar[highfive-give;$get[user]]<=99;   $getVar[highfive-give;$get[user]]  ;$if[$getVar[highfive-give;$get[user]]<=999;  $getVar[highfive-give;$get[user]]  ;$if[$getVar[highfive-give;$get[user]]<=9999;  $getVar[highfive-give;$get[user]] ;$if[$getVar[highfive-give;$get[user]]<=99999; $getVar[highfive-give;$get[user]] ;$if[$getVar[highfive-give;$get[user]]<=999999; $getVar[highfive-give;$get[user]];$if[$getVar[highfive-give;$get[user]]<=9999999;$getVar[highfive-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[highfive-gotten;$if[$getVar[highfive-gotten;$get[user]]!=;$if[$getVar[highfive-gotten;$get[user]]<=9;   $getVar[highfive-gotten;$get[user]]   ;$if[$getVar[highfive-gotten;$get[user]]<=99;   $getVar[highfive-gotten;$get[user]]  ;$if[$getVar[highfive-gotten;$get[user]]<=999;  $getVar[highfive-gotten;$get[user]]  ;$if[$getVar[highfive-gotten;$get[user]]<=9999;  $getVar[highfive-gotten;$get[user]] ;$if[$getVar[highfive-gotten;$get[user]]<=99999; $getVar[highfive-gotten;$get[user]] ;$if[$getVar[highfive-gotten;$get[user]]<=999999; $getVar[highfive-gotten;$get[user]];$if[$getVar[highfive-gotten;$get[user]]<=9999999;$getVar[highfive-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[highfive-sum;$sum[$replace[$getVar[highfive-gotten;$get[user]]; ;;-1];$replace[$getVar[highfive-give;$get[user]]; ;;-1]]]
      $let[highfive;$if[$get[highfive-sum]!=;$if[$get[highfive-sum]<=9;   $get[highfive-sum]   ;$if[$get[highfive-sum]<=99;   $get[highfive-sum]  ;$if[$get[highfive-sum]<=999;  $get[highfive-sum]  ;$if[$get[highfive-sum]<=9999;  $get[highfive-sum] ;$if[$get[highfive-sum]<=99999; $get[highfive-sum] ;$if[$get[highfive-sum]<=999999; $get[highfive-sum];$if[$get[highfive-sum]<=9999999;$get[highfive-sum];9999999]]]]]]];   0   ]]

      $let[hug-give;$if[$getVar[hug-give;$get[user]]!=;$if[$getVar[hug-give;$get[user]]<=9;   $getVar[hug-give;$get[user]]   ;$if[$getVar[hug-give;$get[user]]<=99;   $getVar[hug-give;$get[user]]  ;$if[$getVar[hug-give;$get[user]]<=999;  $getVar[hug-give;$get[user]]  ;$if[$getVar[hug-give;$get[user]]<=9999;  $getVar[hug-give;$get[user]] ;$if[$getVar[hug-give;$get[user]]<=99999; $getVar[hug-give;$get[user]] ;$if[$getVar[hug-give;$get[user]]<=999999; $getVar[hug-give;$get[user]];$if[$getVar[hug-give;$get[user]]<=9999999;$getVar[hug-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[hug-gotten;$if[$getVar[hug-gotten;$get[user]]!=;$if[$getVar[hug-gotten;$get[user]]<=9;   $getVar[hug-gotten;$get[user]]   ;$if[$getVar[hug-gotten;$get[user]]<=99;   $getVar[hug-gotten;$get[user]]  ;$if[$getVar[hug-gotten;$get[user]]<=999;  $getVar[hug-gotten;$get[user]]  ;$if[$getVar[hug-gotten;$get[user]]<=9999;  $getVar[hug-gotten;$get[user]] ;$if[$getVar[hug-gotten;$get[user]]<=99999; $getVar[hug-gotten;$get[user]] ;$if[$getVar[hug-gotten;$get[user]]<=999999; $getVar[hug-gotten;$get[user]];$if[$getVar[hug-gotten;$get[user]]<=9999999;$getVar[hug-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[hug-sum;$sum[$replace[$getVar[hug-gotten;$get[user]]; ;;-1];$replace[$getVar[hug-give;$get[user]]; ;;-1]]]
      $let[hug;$if[$get[hug-sum]!=;$if[$get[hug-sum]<=9;   $get[hug-sum]   ;$if[$get[hug-sum]<=99;   $get[hug-sum]  ;$if[$get[hug-sum]<=999;  $get[hug-sum]  ;$if[$get[hug-sum]<=9999;  $get[hug-sum] ;$if[$get[hug-sum]<=99999; $get[hug-sum] ;$if[$get[hug-sum]<=999999; $get[hug-sum];$if[$get[hug-sum]<=9999999;$get[hug-sum];9999999]]]]]]];   0   ]]

      $let[kiss-give;$if[$getVar[kiss-give;$get[user]]!=;$if[$getVar[kiss-give;$get[user]]<=9;   $getVar[kiss-give;$get[user]]   ;$if[$getVar[kiss-give;$get[user]]<=99;   $getVar[kiss-give;$get[user]]  ;$if[$getVar[kiss-give;$get[user]]<=999;  $getVar[kiss-give;$get[user]]  ;$if[$getVar[kiss-give;$get[user]]<=9999;  $getVar[kiss-give;$get[user]] ;$if[$getVar[kiss-give;$get[user]]<=99999; $getVar[kiss-give;$get[user]] ;$if[$getVar[kiss-give;$get[user]]<=999999; $getVar[kiss-give;$get[user]];$if[$getVar[kiss-give;$get[user]]<=9999999;$getVar[kiss-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[kiss-gotten;$if[$getVar[kiss-gotten;$get[user]]!=;$if[$getVar[kiss-gotten;$get[user]]<=9;   $getVar[kiss-gotten;$get[user]]   ;$if[$getVar[kiss-gotten;$get[user]]<=99;   $getVar[kiss-gotten;$get[user]]  ;$if[$getVar[kiss-gotten;$get[user]]<=999;  $getVar[kiss-gotten;$get[user]]  ;$if[$getVar[kiss-gotten;$get[user]]<=9999;  $getVar[kiss-gotten;$get[user]] ;$if[$getVar[kiss-gotten;$get[user]]<=99999; $getVar[kiss-gotten;$get[user]] ;$if[$getVar[kiss-gotten;$get[user]]<=999999; $getVar[kiss-gotten;$get[user]];$if[$getVar[kiss-gotten;$get[user]]<=9999999;$getVar[kiss-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[kiss-sum;$sum[$replace[$getVar[kiss-gotten;$get[user]]; ;;-1];$replace[$getVar[kiss-give;$get[user]]; ;;-1]]]
      $let[kiss;$if[$get[kiss-sum]!=;$if[$get[kiss-sum]<=9;   $get[kiss-sum]   ;$if[$get[kiss-sum]<=99;   $get[kiss-sum]  ;$if[$get[kiss-sum]<=999;  $get[kiss-sum]  ;$if[$get[kiss-sum]<=9999;  $get[kiss-sum] ;$if[$get[kiss-sum]<=99999; $get[kiss-sum] ;$if[$get[kiss-sum]<=999999; $get[kiss-sum];$if[$get[kiss-sum]<=9999999;$get[kiss-sum];9999999]]]]]]];   0   ]]

      $let[laugh-give;$if[$getVar[laugh-give;$get[user]]!=;$if[$getVar[laugh-give;$get[user]]<=9;   $getVar[laugh-give;$get[user]]   ;$if[$getVar[laugh-give;$get[user]]<=99;   $getVar[laugh-give;$get[user]]  ;$if[$getVar[laugh-give;$get[user]]<=999;  $getVar[laugh-give;$get[user]]  ;$if[$getVar[laugh-give;$get[user]]<=9999;  $getVar[laugh-give;$get[user]] ;$if[$getVar[laugh-give;$get[user]]<=99999; $getVar[laugh-give;$get[user]] ;$if[$getVar[laugh-give;$get[user]]<=999999; $getVar[laugh-give;$get[user]];$if[$getVar[laugh-give;$get[user]]<=9999999;$getVar[laugh-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[laugh-gotten;$if[$getVar[laugh-gotten;$get[user]]!=;$if[$getVar[laugh-gotten;$get[user]]<=9;   $getVar[laugh-gotten;$get[user]]   ;$if[$getVar[laugh-gotten;$get[user]]<=99;   $getVar[laugh-gotten;$get[user]]  ;$if[$getVar[laugh-gotten;$get[user]]<=999;  $getVar[laugh-gotten;$get[user]]  ;$if[$getVar[laugh-gotten;$get[user]]<=9999;  $getVar[laugh-gotten;$get[user]] ;$if[$getVar[laugh-gotten;$get[user]]<=99999; $getVar[laugh-gotten;$get[user]] ;$if[$getVar[laugh-gotten;$get[user]]<=999999; $getVar[laugh-gotten;$get[user]];$if[$getVar[laugh-gotten;$get[user]]<=9999999;$getVar[laugh-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[laugh-sum;$sum[$replace[$getVar[laugh-gotten;$get[user]]; ;;-1];$replace[$getVar[laugh-give;$get[user]]; ;;-1]]]
      $let[laugh;$if[$get[laugh-sum]!=;$if[$get[laugh-sum]<=9;   $get[laugh-sum]   ;$if[$get[laugh-sum]<=99;   $get[laugh-sum]  ;$if[$get[laugh-sum]<=999;  $get[laugh-sum]  ;$if[$get[laugh-sum]<=9999;  $get[laugh-sum] ;$if[$get[laugh-sum]<=99999; $get[laugh-sum] ;$if[$get[laugh-sum]<=999999; $get[laugh-sum];$if[$get[laugh-sum]<=9999999;$get[laugh-sum];9999999]]]]]]];   0   ]]

      $let[lick-give;$if[$getVar[lick-give;$get[user]]!=;$if[$getVar[lick-give;$get[user]]<=9;   $getVar[lick-give;$get[user]]   ;$if[$getVar[lick-give;$get[user]]<=99;   $getVar[lick-give;$get[user]]  ;$if[$getVar[lick-give;$get[user]]<=999;  $getVar[lick-give;$get[user]]  ;$if[$getVar[lick-give;$get[user]]<=9999;  $getVar[lick-give;$get[user]] ;$if[$getVar[lick-give;$get[user]]<=99999; $getVar[lick-give;$get[user]] ;$if[$getVar[lick-give;$get[user]]<=999999; $getVar[lick-give;$get[user]];$if[$getVar[lick-give;$get[user]]<=9999999;$getVar[lick-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[lick-gotten;$if[$getVar[lick-gotten;$get[user]]!=;$if[$getVar[lick-gotten;$get[user]]<=9;   $getVar[lick-gotten;$get[user]]   ;$if[$getVar[lick-gotten;$get[user]]<=99;   $getVar[lick-gotten;$get[user]]  ;$if[$getVar[lick-gotten;$get[user]]<=999;  $getVar[lick-gotten;$get[user]]  ;$if[$getVar[lick-gotten;$get[user]]<=9999;  $getVar[lick-gotten;$get[user]] ;$if[$getVar[lick-gotten;$get[user]]<=99999; $getVar[lick-gotten;$get[user]] ;$if[$getVar[lick-gotten;$get[user]]<=999999; $getVar[lick-gotten;$get[user]];$if[$getVar[lick-gotten;$get[user]]<=9999999;$getVar[lick-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[lick-sum;$sum[$replace[$getVar[lick-gotten;$get[user]]; ;;-1];$replace[$getVar[lick-give;$get[user]]; ;;-1]]]
      $let[lick;$if[$get[lick-sum]!=;$if[$get[lick-sum]<=9;   $get[lick-sum]   ;$if[$get[lick-sum]<=99;   $get[lick-sum]  ;$if[$get[lick-sum]<=999;  $get[lick-sum]  ;$if[$get[lick-sum]<=9999;  $get[lick-sum] ;$if[$get[lick-sum]<=99999; $get[lick-sum] ;$if[$get[lick-sum]<=999999; $get[lick-sum];$if[$get[lick-sum]<=9999999;$get[lick-sum];9999999]]]]]]];   0   ]]

      $let[love-give;$if[$getVar[love-give;$get[user]]!=;$if[$getVar[love-give;$get[user]]<=9;   $getVar[love-give;$get[user]]   ;$if[$getVar[love-give;$get[user]]<=99;   $getVar[love-give;$get[user]]  ;$if[$getVar[love-give;$get[user]]<=999;  $getVar[love-give;$get[user]]  ;$if[$getVar[love-give;$get[user]]<=9999;  $getVar[love-give;$get[user]] ;$if[$getVar[love-give;$get[user]]<=99999; $getVar[love-give;$get[user]] ;$if[$getVar[love-give;$get[user]]<=999999; $getVar[love-give;$get[user]];$if[$getVar[love-give;$get[user]]<=9999999;$getVar[love-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[love-gotten;$if[$getVar[love-gotten;$get[user]]!=;$if[$getVar[love-gotten;$get[user]]<=9;   $getVar[love-gotten;$get[user]]   ;$if[$getVar[love-gotten;$get[user]]<=99;   $getVar[love-gotten;$get[user]]  ;$if[$getVar[love-gotten;$get[user]]<=999;  $getVar[love-gotten;$get[user]]  ;$if[$getVar[love-gotten;$get[user]]<=9999;  $getVar[love-gotten;$get[user]] ;$if[$getVar[love-gotten;$get[user]]<=99999; $getVar[love-gotten;$get[user]] ;$if[$getVar[love-gotten;$get[user]]<=999999; $getVar[love-gotten;$get[user]];$if[$getVar[love-gotten;$get[user]]<=9999999;$getVar[love-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[love-sum;$sum[$replace[$getVar[love-gotten;$get[user]]; ;;-1];$replace[$getVar[love-give;$get[user]]; ;;-1]]]
      $let[love;$if[$get[love-sum]!=;$if[$get[love-sum]<=9;   $get[love-sum]   ;$if[$get[love-sum]<=99;   $get[love-sum]  ;$if[$get[love-sum]<=999;  $get[love-sum]  ;$if[$get[love-sum]<=9999;  $get[love-sum] ;$if[$get[love-sum]<=99999; $get[love-sum] ;$if[$get[love-sum]<=999999; $get[love-sum];$if[$get[love-sum]<=9999999;$get[love-sum];9999999]]]]]]];   0   ]]

      $let[lurk-give;$if[$getVar[lurk-give;$get[user]]!=;$if[$getVar[lurk-give;$get[user]]<=9;   $getVar[lurk-give;$get[user]]   ;$if[$getVar[lurk-give;$get[user]]<=99;   $getVar[lurk-give;$get[user]]  ;$if[$getVar[lurk-give;$get[user]]<=999;  $getVar[lurk-give;$get[user]]  ;$if[$getVar[lurk-give;$get[user]]<=9999;  $getVar[lurk-give;$get[user]] ;$if[$getVar[lurk-give;$get[user]]<=99999; $getVar[lurk-give;$get[user]] ;$if[$getVar[lurk-give;$get[user]]<=999999; $getVar[lurk-give;$get[user]];$if[$getVar[lurk-give;$get[user]]<=9999999;$getVar[lurk-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[lurk-gotten;$if[$getVar[lurk-gotten;$get[user]]!=;$if[$getVar[lurk-gotten;$get[user]]<=9;   $getVar[lurk-gotten;$get[user]]   ;$if[$getVar[lurk-gotten;$get[user]]<=99;   $getVar[lurk-gotten;$get[user]]  ;$if[$getVar[lurk-gotten;$get[user]]<=999;  $getVar[lurk-gotten;$get[user]]  ;$if[$getVar[lurk-gotten;$get[user]]<=9999;  $getVar[lurk-gotten;$get[user]] ;$if[$getVar[lurk-gotten;$get[user]]<=99999; $getVar[lurk-gotten;$get[user]] ;$if[$getVar[lurk-gotten;$get[user]]<=999999; $getVar[lurk-gotten;$get[user]];$if[$getVar[lurk-gotten;$get[user]]<=9999999;$getVar[lurk-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[lurk-sum;$sum[$replace[$getVar[lurk-gotten;$get[user]]; ;;-1];$replace[$getVar[lurk-give;$get[user]]; ;;-1]]]
      $let[lurk;$if[$get[lurk-sum]!=;$if[$get[lurk-sum]<=9;   $get[lurk-sum]   ;$if[$get[lurk-sum]<=99;   $get[lurk-sum]  ;$if[$get[lurk-sum]<=999;  $get[lurk-sum]  ;$if[$get[lurk-sum]<=9999;  $get[lurk-sum] ;$if[$get[lurk-sum]<=99999; $get[lurk-sum] ;$if[$get[lurk-sum]<=999999; $get[lurk-sum];$if[$get[lurk-sum]<=9999999;$get[lurk-sum];9999999]]]]]]];   0   ]]

      $let[nom-give;$if[$getVar[nom-give;$get[user]]!=;$if[$getVar[nom-give;$get[user]]<=9;   $getVar[nom-give;$get[user]]   ;$if[$getVar[nom-give;$get[user]]<=99;   $getVar[nom-give;$get[user]]  ;$if[$getVar[nom-give;$get[user]]<=999;  $getVar[nom-give;$get[user]]  ;$if[$getVar[nom-give;$get[user]]<=9999;  $getVar[nom-give;$get[user]] ;$if[$getVar[nom-give;$get[user]]<=99999; $getVar[nom-give;$get[user]] ;$if[$getVar[nom-give;$get[user]]<=999999; $getVar[nom-give;$get[user]];$if[$getVar[nom-give;$get[user]]<=9999999;$getVar[nom-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[nom-gotten;$if[$getVar[nom-gotten;$get[user]]!=;$if[$getVar[nom-gotten;$get[user]]<=9;   $getVar[nom-gotten;$get[user]]   ;$if[$getVar[nom-gotten;$get[user]]<=99;   $getVar[nom-gotten;$get[user]]  ;$if[$getVar[nom-gotten;$get[user]]<=999;  $getVar[nom-gotten;$get[user]]  ;$if[$getVar[nom-gotten;$get[user]]<=9999;  $getVar[nom-gotten;$get[user]] ;$if[$getVar[nom-gotten;$get[user]]<=99999; $getVar[nom-gotten;$get[user]] ;$if[$getVar[nom-gotten;$get[user]]<=999999; $getVar[nom-gotten;$get[user]];$if[$getVar[nom-gotten;$get[user]]<=9999999;$getVar[nom-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[nom-sum;$sum[$replace[$getVar[nom-gotten;$get[user]]; ;;-1];$replace[$getVar[nom-give;$get[user]]; ;;-1]]]
      $let[nom;$if[$get[nom-sum]!=;$if[$get[nom-sum]<=9;   $get[nom-sum]   ;$if[$get[nom-sum]<=99;   $get[nom-sum]  ;$if[$get[nom-sum]<=999;  $get[nom-sum]  ;$if[$get[nom-sum]<=9999;  $get[nom-sum] ;$if[$get[nom-sum]<=99999; $get[nom-sum] ;$if[$get[nom-sum]<=999999; $get[nom-sum];$if[$get[nom-sum]<=9999999;$get[nom-sum];9999999]]]]]]];   0   ]]

      $let[nuzzle-give;$if[$getVar[nuzzle-give;$get[user]]!=;$if[$getVar[nuzzle-give;$get[user]]<=9;   $getVar[nuzzle-give;$get[user]]   ;$if[$getVar[nuzzle-give;$get[user]]<=99;   $getVar[nuzzle-give;$get[user]]  ;$if[$getVar[nuzzle-give;$get[user]]<=999;  $getVar[nuzzle-give;$get[user]]  ;$if[$getVar[nuzzle-give;$get[user]]<=9999;  $getVar[nuzzle-give;$get[user]] ;$if[$getVar[nuzzle-give;$get[user]]<=99999; $getVar[nuzzle-give;$get[user]] ;$if[$getVar[nuzzle-give;$get[user]]<=999999; $getVar[nuzzle-give;$get[user]];$if[$getVar[nuzzle-give;$get[user]]<=9999999;$getVar[nuzzle-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[nuzzle-gotten;$if[$getVar[nuzzle-gotten;$get[user]]!=;$if[$getVar[nuzzle-gotten;$get[user]]<=9;   $getVar[nuzzle-gotten;$get[user]]   ;$if[$getVar[nuzzle-gotten;$get[user]]<=99;   $getVar[nuzzle-gotten;$get[user]]  ;$if[$getVar[nuzzle-gotten;$get[user]]<=999;  $getVar[nuzzle-gotten;$get[user]]  ;$if[$getVar[nuzzle-gotten;$get[user]]<=9999;  $getVar[nuzzle-gotten;$get[user]] ;$if[$getVar[nuzzle-gotten;$get[user]]<=99999; $getVar[nuzzle-gotten;$get[user]] ;$if[$getVar[nuzzle-gotten;$get[user]]<=999999; $getVar[nuzzle-gotten;$get[user]];$if[$getVar[nuzzle-gotten;$get[user]]<=9999999;$getVar[nuzzle-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[nuzzle-sum;$sum[$replace[$getVar[nuzzle-gotten;$get[user]]; ;;-1];$replace[$getVar[nuzzle-give;$get[user]]; ;;-1]]]
      $let[nuzzle;$if[$get[nuzzle-sum]!=;$if[$get[nuzzle-sum]<=9;   $get[nuzzle-sum]   ;$if[$get[nuzzle-sum]<=99;   $get[nuzzle-sum]  ;$if[$get[nuzzle-sum]<=999;  $get[nuzzle-sum]  ;$if[$get[nuzzle-sum]<=9999;  $get[nuzzle-sum] ;$if[$get[nuzzle-sum]<=99999; $get[nuzzle-sum] ;$if[$get[nuzzle-sum]<=999999; $get[nuzzle-sum];$if[$get[nuzzle-sum]<=9999999;$get[nuzzle-sum];9999999]]]]]]];   0   ]]

      $let[pat-give;$if[$getVar[pat-give;$get[user]]!=;$if[$getVar[pat-give;$get[user]]<=9;   $getVar[pat-give;$get[user]]   ;$if[$getVar[pat-give;$get[user]]<=99;   $getVar[pat-give;$get[user]]  ;$if[$getVar[pat-give;$get[user]]<=999;  $getVar[pat-give;$get[user]]  ;$if[$getVar[pat-give;$get[user]]<=9999;  $getVar[pat-give;$get[user]] ;$if[$getVar[pat-give;$get[user]]<=99999; $getVar[pat-give;$get[user]] ;$if[$getVar[pat-give;$get[user]]<=999999; $getVar[pat-give;$get[user]];$if[$getVar[pat-give;$get[user]]<=9999999;$getVar[pat-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[pat-gotten;$if[$getVar[pat-gotten;$get[user]]!=;$if[$getVar[pat-gotten;$get[user]]<=9;   $getVar[pat-gotten;$get[user]]   ;$if[$getVar[pat-gotten;$get[user]]<=99;   $getVar[pat-gotten;$get[user]]  ;$if[$getVar[pat-gotten;$get[user]]<=999;  $getVar[pat-gotten;$get[user]]  ;$if[$getVar[pat-gotten;$get[user]]<=9999;  $getVar[pat-gotten;$get[user]] ;$if[$getVar[pat-gotten;$get[user]]<=99999; $getVar[pat-gotten;$get[user]] ;$if[$getVar[pat-gotten;$get[user]]<=999999; $getVar[pat-gotten;$get[user]];$if[$getVar[pat-gotten;$get[user]]<=9999999;$getVar[pat-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[pat-sum;$sum[$replace[$getVar[pat-gotten;$get[user]]; ;;-1];$replace[$getVar[pat-give;$get[user]]; ;;-1]]]
      $let[pat;$if[$get[pat-sum]!=;$if[$get[pat-sum]<=9;   $get[pat-sum]   ;$if[$get[pat-sum]<=99;   $get[pat-sum]  ;$if[$get[pat-sum]<=999;  $get[pat-sum]  ;$if[$get[pat-sum]<=9999;  $get[pat-sum] ;$if[$get[pat-sum]<=99999; $get[pat-sum] ;$if[$get[pat-sum]<=999999; $get[pat-sum];$if[$get[pat-sum]<=9999999;$get[pat-sum];9999999]]]]]]];   0   ]]

      $let[peck-give;$if[$getVar[peck-give;$get[user]]!=;$if[$getVar[peck-give;$get[user]]<=9;   $getVar[peck-give;$get[user]]   ;$if[$getVar[peck-give;$get[user]]<=99;   $getVar[peck-give;$get[user]]  ;$if[$getVar[peck-give;$get[user]]<=999;  $getVar[peck-give;$get[user]]  ;$if[$getVar[peck-give;$get[user]]<=9999;  $getVar[peck-give;$get[user]] ;$if[$getVar[peck-give;$get[user]]<=99999; $getVar[peck-give;$get[user]] ;$if[$getVar[peck-give;$get[user]]<=999999; $getVar[peck-give;$get[user]];$if[$getVar[peck-give;$get[user]]<=9999999;$getVar[peck-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[peck-gotten;$if[$getVar[peck-gotten;$get[user]]!=;$if[$getVar[peck-gotten;$get[user]]<=9;   $getVar[peck-gotten;$get[user]]   ;$if[$getVar[peck-gotten;$get[user]]<=99;   $getVar[peck-gotten;$get[user]]  ;$if[$getVar[peck-gotten;$get[user]]<=999;  $getVar[peck-gotten;$get[user]]  ;$if[$getVar[peck-gotten;$get[user]]<=9999;  $getVar[peck-gotten;$get[user]] ;$if[$getVar[peck-gotten;$get[user]]<=99999; $getVar[peck-gotten;$get[user]] ;$if[$getVar[peck-gotten;$get[user]]<=999999; $getVar[peck-gotten;$get[user]];$if[$getVar[peck-gotten;$get[user]]<=9999999;$getVar[peck-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[peck-sum;$sum[$replace[$getVar[peck-gotten;$get[user]]; ;;-1];$replace[$getVar[peck-give;$get[user]]; ;;-1]]]
      $let[peck;$if[$get[peck-sum]!=;$if[$get[peck-sum]<=9;   $get[peck-sum]   ;$if[$get[peck-sum]<=99;   $get[peck-sum]  ;$if[$get[peck-sum]<=999;  $get[peck-sum]  ;$if[$get[peck-sum]<=9999;  $get[peck-sum] ;$if[$get[peck-sum]<=99999; $get[peck-sum] ;$if[$get[peck-sum]<=999999; $get[peck-sum];$if[$get[peck-sum]<=9999999;$get[peck-sum];9999999]]]]]]];   0   ]]

      $let[poke-give;$if[$getVar[poke-give;$get[user]]!=;$if[$getVar[poke-give;$get[user]]<=9;   $getVar[poke-give;$get[user]]   ;$if[$getVar[poke-give;$get[user]]<=99;   $getVar[poke-give;$get[user]]  ;$if[$getVar[poke-give;$get[user]]<=999;  $getVar[poke-give;$get[user]]  ;$if[$getVar[poke-give;$get[user]]<=9999;  $getVar[poke-give;$get[user]] ;$if[$getVar[poke-give;$get[user]]<=99999; $getVar[poke-give;$get[user]] ;$if[$getVar[poke-give;$get[user]]<=999999; $getVar[poke-give;$get[user]];$if[$getVar[poke-give;$get[user]]<=9999999;$getVar[poke-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[poke-gotten;$if[$getVar[poke-gotten;$get[user]]!=;$if[$getVar[poke-gotten;$get[user]]<=9;   $getVar[poke-gotten;$get[user]]   ;$if[$getVar[poke-gotten;$get[user]]<=99;   $getVar[poke-gotten;$get[user]]  ;$if[$getVar[poke-gotten;$get[user]]<=999;  $getVar[poke-gotten;$get[user]]  ;$if[$getVar[poke-gotten;$get[user]]<=9999;  $getVar[poke-gotten;$get[user]] ;$if[$getVar[poke-gotten;$get[user]]<=99999; $getVar[poke-gotten;$get[user]] ;$if[$getVar[poke-gotten;$get[user]]<=999999; $getVar[poke-gotten;$get[user]];$if[$getVar[poke-gotten;$get[user]]<=9999999;$getVar[poke-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[poke-sum;$sum[$replace[$getVar[poke-gotten;$get[user]]; ;;-1];$replace[$getVar[poke-give;$get[user]]; ;;-1]]]
      $let[poke;$if[$get[poke-sum]!=;$if[$get[poke-sum]<=9;   $get[poke-sum]   ;$if[$get[poke-sum]<=99;   $get[poke-sum]  ;$if[$get[poke-sum]<=999;  $get[poke-sum]  ;$if[$get[poke-sum]<=9999;  $get[poke-sum] ;$if[$get[poke-sum]<=99999; $get[poke-sum] ;$if[$get[poke-sum]<=999999; $get[poke-sum];$if[$get[poke-sum]<=9999999;$get[poke-sum];9999999]]]]]]];   0   ]]

      $let[pout-give;$if[$getVar[pout-give;$get[user]]!=;$if[$getVar[pout-give;$get[user]]<=9;   $getVar[pout-give;$get[user]]   ;$if[$getVar[pout-give;$get[user]]<=99;   $getVar[pout-give;$get[user]]  ;$if[$getVar[pout-give;$get[user]]<=999;  $getVar[pout-give;$get[user]]  ;$if[$getVar[pout-give;$get[user]]<=9999;  $getVar[pout-give;$get[user]] ;$if[$getVar[pout-give;$get[user]]<=99999; $getVar[pout-give;$get[user]] ;$if[$getVar[pout-give;$get[user]]<=999999; $getVar[pout-give;$get[user]];$if[$getVar[pout-give;$get[user]]<=9999999;$getVar[pout-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[pout-gotten;$if[$getVar[pout-gotten;$get[user]]!=;$if[$getVar[pout-gotten;$get[user]]<=9;   $getVar[pout-gotten;$get[user]]   ;$if[$getVar[pout-gotten;$get[user]]<=99;   $getVar[pout-gotten;$get[user]]  ;$if[$getVar[pout-gotten;$get[user]]<=999;  $getVar[pout-gotten;$get[user]]  ;$if[$getVar[pout-gotten;$get[user]]<=9999;  $getVar[pout-gotten;$get[user]] ;$if[$getVar[pout-gotten;$get[user]]<=99999; $getVar[pout-gotten;$get[user]] ;$if[$getVar[pout-gotten;$get[user]]<=999999; $getVar[pout-gotten;$get[user]];$if[$getVar[pout-gotten;$get[user]]<=9999999;$getVar[pout-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[pout-sum;$sum[$replace[$getVar[pout-gotten;$get[user]]; ;;-1];$replace[$getVar[pout-give;$get[user]]; ;;-1]]]
      $let[pout;$if[$get[pout-sum]!=;$if[$get[pout-sum]<=9;   $get[pout-sum]   ;$if[$get[pout-sum]<=99;   $get[pout-sum]  ;$if[$get[pout-sum]<=999;  $get[pout-sum]  ;$if[$get[pout-sum]<=9999;  $get[pout-sum] ;$if[$get[pout-sum]<=99999; $get[pout-sum] ;$if[$get[pout-sum]<=999999; $get[pout-sum];$if[$get[pout-sum]<=9999999;$get[pout-sum];9999999]]]]]]];   0   ]]

      $let[sleep-give;$if[$getVar[sleep-give;$get[user]]!=;$if[$getVar[sleep-give;$get[user]]<=9;   $getVar[sleep-give;$get[user]]   ;$if[$getVar[sleep-give;$get[user]]<=99;   $getVar[sleep-give;$get[user]]  ;$if[$getVar[sleep-give;$get[user]]<=999;  $getVar[sleep-give;$get[user]]  ;$if[$getVar[sleep-give;$get[user]]<=9999;  $getVar[sleep-give;$get[user]] ;$if[$getVar[sleep-give;$get[user]]<=99999; $getVar[sleep-give;$get[user]] ;$if[$getVar[sleep-give;$get[user]]<=999999; $getVar[sleep-give;$get[user]];$if[$getVar[sleep-give;$get[user]]<=9999999;$getVar[sleep-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[sleep-gotten;$if[$getVar[sleep-gotten;$get[user]]!=;$if[$getVar[sleep-gotten;$get[user]]<=9;   $getVar[sleep-gotten;$get[user]]   ;$if[$getVar[sleep-gotten;$get[user]]<=99;   $getVar[sleep-gotten;$get[user]]  ;$if[$getVar[sleep-gotten;$get[user]]<=999;  $getVar[sleep-gotten;$get[user]]  ;$if[$getVar[sleep-gotten;$get[user]]<=9999;  $getVar[sleep-gotten;$get[user]] ;$if[$getVar[sleep-gotten;$get[user]]<=99999; $getVar[sleep-gotten;$get[user]] ;$if[$getVar[sleep-gotten;$get[user]]<=999999; $getVar[sleep-gotten;$get[user]];$if[$getVar[sleep-gotten;$get[user]]<=9999999;$getVar[sleep-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[sleep-sum;$sum[$replace[$getVar[sleep-gotten;$get[user]]; ;;-1];$replace[$getVar[sleep-give;$get[user]]; ;;-1]]]
      $let[sleep;$if[$get[sleep-sum]!=;$if[$get[sleep-sum]<=9;   $get[sleep-sum]   ;$if[$get[sleep-sum]<=99;   $get[sleep-sum]  ;$if[$get[sleep-sum]<=999;  $get[sleep-sum]  ;$if[$get[sleep-sum]<=9999;  $get[sleep-sum] ;$if[$get[sleep-sum]<=99999; $get[sleep-sum] ;$if[$get[sleep-sum]<=999999; $get[sleep-sum];$if[$get[sleep-sum]<=9999999;$get[sleep-sum];9999999]]]]]]];   0   ]]

      $let[thumbsup-give;$if[$getVar[thumbsup-give;$get[user]]!=;$if[$getVar[thumbsup-give;$get[user]]<=9;   $getVar[thumbsup-give;$get[user]]   ;$if[$getVar[thumbsup-give;$get[user]]<=99;   $getVar[thumbsup-give;$get[user]]  ;$if[$getVar[thumbsup-give;$get[user]]<=999;  $getVar[thumbsup-give;$get[user]]  ;$if[$getVar[thumbsup-give;$get[user]]<=9999;  $getVar[thumbsup-give;$get[user]] ;$if[$getVar[thumbsup-give;$get[user]]<=99999; $getVar[thumbsup-give;$get[user]] ;$if[$getVar[thumbsup-give;$get[user]]<=999999; $getVar[thumbsup-give;$get[user]];$if[$getVar[thumbsup-give;$get[user]]<=9999999;$getVar[thumbsup-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[thumbsup-gotten;$if[$getVar[thumbsup-gotten;$get[user]]!=;$if[$getVar[thumbsup-gotten;$get[user]]<=9;   $getVar[thumbsup-gotten;$get[user]]   ;$if[$getVar[thumbsup-gotten;$get[user]]<=99;   $getVar[thumbsup-gotten;$get[user]]  ;$if[$getVar[thumbsup-gotten;$get[user]]<=999;  $getVar[thumbsup-gotten;$get[user]]  ;$if[$getVar[thumbsup-gotten;$get[user]]<=9999;  $getVar[thumbsup-gotten;$get[user]] ;$if[$getVar[thumbsup-gotten;$get[user]]<=99999; $getVar[thumbsup-gotten;$get[user]] ;$if[$getVar[thumbsup-gotten;$get[user]]<=999999; $getVar[thumbsup-gotten;$get[user]];$if[$getVar[thumbsup-gotten;$get[user]]<=9999999;$getVar[thumbsup-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[thumbsup-sum;$sum[$replace[$getVar[thumbsup-gotten;$get[user]]; ;;-1];$replace[$getVar[thumbsup-give;$get[user]]; ;;-1]]]
      $let[thumbsup;$if[$get[thumbsup-sum]!=;$if[$get[thumbsup-sum]<=9;   $get[thumbsup-sum]   ;$if[$get[thumbsup-sum]<=99;   $get[thumbsup-sum]  ;$if[$get[thumbsup-sum]<=999;  $get[thumbsup-sum]  ;$if[$get[thumbsup-sum]<=9999;  $get[thumbsup-sum] ;$if[$get[thumbsup-sum]<=99999; $get[thumbsup-sum] ;$if[$get[thumbsup-sum]<=999999; $get[thumbsup-sum];$if[$get[thumbsup-sum]<=9999999;$get[thumbsup-sum];9999999]]]]]]];   0   ]]

      $let[tickle-give;$if[$getVar[tickle-give;$get[user]]!=;$if[$getVar[tickle-give;$get[user]]<=9;   $getVar[tickle-give;$get[user]]   ;$if[$getVar[tickle-give;$get[user]]<=99;   $getVar[tickle-give;$get[user]]  ;$if[$getVar[tickle-give;$get[user]]<=999;  $getVar[tickle-give;$get[user]]  ;$if[$getVar[tickle-give;$get[user]]<=9999;  $getVar[tickle-give;$get[user]] ;$if[$getVar[tickle-give;$get[user]]<=99999; $getVar[tickle-give;$get[user]] ;$if[$getVar[tickle-give;$get[user]]<=999999; $getVar[tickle-give;$get[user]];$if[$getVar[tickle-give;$get[user]]<=9999999;$getVar[tickle-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[tickle-gotten;$if[$getVar[tickle-gotten;$get[user]]!=;$if[$getVar[tickle-gotten;$get[user]]<=9;   $getVar[tickle-gotten;$get[user]]   ;$if[$getVar[tickle-gotten;$get[user]]<=99;   $getVar[tickle-gotten;$get[user]]  ;$if[$getVar[tickle-gotten;$get[user]]<=999;  $getVar[tickle-gotten;$get[user]]  ;$if[$getVar[tickle-gotten;$get[user]]<=9999;  $getVar[tickle-gotten;$get[user]] ;$if[$getVar[tickle-gotten;$get[user]]<=99999; $getVar[tickle-gotten;$get[user]] ;$if[$getVar[tickle-gotten;$get[user]]<=999999; $getVar[tickle-gotten;$get[user]];$if[$getVar[tickle-gotten;$get[user]]<=9999999;$getVar[tickle-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[tickle-sum;$sum[$replace[$getVar[tickle-gotten;$get[user]]; ;;-1];$replace[$getVar[tickle-give;$get[user]]; ;;-1]]]
      $let[tickle;$if[$get[tickle-sum]!=;$if[$get[tickle-sum]<=9;   $get[tickle-sum]   ;$if[$get[tickle-sum]<=99;   $get[tickle-sum]  ;$if[$get[tickle-sum]<=999;  $get[tickle-sum]  ;$if[$get[tickle-sum]<=9999;  $get[tickle-sum] ;$if[$get[tickle-sum]<=99999; $get[tickle-sum] ;$if[$get[tickle-sum]<=999999; $get[tickle-sum];$if[$get[tickle-sum]<=9999999;$get[tickle-sum];9999999]]]]]]];   0   ]]

      $let[wag-give;$if[$getVar[wag-give;$get[user]]!=;$if[$getVar[wag-give;$get[user]]<=9;   $getVar[wag-give;$get[user]]   ;$if[$getVar[wag-give;$get[user]]<=99;   $getVar[wag-give;$get[user]]  ;$if[$getVar[wag-give;$get[user]]<=999;  $getVar[wag-give;$get[user]]  ;$if[$getVar[wag-give;$get[user]]<=9999;  $getVar[wag-give;$get[user]] ;$if[$getVar[wag-give;$get[user]]<=99999; $getVar[wag-give;$get[user]] ;$if[$getVar[wag-give;$get[user]]<=999999; $getVar[wag-give;$get[user]];$if[$getVar[wag-give;$get[user]]<=9999999;$getVar[wag-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[wag-gotten;$if[$getVar[wag-gotten;$get[user]]!=;$if[$getVar[wag-gotten;$get[user]]<=9;   $getVar[wag-gotten;$get[user]]   ;$if[$getVar[wag-gotten;$get[user]]<=99;   $getVar[wag-gotten;$get[user]]  ;$if[$getVar[wag-gotten;$get[user]]<=999;  $getVar[wag-gotten;$get[user]]  ;$if[$getVar[wag-gotten;$get[user]]<=9999;  $getVar[wag-gotten;$get[user]] ;$if[$getVar[wag-gotten;$get[user]]<=99999; $getVar[wag-gotten;$get[user]] ;$if[$getVar[wag-gotten;$get[user]]<=999999; $getVar[wag-gotten;$get[user]];$if[$getVar[wag-gotten;$get[user]]<=9999999;$getVar[wag-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[wag-sum;$sum[$replace[$getVar[wag-gotten;$get[user]]; ;;-1];$replace[$getVar[wag-give;$get[user]]; ;;-1]]]
      $let[wag;$if[$get[wag-sum]!=;$if[$get[wag-sum]<=9;   $get[wag-sum]   ;$if[$get[wag-sum]<=99;   $get[wag-sum]  ;$if[$get[wag-sum]<=999;  $get[wag-sum]  ;$if[$get[wag-sum]<=9999;  $get[wag-sum] ;$if[$get[wag-sum]<=99999; $get[wag-sum] ;$if[$get[wag-sum]<=999999; $get[wag-sum];$if[$get[wag-sum]<=9999999;$get[wag-sum];9999999]]]]]]];   0   ]]

      $let[wave-give;$if[$getVar[wave-give;$get[user]]!=;$if[$getVar[wave-give;$get[user]]<=9;   $getVar[wave-give;$get[user]]   ;$if[$getVar[wave-give;$get[user]]<=99;   $getVar[wave-give;$get[user]]  ;$if[$getVar[wave-give;$get[user]]<=999;  $getVar[wave-give;$get[user]]  ;$if[$getVar[wave-give;$get[user]]<=9999;  $getVar[wave-give;$get[user]] ;$if[$getVar[wave-give;$get[user]]<=99999; $getVar[wave-give;$get[user]] ;$if[$getVar[wave-give;$get[user]]<=999999; $getVar[wave-give;$get[user]];$if[$getVar[wave-give;$get[user]]<=9999999;$getVar[wave-give;$get[user]];9999999]]]]]]];   0   ]]
      $let[wave-gotten;$if[$getVar[wave-gotten;$get[user]]!=;$if[$getVar[wave-gotten;$get[user]]<=9;   $getVar[wave-gotten;$get[user]]   ;$if[$getVar[wave-gotten;$get[user]]<=99;   $getVar[wave-gotten;$get[user]]  ;$if[$getVar[wave-gotten;$get[user]]<=999;  $getVar[wave-gotten;$get[user]]  ;$if[$getVar[wave-gotten;$get[user]]<=9999;  $getVar[wave-gotten;$get[user]] ;$if[$getVar[wave-gotten;$get[user]]<=99999; $getVar[wave-gotten;$get[user]] ;$if[$getVar[wave-gotten;$get[user]]<=999999; $getVar[wave-gotten;$get[user]];$if[$getVar[wave-gotten;$get[user]]<=9999999;$getVar[wave-gotten;$get[user]];9999999]]]]]]];   0   ]]
      $let[wave-sum;$sum[$replace[$getVar[wave-gotten;$get[user]]; ;;-1];$replace[$getVar[wave-give;$get[user]]; ;;-1]]]
      $let[wave;$if[$get[wave-sum]!=;$if[$get[wave-sum]<=9;   $get[wave-sum]   ;$if[$get[wave-sum]<=99;   $get[wave-sum]  ;$if[$get[wave-sum]<=999;  $get[wave-sum]  ;$if[$get[wave-sum]<=9999;  $get[wave-sum] ;$if[$get[wave-sum]<=99999; $get[wave-sum] ;$if[$get[wave-sum]<=999999; $get[wave-sum];$if[$get[wave-sum]<=9999999;$get[wave-sum];9999999]]]]]]];   0   ]]

      $color[$getUserVar[color;$get[user]]]
      $author[$username[$get[userID]]'s roleplay counter;$userAvatar[$get[userID]]]
      $addField[**Wholesome:**;\`\`\`swift
Type     | Gotten  | Given   | Total   
---------+---------+---------+---------
Blush    | $get[blush-gotten] | $get[blush-give] | $get[blush]
Boop     | $get[boop-gotten] | $get[boop-give] | $get[boop]
Cheer    | $get[cheer-gotten] | $get[cheer-give] | $get[cheer]
Cuddle   | $get[cuddle-gotten] | $get[cuddle-give] | $get[cuddle]
Dance    | $get[dance-gotten] | $get[dance-give] | $get[dance]
Feed     | $get[feed-gotten] | $get[feed-give] | $get[feed]
Glomp    | $get[glomp-gotten] | $get[glomp-give] | $get[glomp]
Handhold | $get[handhold-gotten] | $get[handhold-give] | $get[handhold]
Happy    | $get[happy-gotten] | $get[happy-give] | $get[happy]
Highfive | $get[highfive-gotten] | $get[highfive-give] | $get[highfive]
Hug      | $get[hug-gotten] | $get[hug-give] | $get[hug]
Kiss     | $get[kiss-gotten] | $get[kiss-give] | $get[kiss]
Laugh    | $get[laugh-gotten] | $get[laugh-give] | $get[laugh]
Lick     | $get[lick-gotten] | $get[lick-give] | $get[lick]
\`\`\`]
      $addField[;\`\`\`swift
Love     | $get[love-gotten] | $get[love-give] | $get[love]
Lurk     | $get[lurk-gotten] | $get[lurk-give] | $get[lurk]
Nom      | $get[nom-gotten] | $get[nom-give] | $get[nom]
Nuzzle   | $get[nuzzle-gotten] | $get[nuzzle-give] | $get[nuzzle]
Pat      | $get[pat-gotten] | $get[pat-give] | $get[pat]
Peck     | $get[peck-gotten] | $get[peck-give] | $get[peck]
Poke     | $get[poke-gotten] | $get[poke-give] | $get[poke]
Pout     | $get[pout-gotten] | $get[pout-give] | $get[pout]
Sleep    | $get[sleep-gotten] | $get[sleep-give] | $get[sleep]
Thumbsup | $get[thumbsup-gotten] | $get[thumbsup-give] | $get[thumbsup]
Tickle   | $get[tickle-gotten] | $get[tickle-give] | $get[tickle]
Wag      | $get[wag-gotten] | $get[wag-give] | $get[wag]
Wave     | $get[wave-gotten] | $get[wave-give] | $get[wave]
\`\`\`]
      $addActionRow
      $addButton[counter~positive~$authorID~$get[userID];Positive;Primary;;true]
      $addButton[counter~neutral~$authorID~$get[userID];Neutral;Secondary;;false]
      $addButton[counter~negative~$authorID~$get[userID];Negative;Secondary;;false]
    `
  }
];

export default commands;
