name: Generate Changelog

on:
  push:
    branches:
      - V1.0.0
      - Beta
      - backup-branch
  pull_request:
    branches:
      - V1.0.0
      - Beta
      - backup-branch
  release:
    types: [published]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Set Git config
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

      - name: Generate Changelog
        run: npm run release

      - name: Commit changelog
        run: |
          git add CHANGELOG.md package.json
          git commit -m "chore(release): 1.0.1"
          git push